#!/usr/bin/env bash
# locale.sh — 从受训到独立执业的成长路径（中国大陆 locale） SOP walkthrough for 心理咨询 / 心理治疗(临床实践者视角 — 接案与评估 / 个案概念化 / 主流流派技术(CBT 与第三浪潮 / 精神动力 / 人本存在 / 家庭系统 / 创伤治疗) / 伦理边界与危机干预 / 督导与个人成长 / 执业形态与经营 — 涵盖中国大陆行业现状 + 欧美持照体系,两套体系差异极大).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="心理咨询 / 心理治疗(临床实践者视角 — 接案与评估 / 个案概念化 / 主流流派技术(CBT 与第三浪潮 / 精神动力 / 人本存在 / 家庭系统 / 创伤治疗) / 伦理边界与危机干预 / 督导与个人成长 / 执业形态与经营 — 涵盖中国大陆行业现状 + 欧美持照体系,两套体系差异极大)"
WORKFLOW="从受训到独立执业的成长路径（中国大陆 locale）"

usage() {
  cat <<EOF
locale.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./locale.sh             # interactive
  ./locale.sh --dry-run
  ./locale.sh --json
  ./locale.sh --explain
  ./locale.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "从受训到独立执业的成长路径（中国大陆 locale）" 工作流。

一句话: 在「没有法定统一准入」的中国大陆，把一个想入行的人从「学习 / 受训」带到「能相对被信任地执业」——路径不是「考一个证就上岗」，而是「学历 / 系统受训 + 长期督导 + 个人体验 + 在认证混乱市场里锚定专业身份」的拼图，且充满营销噪音。

入门 SOP 共 6 步, 失败模式自检 5 项。

相关心智模型:
  • 治疗关系 / 共同要素 > 单一技术: 这一行的资深人默认「治疗关系的质量、共情、期望、来访者因素」这些**跨流派共有的共同要素**对疗效的解释力,可能不亚于任一流派的特定技术 —— 所以「学对了流派」从来不够,「谁来做、和来访者建立了什么
  • 症状是有功能 / 是适应,不是单纯的「病」: 这一行的人看一个症状,默认先问「它在为这个人 / 这个系统**做什么**」—— 症状常是某个困境下能找到的最优解、是适应而非缺陷,去病理化地理解它,比急着「消除」它更接近治疗。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**认清「没有法定统一准入」这一前提**：先理解 2017 年后市场现状——大量「山寨证书 / 速成班」是营销噪音，「考个证」既不是法定准入、也不等于胜任力。这一步是**认知前提**，跳过它会被营销带进坑。"
  "**学历 / 系统连续培训**：走相对扎实的路径——临床与咨询心理学的学历教育（北师大 / 北大 / 华东师大等院校项目），或长程系统连续培训（中德 / 中挪 / 中美等精神分析连续培训项目、简单心理 Uni / 壹心理学院等的系统课程）。**输出**=系统的理论与技术训练基础。"
  "**督导下执业 + 长期督导**：在督导师的督导下接案、累计实务经验；督导是国内最实质的专业把关机制之一（中国心理学会注册系统的督导师名录是找合格督导的相对可信入口）。"
  "**个人体验**：接受个人体验 / 受训分析（动力学取向尤其强调）——了解自己作为工具。"
  "**在认证混乱市场里锚定专业身份**：进入**中国心理学会临床与咨询心理学注册系统**（注册心理师 / 督导师身份及其继续教育、督导时数要求）——这是 2017 取消国家证后**国内最接近行业公认门槛的标准**，是对抗市场噪音的工具。"
  "**执业形态选择 + 持续教育**：选择机构执业 / 平台执业（简单心理 / 壹心理等平台后台 + 抽成派单规则）/ 私人执业（国内缺一体化 EHR，需自行拼凑合规工具）；持续受训、督导、继续教育是常态。"
)
declare -a FAILURE_MODES=(
  "**「考证躺赚 / 21 天速成」**：被营销骗——后果是钱白花、对自己资质有错误预期、且对来访者不负责。避免：认清 2017 后无法定统一准入、证书 ≠ 胜任力。"
  "**「无督导执业」**：自己接案、没人把关——后果是临床判断 / 伦理 / 危机处理无人把关，对来访者和从业者都危险。避免：长期督导是国内最实质的把关机制，不能省。"
  "**「集邮式考证」**：在零散工作坊和各种证书之间漂——后果是无系统受训谱系、无累积。避免：聚焦学历 / 连续培训 + 注册系统 + 督导。"
  "**「被『助人很美好』鸡汤掩盖职业现实」**：忽视收入不稳定、替代性创伤、共情耗竭——后果是职业规划缺位、耗竭风险高。避免：把职业经济现实与自我照顾当成长的一部分。"
  "**CLI 化暗示**：抽进国内成长路径自检——「我是否理解 2017 后中国没有法定统一准入这一前提？」「我走的是系统学历 / 连续培训，还是零散考证？」「我有没有持续的、有质量的督导？」「我有没有把个人体验当回事？」「我是否进了（或在走向）中国心理学会注册系统作为专业锚点？」「我对国内从业者的收入与职业风险现实有没有清醒认知？」"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "locale-walkthrough"
fi
