#!/usr/bin/env bash
# workflow-3.sh — 危机干预流程（自杀 / 自伤 / 虐待 / 急性精神病性发作 的识别 → 评估 → 立即导向危机资源 / 转介 / 上级督导） SOP walkthrough for 心理咨询 / 心理治疗(临床实践者视角 — 接案与评估 / 个案概念化 / 主流流派技术(CBT 与第三浪潮 / 精神动力 / 人本存在 / 家庭系统 / 创伤治疗) / 伦理边界与危机干预 / 督导与个人成长 / 执业形态与经营 — 涵盖中国大陆行业现状 + 欧美持照体系,两套体系差异极大).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="心理咨询 / 心理治疗(临床实践者视角 — 接案与评估 / 个案概念化 / 主流流派技术(CBT 与第三浪潮 / 精神动力 / 人本存在 / 家庭系统 / 创伤治疗) / 伦理边界与危机干预 / 督导与个人成长 / 执业形态与经营 — 涵盖中国大陆行业现状 + 欧美持照体系,两套体系差异极大)"
WORKFLOW="危机干预流程（自杀 / 自伤 / 虐待 / 急性精神病性发作 的识别 → 评估 → 立即导向危机资源 / 转介 / 上级督导）"

usage() {
  cat <<EOF
workflow-3.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-3.sh             # interactive
  ./workflow-3.sh --dry-run
  ./workflow-3.sh --json
  ./workflow-3.sh --explain
  ./workflow-3.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "危机干预流程（自杀 / 自伤 / 虐待 / 急性精神病性发作 的识别 → 评估 → 立即导向危机资源 / 转介 / 上级督导）" 工作流。

一句话: 当来访者出现自杀 / 自伤 / 对他人危险 / 受虐 / 急性精神病性发作的信号时，治疗师从「识别」走到「评估严重度」再走到「立即导向危机资源 / 转介 / 调动上级督导」——目标是把来访者安全地接入比单次治疗会谈更高强度的安全网。

入门 SOP 共 5 步, 失败模式自检 6 项。

相关心智模型:
  • 治疗关系 / 共同要素 > 单一技术: 这一行的资深人默认「治疗关系的质量、共情、期望、来访者因素」这些**跨流派共有的共同要素**对疗效的解释力,可能不亚于任一流派的特定技术 —— 所以「学对了流派」从来不够,「谁来做、和来访者建立了什么
  • 症状是有功能 / 是适应,不是单纯的「病」: 这一行的人看一个症状,默认先问「它在为这个人 / 这个系统**做什么**」—— 症状常是某个困境下能找到的最优解、是适应而非缺陷,去病理化地理解它,比急着「消除」它更接近治疗。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**识别（不回避地问）**：察觉危机信号后，**直接、具体地问**——不要因为「怕问了反而诱导」而回避（这是被反复证伪的误解）。自杀风险要直接问到念头、计划、手段可得性、时间线、既往尝试。"
  "**用结构化工具评估严重度**：用 C-SSRS（哥伦比亚自杀严重程度评定量表）等结构化工具把「问到位」标准化——评估的目的是**分诊**（决定下一步去向的强度），不是「做完就免责」。**没有任何工具能预测自杀**。"
  "**立即导向相应强度的资源 / 转介**（这是核心步骤，硬边界）："
  "**调动上级督导 / 同行支持**：危机个案**不独自扛**——尽快（理想是当天）联系督导 / 上级 / 同行咨询，把决策放进专业支持网。"
  "**完整记录 + 安排随访**：把识别到的信号、评估结果、采取的行动、转介去向、安全计划、随访安排全部记录（危机记录的法律与伦理要求比常规记录更严）；落实**加密的、明确时间的随访**。"
)
declare -a FAILURE_MODES=(
  "**「不敢问自杀」**：怕「问了反而诱导」而回避直接询问——这是被反复证伪的误解，后果是漏评危机。避免：危机信号出现就直接、具体地问，回避才是危险的。"
  "**「把风险评估当免责清单」**：做完 C-SSRS 就觉得「我尽到责任了」——后果是把分诊工具误当预测工具、误当法律护身符。避免：评估是为了决定下一步去向的强度，且风险是动态的、要反复评。"
  "**「独自扛高危个案」**：不调动督导 / 上级 / 同行——后果是来访者风险增加 + 治疗师法律与耗竭风险。避免：危机个案当天联系专业支持网。"
  "**「给个号码就算转介了」**：不确认转介是否真的接上——后果是来访者卡在转介缝隙里。避免：跟进到转介确实衔接。"
  "**「危机资源清单是危机当下才现查」**：没有预先维护的本地资源清单——后果是危机时手忙脚乱。避免：预先备好本地急诊 / 热线 / 精神科 / 强制报告流程。"
  "**CLI 化暗示**：抽进危机响应自检——「我是否直接、具体地问了风险（含计划 / 手段可得性 / 时间线 / 既往尝试）？」「我是否用了结构化工具并记录？」「来访者的下一步安全去向是否已落实、是否与风险等级匹配？」「我是否已（或将在当天）联系督导 / 上级？」「随访是否已安排了明确时间？」「涉及虐待 / 对他人危险时，我是否履行了法定报告 / 警告义务？」——**每一项都是 yes 才算危机响应闭环。**"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-3-walkthrough"
fi
