#!/usr/bin/env bash
# workflow-4.sh — 转介流程（识别超出胜任力范围 / 需要其他资源 → 衔接到合适的同行或机构） SOP walkthrough for 心理咨询 / 心理治疗(临床实践者视角 — 接案与评估 / 个案概念化 / 主流流派技术(CBT 与第三浪潮 / 精神动力 / 人本存在 / 家庭系统 / 创伤治疗) / 伦理边界与危机干预 / 督导与个人成长 / 执业形态与经营 — 涵盖中国大陆行业现状 + 欧美持照体系,两套体系差异极大).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="心理咨询 / 心理治疗(临床实践者视角 — 接案与评估 / 个案概念化 / 主流流派技术(CBT 与第三浪潮 / 精神动力 / 人本存在 / 家庭系统 / 创伤治疗) / 伦理边界与危机干预 / 督导与个人成长 / 执业形态与经营 — 涵盖中国大陆行业现状 + 欧美持照体系,两套体系差异极大)"
WORKFLOW="转介流程（识别超出胜任力范围 / 需要其他资源 → 衔接到合适的同行或机构）"

usage() {
  cat <<EOF
workflow-4.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-4.sh             # interactive
  ./workflow-4.sh --dry-run
  ./workflow-4.sh --json
  ./workflow-4.sh --explain
  ./workflow-4.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "转介流程（识别超出胜任力范围 / 需要其他资源 → 衔接到合适的同行或机构）" 工作流。

一句话: 当一个个案超出治疗师的胜任力范围、需要不同治疗形态、或需要医疗 / 精神科 / 社会服务等额外资源时，治疗师从「识别需要转介」走到「把来访者扎实地衔接到合适的人 / 机构」——转介**不是把人推走，是负责任地接力**。

入门 SOP 共 4 步, 失败模式自检 5 项。

相关心智模型:
  • 治疗关系 / 共同要素 > 单一技术: 这一行的资深人默认「治疗关系的质量、共情、期望、来访者因素」这些**跨流派共有的共同要素**对疗效的解释力,可能不亚于任一流派的特定技术 —— 所以「学对了流派」从来不够,「谁来做、和来访者建立了什么
  • 症状是有功能 / 是适应,不是单纯的「病」: 这一行的人看一个症状,默认先问「它在为这个人 / 这个系统**做什么**」—— 症状常是某个困境下能找到的最优解、是适应而非缺陷,去病理化地理解它,比急着「消除」它更接近治疗。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**识别转介需要**：诚实判断「这个个案是不是超出我的胜任力范围 / 需要我提供不了的东西」——胜任力 = 训练 + 督导经验 + 持续教育覆盖的范围，不是「我愿不愿意试」。"
  "**和来访者坦诚沟通转介理由**：不让来访者感觉「被嫌弃 / 被放弃」——说清楚「为什么转介对你更好」，处理可能的被拒感（尤其依恋议题来访者）。"
  "**给出具体、可落实的去向**：不是「你去找个创伤专家吧」，而是给到具体的同行名字 / 机构 / 注册系统名录 / 明确的查找路径；考虑来访者的地理、费用、排期现实。"
  "**完成转介衔接 + 记录**：在来访者同意下与接收方沟通必要信息（守保密、有知情同意）；记录转介理由、去向、沟通内容。"
)
declare -a FAILURE_MODES=(
  "**「超出胜任力还硬接」**：舍不得放手 / 高估自己——伦理违规 + 伤害风险。避免：胜任力是训练 + 督导覆盖的范围，不是意愿；超出就转。"
  "**「转介让来访者感觉被抛弃」**：突兀沟通、不处理被拒感——后果是二次伤害、来访者放弃求助。避免：说清「为什么对你更好」，处理分离与被拒情感。"
  "**「模糊建议当转介」**：「你去找个专家」——后果是来访者卡住、不了了之。避免：给具体名字 / 机构 / 路径，考虑地理费用排期现实。"
  "**「转介后撒手」**：不跟进是否接上——后果是个案在缝隙里掉落。避免：确认衔接，必要时和接收方交接。"
  "**CLI 化暗示**：抽进转介自检——「这个个案是否在我的胜任力范围内（训练 + 督导 + 继续教育覆盖）？」「我给来访者的去向是具体可落实的（一个名字 / 机构 / 明确路径），还是模糊建议？」「我是否处理了来访者可能的被拒 / 被抛弃感？」「转介是否记录、是否跟进了衔接？」"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-4-walkthrough"
fi
