#!/usr/bin/env bash
# workflow-5.sh — 伦理决策流程（遇到伦理两难——保密例外 / 双重关系 / 胜任力边界——怎么走） SOP walkthrough for 心理咨询 / 心理治疗(临床实践者视角 — 接案与评估 / 个案概念化 / 主流流派技术(CBT 与第三浪潮 / 精神动力 / 人本存在 / 家庭系统 / 创伤治疗) / 伦理边界与危机干预 / 督导与个人成长 / 执业形态与经营 — 涵盖中国大陆行业现状 + 欧美持照体系,两套体系差异极大).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="心理咨询 / 心理治疗(临床实践者视角 — 接案与评估 / 个案概念化 / 主流流派技术(CBT 与第三浪潮 / 精神动力 / 人本存在 / 家庭系统 / 创伤治疗) / 伦理边界与危机干预 / 督导与个人成长 / 执业形态与经营 — 涵盖中国大陆行业现状 + 欧美持照体系,两套体系差异极大)"
WORKFLOW="伦理决策流程（遇到伦理两难——保密例外 / 双重关系 / 胜任力边界——怎么走）"

usage() {
  cat <<EOF
workflow-5.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-5.sh             # interactive
  ./workflow-5.sh --dry-run
  ./workflow-5.sh --json
  ./workflow-5.sh --explain
  ./workflow-5.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "伦理决策流程（遇到伦理两难——保密例外 / 双重关系 / 胜任力边界——怎么走）" 工作流。

一句话: 当治疗师遇到一个伦理两难（保密该不该破、这个关系算不算双重关系、要不要接超出范围的个案、AI 记录该不该用），从「察觉这是个伦理问题」走到「一个有依据、有咨询、有记录的决策」——伦理是**硬约束不是建议**，但具体情境常需要结构化推理而非套公式。

入门 SOP 共 5 步, 失败模式自检 6 项。

相关心智模型:
  • 治疗关系 / 共同要素 > 单一技术: 这一行的资深人默认「治疗关系的质量、共情、期望、来访者因素」这些**跨流派共有的共同要素**对疗效的解释力,可能不亚于任一流派的特定技术 —— 所以「学对了流派」从来不够,「谁来做、和来访者建立了什么
  • 症状是有功能 / 是适应,不是单纯的「病」: 这一行的人看一个症状,默认先问「它在为这个人 / 这个系统**做什么**」—— 症状常是某个困境下能找到的最优解、是适应而非缺陷,去病理化地理解它,比急着「消除」它更接近治疗。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**识别「这是一个伦理问题」**：先意识到当前情境有伦理张力——很多伦理失误的根源是根本没把它当伦理问题（如不假思索地接受了来访者的礼物 / 进入了双重关系）。"
  "**查所属伦理守则的相关条款**：明确自己受哪套守则约束（美国 APA 伦理守则 / 英国 BACP 伦理框架 / 中国心理学会注册系统伦理守则——locale 不同，守则不同），查保密、知情同意、双重关系、胜任力、记录的具体条款。"
  "**识别这是「硬规定」还是「需要权衡的两难」**：有些情形守则有明确硬规定（如与当前来访者发生性关系 = 绝对禁止；强制报告 = 法定义务），直接照规定走；有些是真两难（多重关系在小社区不可避免、自我暴露的度），需要结构化权衡。"
  "**咨询督导 / 同行 / 伦理顾问**：伦理两难**不独自决定**——带进督导、找同行咨询、必要时联系专业协会的伦理咨询服务。"
  "**做决策 + 记录推理过程**：落实决策，并把「识别了什么张力、查了哪些条款、咨询了谁、考虑了哪些选项、为什么这样决定」记录下来。"
)
declare -a FAILURE_MODES=(
  "**「没把它当伦理问题」**：不假思索进入双重关系 / 接受礼物 / 做自我暴露——后果是在不知情中违规。避免：对「有张力的情境」保持伦理敏感，先停下来问「这里有伦理问题吗」。"
  "**「凭直觉 / 印象判断，不查守则」**：以为自己记得守则——后果是漏掉明确规定。避免：真遇到就查所属守则的具体条款。"
  "**「独自决定伦理两难」**：不咨询督导 / 同行——后果是被自己的盲点带偏、事后难辩护。避免：伦理两难必带进督导或同行咨询。"
  "**「决策不记录推理」**：做了决定但没写「为什么」——后果是被质疑时无法辩护。避免：记录识别、查证、咨询、选项、理由的全过程。"
  "**「把硬规定当可商量 / 把两难当有标准答案」**：两个方向的错误——前者危险，后者僵化。避免：先分清这是硬规定还是真两难，再决定照走还是权衡。"
  "**CLI 化暗示**：抽进伦理决策自检——「我是否意识到这是个伦理问题？」「我是否查了我所属伦理守则的相关条款（APA / BACP / 中国心理学会，按 locale）？」「这是硬规定还是需要权衡的两难？」「我是否咨询了督导 / 同行 / 伦理顾问？」「我是否记录了决策的推理过程？」"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-5-walkthrough"
fi
