#!/usr/bin/env bash
# workflow-6.sh — 临床督导流程（带个案进督导 → 呈现 → 加工 → 把督导转化为下一次会谈的调整） SOP walkthrough for 心理咨询 / 心理治疗(临床实践者视角 — 接案与评估 / 个案概念化 / 主流流派技术(CBT 与第三浪潮 / 精神动力 / 人本存在 / 家庭系统 / 创伤治疗) / 伦理边界与危机干预 / 督导与个人成长 / 执业形态与经营 — 涵盖中国大陆行业现状 + 欧美持照体系,两套体系差异极大).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="心理咨询 / 心理治疗(临床实践者视角 — 接案与评估 / 个案概念化 / 主流流派技术(CBT 与第三浪潮 / 精神动力 / 人本存在 / 家庭系统 / 创伤治疗) / 伦理边界与危机干预 / 督导与个人成长 / 执业形态与经营 — 涵盖中国大陆行业现状 + 欧美持照体系,两套体系差异极大)"
WORKFLOW="临床督导流程（带个案进督导 → 呈现 → 加工 → 把督导转化为下一次会谈的调整）"

usage() {
  cat <<EOF
workflow-6.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-6.sh             # interactive
  ./workflow-6.sh --dry-run
  ./workflow-6.sh --json
  ./workflow-6.sh --explain
  ./workflow-6.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "临床督导流程（带个案进督导 → 呈现 → 加工 → 把督导转化为下一次会谈的调整）" 工作流。

一句话: 把一个卡住的 / 需要第二双眼睛的个案，从「带进督导」走到「呈现 → 在督导关系里加工 → 把督导所得转化为下一次会谈的具体调整」——督导是这一行**贯穿整个职业生涯**的质量保障与成长机制，不是只有受训期才需要。

入门 SOP 共 5 步, 失败模式自检 6 项。

相关心智模型:
  • 治疗关系 / 共同要素 > 单一技术: 这一行的资深人默认「治疗关系的质量、共情、期望、来访者因素」这些**跨流派共有的共同要素**对疗效的解释力,可能不亚于任一流派的特定技术 —— 所以「学对了流派」从来不够,「谁来做、和来访者建立了什么
  • 症状是有功能 / 是适应,不是单纯的「病」: 这一行的人看一个症状,默认先问「它在为这个人 / 这个系统**做什么**」—— 症状常是某个困境下能找到的最优解、是适应而非缺陷,去病理化地理解它,比急着「消除」它更接近治疗。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**选个案 + 准备呈现**：决定带哪个个案进督导（通常是卡住的 / 有风险的 / 有强反移情的）、准备呈现材料——个案概念化、近期进展、卡点、（在知情同意与保密处理下的）会谈片段 / 逐字稿 / 录音。"
  "**呈现个案**：向督导师 / 督导小组呈现——既呈现「来访者发生了什么」（内容），也呈现「治疗关系里发生了什么、我有什么反应」（过程与反移情）。"
  "**在督导关系里加工**：和督导师一起重新看这个个案——可能是重新概念化、识别盲点、加工反移情、讨论伦理或危机维度、或就治疗联盟的破裂找修复路径。"
  "**转化为下一次会谈的具体调整**：把督导所得落成「下一次会谈我会具体做什么不同」——督导如果不落到行动上就只是清谈。"
  "**记录（受督导阶段）+ 持续性**：受督导阶段记录督导时数与内容；把督导当**贯穿职业生涯**的常态，而非「受训期的任务」。"
)
declare -a FAILURE_MODES=(
  "**「不准备就来督导」**：把督导当漫谈——后果是督导师无据可依、时间浪费。避免：带着具体卡点和准备好的呈现材料。"
  "**「只呈现内容不呈现过程 / 反移情」**：怕暴露「没做好」而回避——后果是督导只能给技术建议，碰不到关系层。避免：主动呈现自己的反应与盲点，这才是督导最有价值的地方。"
  "**「把督导当要答案」**：等督导师给标准答案——后果是错过「加工」的过程价值。避免：督导是协作的理解过程。"
  "**「督导不落到行动」**：督导完治疗室里照旧——后果是督导与治疗脱节、白做。避免：每次督导收尾问「下次会谈我会做什么不同」。"
  "**「持照后停止一切督导」**：把督导当受训期任务——后果是盲点累积、职业孤立、耗竭风险升高。避免：把督导 / 同辈咨询当贯穿职业生涯的常态。"
  "**CLI 化暗示**：抽进督导自检——「我带进督导的个案是有具体卡点的、还是泛泛而谈？」「我有没有呈现治疗关系里发生的、我自己的反移情反应？」「这次督导有没有落成『下次会谈我会做什么不同』？」「危机 / 伦理两难个案，我有没有及时带进督导 / 同行咨询？」"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-6-walkthrough"
fi
