#!/usr/bin/env bash
# agent.sh — Agent 决策助手 for AI 产品经理 (LLM 应用 / 生成式 AI / Agent 产品 / Copilot 嵌入 — 跨模型评估 / 工作流设计 / 产品-工程协同).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="AI 产品经理 (LLM 应用 / 生成式 AI / Agent 产品 / Copilot 嵌入 — 跨模型评估 / 工作流设计 / 产品-工程协同)"
TOPIC="Agent"

usage() {
  cat <<EOF
agent.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 1 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./agent.sh             # interactive
  ./agent.sh --dry-run   # walk through but no file
  ./agent.sh --json      # JSON to stdout
  ./agent.sh --explain   # show backing playbook rules + mental models
  ./agent.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 Agent 主题下的 playbook 规则组合成交互树。

基于 1 条规则:
  • 如果 遇到新 AI 需求 → 则 先问「这是预定义路径就能解决的 workflow,还是真的需要 LLM 自主决策的 agent」,默认假设是 workf

相关心智模型:
  • Eval 是地基,不是可选项（别 vibe-check）: 「AI 产品的『好』不是看几个 case 觉得行就 ship —— 是先针对你**自己产品的失败模式**建一套可重复、可回归的系统化测量;没有 eval 就是在瞎改。」
  • 先 error analysis,再加功能（PM 亲自看 trace）: 「质量上不去时,资深 AI PM 的第一反应**不是加功能**,是 PM 亲自拉 10-50 个真实 trace（trace 条数量级见 Hamel field-guide T03-S001 / ev

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "遇到新 AI 需求"
)
declare -a RULE_ACTIONS=(
  "先问「这是预定义路径就能解决的 workflow,还是真的需要 LLM 自主决策的 agent」,默认假设是 workflow —— 多数需求是 workflow,把不是 agent 的需求做成 agent 是无谓的不可靠 + 成本"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agent-decision"
fi
