#!/usr/bin/env bash
# topic-1.sh — —— 决策助手 for AI 产品经理 (LLM 应用 / 生成式 AI / Agent 产品 / Copilot 嵌入 — 跨模型评估 / 工作流设计 / 产品-工程协同).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="AI 产品经理 (LLM 应用 / 生成式 AI / Agent 产品 / Copilot 嵌入 — 跨模型评估 / 工作流设计 / 产品-工程协同)"
TOPIC="——"

usage() {
  cat <<EOF
topic-1.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 7 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-1.sh             # interactive
  ./topic-1.sh --dry-run   # walk through but no file
  ./topic-1.sh --json      # JSON to stdout
  ./topic-1.sh --explain   # show backing playbook rules + mental models
  ./topic-1.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 —— 主题下的 playbook 规则组合成交互树。

基于 7 条规则:
  • 如果 质量或方向不明 → 则 (产品不行、不知道改哪、要定义成功标准),则 PM 先亲自拉 10-50 个真实 trace 逐条标错、自下而上归类成 
  • 如果 遇到 AI 技术决策 → 则 (该用什么技术实现一个需求),则默认从最便宜的假设起 —— prompt-only → RAG → agent → fi
  • 如果 要判断 AI 输出质量 → 则 用 binary pass/fail + 失败频率计数排优先级,不用模糊的 1-5 / 1-10 分,不用「我觉得这个重
  • 如果 是新 AI 产品或新需求要落地 → 则 默认 provider SDK + pgvector + 先做 error analysis 起步,不要一上来堆 Lan
  • 如果 要 ship 一个 agent → 则 上线标准是 pass^k（同任务跑 k 次的稳定通过率),不是「demo 跑通一次」 —— 并且要有失败回退 + 用户控
  • 如果 LLM-as-judge 要上线 → 则 必须先和人工标注校准到 75-90% 一致再 scale,用 binary 不用 1-5 分 —— 没校准的 judge
  • 如果 做架构决策 → 则 LLM 接入用 LiteLLM / provider SDK 抽象层、工具集成走 MCP,不 hardcode 单一 p

相关心智模型:
  • Eval 是地基,不是可选项（别 vibe-check）: 「AI 产品的『好』不是看几个 case 觉得行就 ship —— 是先针对你**自己产品的失败模式**建一套可重复、可回归的系统化测量;没有 eval 就是在瞎改。」
  • 先 error analysis,再加功能（PM 亲自看 trace）: 「质量上不去时,资深 AI PM 的第一反应**不是加功能**,是 PM 亲自拉 10-50 个真实 trace（trace 条数量级见 Hamel field-guide T03-S001 / ev

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "质量或方向不明"
  "遇到 AI 技术决策"
  "要判断 AI 输出质量"
  "是新 AI 产品或新需求要落地"
  "要 ship 一个 agent"
  "LLM-as-judge 要上线"
  "做架构决策"
)
declare -a RULE_ACTIONS=(
  "(产品不行、不知道改哪、要定义成功标准),则 PM 先亲自拉 10-50 个真实 trace 逐条标错、自下而上归类成 failure mode,再做任何决策 —— 不要先建指标 dashboard,不要凭直觉加功能"
  "(该用什么技术实现一个需求),则默认从最便宜的假设起 —— prompt-only → RAG → agent → finetune 是一道阶梯,只在当前层被证明不够时才升级到下一层,且每次升级要说得出「为什么低层不够」"
  "用 binary pass/fail + 失败频率计数排优先级,不用模糊的 1-5 / 1-10 分,不用「我觉得这个重要」 —— 专家做二元判断更可靠,频率比直觉更能定优先级"
  "默认 provider SDK + pgvector + 先做 error analysis 起步,不要一上来堆 LangChain 类重框架、不要先买 eval 平台 —— 「默认用最轻的能跑的,感到真实痛点再上框架」"
  "上线标准是 pass^k（同任务跑 k 次的稳定通过率),不是「demo 跑通一次」 —— 并且要有失败回退 + 用户控制权 + 沙箱大量测试 + guardrails"
  "必须先和人工标注校准到 75-90% 一致再 scale,用 binary 不用 1-5 分 —— 没校准的 judge 等于没用,团队很快不信它,且校准是 domain-specific 的、不能外包给 vendor 的 pre-built judge"
  "LLM 接入用 LiteLLM / provider SDK 抽象层、工具集成走 MCP,不 hardcode 单一 provider、不选私有 tool 协议,且把「这工具还独立吗 / 厂商中立吗」和功能并列评估 —— 模型每几周一版,hardcode 的应用面临 recurring migration projects"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-1-decision"
fi
