#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 法律执业 (中国法).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="法律执业 (中国法)"
DIM_COUNT=3

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (3 个):
  9.1 法律关系定性
  9.2 程序前置审查
  9.3 证据评估

背后的心智模型:
  • 程序正义先于实体: 程序错了, 实体再对也白搭。诉讼时效 / 管辖 / 当事人主体 / 证据规则的程序问题, 一个错了案子就死了。
  • 证据决定胜负, 不是法条: 法条人人会查, 但证据是子弹。证据不到「高度盖然性」标准, 法条再硬也撑不起来。
  • 风险防范优于事后救济: 合同审核 → 起草 → 谈判 → 履行 → 纠纷, 风险阶段越前置成本越低。事后打官司是最贵的救济方式。

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "法律关系定性"
  "程序前置审查"
  "证据评估"
)
declare -a DIM_QUESTIONS=(
  "当事人之间的法律关系是什么 (合同 / 侵权 / 物权 / 婚姻家庭 / 劳动 / 行政 / 刑事)"
  "时效 / 管辖 / 当事人主体 / 受案范围 / 必要的前置程序 (调解 / 仲裁条款)"
  "现有证据是否充分 / 链条是否闭合 / 待补强的证据"
)
declare -a DIM_SOURCES=(
  "当事人陈述 + 关键文件 (合同 / 单据 / 通信)"
  "时间线 + 当事人信息 + 合同条款"
  "客户提供的证据 + 主张事实清单"
)
declare -a DIM_OUTPUT_FORMATS=(
  "法律关系类型 + 请求权基础 (法条 + 司法解释)"
  "程序合规度 + 致命问题 (如有)"
  "证据强度 (1-10) + 关键缺口 + 补强方向"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
