#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 中国法律执业.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="中国法律执业"
DIM_COUNT=5

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (5 个):
  9.1 法律状态评估 (法源 + 司法解释 + 类案)
  9.2 程序四要素 (管辖 / 时效 / 证据 / 主体)
  9.3 实体法分析 (民商事 / 刑事 / 行政)
  9.4 风险 + 成本 + 可执行性评估
  9.5 客户期望管理 + 沟通 (软实力)

背后的心智模型:
  • 程序先于实体 — 时效 / 管辖 / 主体 错一个就输: 实体法 (民法典 / 刑法 / 公司法) 决定「谁对谁错」, 程序法 (民诉 / 刑诉 / 行诉) 决定「能不能进法院」. 程序错了, 实体上多对都没用.
  • 法律不是结论, 是程序 + 论证 — 「依法」≠「我说的就对」: 法律给的不是「答案」, 是「论证路径 + 证据规则 + 程序」. 同一事实下不同律师 / 不同法官可能得出不同结果, 这不是错, 是法律的本质.
  • 证据是诉讼核心 — 没证据 = 没事实: 法律事实 ≠ 客观事实. 法律事实是有证据证明的事实. 没证据等于法律上没发生.

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "法律状态评估 (法源 + 司法解释 + 类案)"
  "程序四要素 (管辖 / 时效 / 证据 / 主体)"
  "实体法分析 (民商事 / 刑事 / 行政)"
  "风险 + 成本 + 可执行性评估"
  "客户期望管理 + 沟通 (软实力)"
)
declare -a DIM_QUESTIONS=(
  "现行法律 + 司法解释 + 指导性案例 + 类案 + 法官倾向 + 立法说明 + 学术解读"
  "- **管辖**: 级别 + 地域 + 协议 + 专属 + 涉外"
  "- **民商事**: 民法典 + 单行法 + 合同 + 类案"
  "- **胜诉概率** (基于法律状态 + 证据 + 类案)"
  "客户具体期望 + 教育水平 + 行业 + 紧迫度 + 既往法律经验 + 情绪状态"
)
declare -a DIM_SOURCES=(
  "flk.npc.gov.cn (法源) + court.gov.cn (司法解释 + 公报) + 北大法宝 (案例 + 学术) + 裁判文书网 + 头部所公开解读"
  "民诉法 / 刑诉法 / 行诉法 + 各类司法解释 + 当事人证据 + 调查"
  "flk.npc.gov.cn + 学术教材 (王利明 / 张明楷 等) + 头部所解读"
  "财产调查 + 被告资产 + 执行信息公开网 + 诉讼成本估算"
  "接谈 + 持续沟通 + 委托合同 + 风险提示书"
)
declare -a DIM_OUTPUT_FORMATS=(
  "法律状态摘要 + 类案多数倾向 + 争议点 + 不确定性"
  "四要素逐项评估 + 风险点 + 缺口 (能不能补)"
  "实体法主张 + 抗辩 + 证据匹配 + 法律解释路径 (多选)"
  "接 / 不接代理决策 + 客户费用预告 + 替代方案推荐"
  "期望写进委托合同 + 风险提示书 + 持续节点告知"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
