#!/usr/bin/env bash
# ai-search-geo-llmo-2024-2026.sh — AI Search 优化 (GEO / LLMO) — 2024-2026 新流派 SOP walkthrough for SEO 专家.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="SEO 专家"
WORKFLOW="AI Search 优化 (GEO / LLMO) — 2024-2026 新流派"

usage() {
  cat <<EOF
ai-search-geo-llmo-2024-2026.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./ai-search-geo-llmo-2024-2026.sh             # interactive
  ./ai-search-geo-llmo-2024-2026.sh --dry-run
  ./ai-search-geo-llmo-2024-2026.sh --json
  ./ai-search-geo-llmo-2024-2026.sh --explain
  ./ai-search-geo-llmo-2024-2026.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "AI Search 优化 (GEO / LLMO) — 2024-2026 新流派" 工作流。

一句话: 在 AI Overviews / ChatGPT / Perplexity / Claude 中被引用比传统排名重要 — Generative Engine Optimization.

入门 SOP 共 5 步, 失败模式自检 4 项。

相关心智模型:
  • People-first content > Search engine first content (核心 PASS): Google 长期主线是「为用户写, 不为搜索引擎写」. 套路 6 个月一过期, 真实价值是长期资产.
  • Pillar + Cluster 内容架构 (核心 PASS): Pillar (主题枢纽) + Cluster (长尾分支) 是中型品牌内容 SEO 的标准架构.

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**AI Search 监控接入** (Week 1):"
  "**内容 GEO 优化** (Week 2-4):"
  "**E-E-A-T 强化** (Week 2-4):"
  "**被 LLM 引用** (持续):"
  "**跨平台 AI 可见度** (持续):"
)
declare -a FAILURE_MODES=(
  "内容结构散漫 → LLM 没法精准引用"
  "数据密度低 → LLM 引用首选高密度内容"
  "Schema markup 缺失 → AI 解析困难"
  "不监控 → 不知道哪些内容被引用"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "ai-search-geo-llmo-2024-2026-walkthrough"
fi
