#!/usr/bin/env bash
# 3.sh — 创意素材生产 (黄金 3 秒法则) SOP walkthrough for 短视频投流.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="短视频投流"
WORKFLOW="创意素材生产 (黄金 3 秒法则)"

usage() {
  cat <<EOF
3.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./3.sh             # interactive
  ./3.sh --dry-run
  ./3.sh --json
  ./3.sh --explain
  ./3.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "创意素材生产 (黄金 3 秒法则)" 工作流。

一句话: 短视频投流素材的标准生产流程 — 黄金 3 秒抛卖点 + 钩子 + 转化点 三件套.

入门 SOP 共 6 步, 失败模式自检 4 项。

相关心智模型:
  • 创意是因, 出价是果 (核心 PASS): 没有好素材, 怎么投都跑不动. 投流的杠杆 90% 在创意, 10% 在出价 / 定向.
  • 学习期不动是铁律 (核心 PASS): 千川计划前 50 转化是算法学习期, 任何调整都重置学习. 学完才能优化.

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**拆解类目爆款** (Day 1): 蝉小红 / 蝉妈妈 找类目 top 10 跑量素材, 拆其结构 (3 秒 / 钩子 / 转化点)"
  "**写脚本 / 做素材** (Day 2-4): 同卖点 5-10 个不同角度 (痛点开头 / 反差 / 解决方案 / 真人感)"
  "**3 秒钩子设计** (Day 2-4): 前 3 秒抛核心卖点 / 反差 / 痛点, 否则 80% 划走"
  "**15-30 秒结构** (Day 2-4): 5-15 秒钩子 (痛点 + 反差) → 15-30 秒产品 + 转化"
  "**真人感要素**: 真人出境 / 真实场景 / 真实使用 (反对 AI 全自动直发)"
  "**投放跑测** (Day 5-7): 每组 3-5 条投放, 让系统挑出最优"
)
declare -a FAILURE_MODES=(
  "一个素材投到死 → 衰减后 ROAS 暴跌"
  "全 AI 生成不加人工 → 平台识别限流"
  "没有钩子 / 转化点结构 → 跑不出量"
  "同质化素材 (5 条都用同一钩子) → 系统挑不出最优"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "3-walkthrough"
fi
