#!/usr/bin/env bash
# 50.sh — 新计划冷启动 (前 50 转化) SOP walkthrough for 短视频投流.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="短视频投流"
WORKFLOW="新计划冷启动 (前 50 转化)"

usage() {
  cat <<EOF
50.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./50.sh             # interactive
  ./50.sh --dry-run
  ./50.sh --json
  ./50.sh --explain
  ./50.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "新计划冷启动 (前 50 转化)" 工作流。

一句话: 千川新计划从 0 到稳定跑量的标准动作 — 14 天内累积 ≥ 50 转化, 算法学完模型.

入门 SOP 共 6 步, 失败模式自检 4 项。

相关心智模型:
  • 创意是因, 出价是果 (核心 PASS): 没有好素材, 怎么投都跑不动. 投流的杠杆 90% 在创意, 10% 在出价 / 定向.
  • 学习期不动是铁律 (核心 PASS): 千川计划前 50 转化是算法学习期, 任何调整都重置学习. 学完才能优化.

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**创意素材准备** (Day 0): 一个广告组准备 3-5 条不同创意素材 (不同角度 / 不同钩子)"
  "**建组建计划** (Day 0): OCPM 智能出价, 出价按目标 ROAS 倒推 (类目 benchmark 找蝉妈妈)"
  "**学习期铁律** (Day 0-7, ≤ 50 转化): 不动出价 / 不动定向 / 不动素材 / 不动预算"
  "**跑量评估** (Day 7-14): 观察曝光 / CTR / CVR / ROAS — 哪条素材跑得动就放大"
  "**跑得动的处理** (Day 14+): 跑出量的素材复制 + 微调出价 (±10%) 持续放大"
  "**跑不动的处理** (Day 14+): 跑不动的计划砍掉, 不要硬撑 — 没有学习期保底数据"
)
declare -a FAILURE_MODES=(
  "学习期硬调出价 → 算法重置学习, 50 转化重计"
  "一个组只放 1 条素材 → 没法 A/B 测试"
  "一上来就调高预算 → 模型来不及学习, 跑乱"
  "计划跑不动还硬撑 → 浪费预算, 应该立刻砍"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "50-walkthrough"
fi
