#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 抖音直播带货 (商家 / 主播 / 直播间运营 + 千川 / 巨量引擎广告投放 + 选品 + 流量场承接 + 合规).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="抖音直播带货 (商家 / 主播 / 直播间运营 + 千川 / 巨量引擎广告投放 + 选品 + 流量场承接 + 合规)"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 监管红线现状核查 (推导自心智模型 1.5)
  9.2 千川产品形态时效核查 (推导自心智模型 1.6)
  9.3 承接能力诊断 (推导自心智模型 1.2)
  9.4 货盘 / 供应链体检 (推导自心智模型 1.3)
  9.5 阶段定位 + 流量结构诊断 (推导自心智模型 1.1)
  9.6 数据来源可信度甄别 (推导自心智模型「真数据 vs 估算数据」，C6 —— 元维度)
  9.7 流派语境定位 (推导自心智模型 1.4 + 五大流派分歧)

背后的心智模型:
  • 算法生意：直播间是做给算法看的，不是做给用户看的: 抖音直播带货的本质是「向推荐算法证明这个直播间值得被推流」——理解算法如何用停留 / 转化 / GPM 这组指标分配免费流量，比话术技巧更底层；流量是非线性「大爆发」的，核心变量是流量 × 选品。
  • 承接 > 引流：流量是放大器不是发动机: 直播间能不能做起来，发动机是「承接能力」(UV 价值 / 停留时长 / GPM / 品组 / 话术)，流量 (自然 + 投流) 只是把这台发动机的输出放大——承接是负数时，加流量等于加速亏钱。
  • 货是天花板：选品决定上限，人和场只能在上限内优化: 人货场三要素里「货 (选品)」是天花板——选品错了，再强的主播和再精细的场也救不回来；MCN / 操盘手的真本事在「组货 / 供应链」，不在「话术」。

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "监管红线现状核查 (推导自心智模型 1.5)"
  "千川产品形态时效核查 (推导自心智模型 1.6)"
  "承接能力诊断 (推导自心智模型 1.2)"
  "货盘 / 供应链体检 (推导自心智模型 1.3)"
  "阶段定位 + 流量结构诊断 (推导自心智模型 1.1)"
  "数据来源可信度甄别 (推导自心智模型「真数据 vs 估算数据」，C6 —— 元维度)"
  "流派语境定位 (推导自心智模型 1.4 + 五大流派分歧)"
)
declare -a DIM_QUESTIONS=(
  "当前绝对化用语执法口径、退货率红线、AI 数字人显著标识要求、资质 / 信息公示义务、主播法律身份四分法 (代言人 / 发布者 / 经营者 / 导购)、《直播电商监督管理办法》(117 号令) 实施细则与首批典型执法案例。"
  "当前是标准推广还是全域推广 (哪些场景标准推广还残存)、千川·乘方 (千策 / 千意 / 千寻) 铺开程度与计费 (技术服务费率)、商品全域推广的体裁覆盖。"
  "直播间平均停留时长、进场留存率、UV 价值、GPM、品组结构 (引流 / 福利 / 主推 / 利润 / 形象款配比)、话术六板块完整度——先于一切引流 / 投放问题。"
  "选品与账号实时标签 / 历史成交人群的匹配度、利润空间、退换货逻辑 (品类退货率，如服饰 40-60%)、供应链能否扛放大期的量级和发货时效。"
  "商家 / 案例在 0→1 / 1→10 / 10→100 哪个阶段 (对应该追什么指标)、自然流 / 短视频 / 付费三条腿的配比是否健康、是否只靠直播推荐单一来源。"
  "手上每个数字是「真数据」还是「估算数据」——真数据 = 罗盘 / 巨量百应 (仅本人可见)；估算 = 蝉妈妈 / 飞瓜 / 新抖 (偏差 10-30%)；以及是否为「平台官方报喜口径」(不可 cross-check)。"
  "用户 / 案例属于哪一派——投放 / 运营工程派、知识 / 内容信任派、去 IP 化机构派、超头 IP / 明星派、选品派、私域沉淀派、平台官方派；以及他引用的方法论是「官方明线」还是「实战暗线」。"
)
declare -a DIM_SOURCES=(
  "网信办 (cac.gov.cn) + 市场监管总局官网监管原文；抖音电商学习中心「规则中心」(school.jinritemai.com)；地方市监局合规指引 (如《北京市直播带货合规指引》)。"
  "千川官网 (qianchuan.jinritemai.com) + 巨量学 (school.oceanengine.com)；亿邦动力 / IT 之家 / 36 氪对千川大会的报道；千川大会官方发布信息。"
  "抖音电商罗盘 (compass.jinritemai.com，真数据，四大核心指标：人气 / 互动 / 商品 / 订单)；巨量百应 (达人合作真数据)；不用蝉妈妈 / 飞瓜 (估算)。"
  "巨量算数 (trendinsight.oceanengine.com，行业趋势 / 垂类热度，定方向) → 蝉妈妈 / 飞瓜 (查具体商品 / 竞品 / 达人，标注是估算) → 巨量百应 (自己商品被带的真数据)。"
  "抖音电商罗盘的流量来源构成 + 阶段数据 (月销量级)；抖音电商学习中心「商家成长路径」课程对阶段的官方分层。"
  "核对数字出处——决策 / 合规 / 达人结算只认罗盘 / 巨量百应；竞品对标用蝉妈妈 / 飞瓜但标估算；平台大会数据标官方口径。"
  "用户的表述 register (黑话密度 / 是否讲「算法博弈、投流脏活」) + 引用的代表人物 / 框架 (FACT / 兴趣电商 = 官方派；千川校准 = 投放派；做号不做人 = 去 IP 化派)。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "1-2 句结构化结论 ——「当前 X 行为的合规状态是 [可做 / 高危 / 已违法]，依据 [法条 / 案例]；2026-02 后新增红线为 [...]。」"
  "1-2 句 ——「截至 [日期]，千川【推商品 / 推直播间】场景当前默认模式是 [...]，标准推广 [已下线 / 残存于 X 场景]，千川·乘方处于 [发布 / 铺开] 阶段、费率 [...]。」"
  "1-2 句 ——「承接发动机是 [正 / 负]：停留 [X 秒 vs 达标线 30 秒]、进场留存 [X% vs 30%]、UV 价值 [...]；漏在 [品组 / 话术 / 节奏] 环节。结论：[先修承接 / 可以加流量]。」"
  "1-2 句 ——「货的天花板是 [高 / 低]：选品与账号标签 [匹配 / 错配]、利润空间 [...]、供应链扛量能力 [能 / 不能扛月销翻 10 倍]。结论：[换品 / 货可以、问题在别处]。」"
  "1-2 句 ——「当前在 [0→1 / 1→10 / 10→100] 阶段，本阶段单一重点是 [标签精准 / 拉升 / 全域放大]；流量结构 [三条腿健康 / 单一来源风险]，缺 [短视频 / 付费] 这条腿。」"
  "1-2 句 ——「本结论引用的数据是 [真数据 / 估算 (偏差 10-30%) / 平台官方口径]，来源 [...]；用于 [决策 / 结算 / 合规] 的部分 [是否] 满足『必须用真数据』要求。」"
  "1-2 句 ——「用户语境属 [X 派]，对应方法论侧重 [...]；该派与 [Y 派] 在 [分歧点] 上立场相反，回答应 [按 X 派方法论 / 同时呈现分歧、不抹平]。」"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
