#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 跨境电商运营.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="跨境电商运营"
DIM_COUNT=5

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (5 个):
  9.1 选品机会 + 类目竞争结构
  9.2 合规可行性 (重点欧美)
  9.3 关键词 / Listing 数据
  9.4 投流 ROI 评估
  9.5 财务可行性 (Cash Flow + Payback)

背后的心智模型:
  • 合规优先于流量: 在欧美主流站点, 新品类上线前先解决「能不能合规开卖」, 再考虑「能不能跑出量」。
  • 选品决定 90% 命运: 在亚马逊体系里, 一个品的最终成败 90% 在选品阶段已经决定, 后续运营只能放大这 10% 空间。
  • 品牌长期资产 vs 平台流量租赁 (industry-amplified): 在亚马逊只是租流量, 自有品牌 + 独立站 / 私域才是真资产. 不要在别人的平台上盖楼。

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "选品机会 + 类目竞争结构"
  "合规可行性 (重点欧美)"
  "关键词 / Listing 数据"
  "投流 ROI 评估"
  "财务可行性 (Cash Flow + Payback)"
)
declare -a DIM_QUESTIONS=(
  "类目天花板 (Top 100 月销总和) + 头部集中度 + 供应链门槛 + 季节性"
  "目标站点 + 品类是否需要 VAT / OSS / VerpackG / WEEE / 电池法 / CE / GS / GPSR / EPR"
  "目标关键词搜索量 + 转化率 + 头部对手 listing 关键词矩阵 + SQP 真实搜索词"
  "类目平均 ACOS / TACOS / CTR / CVR + 自家 listing 成本结构"
  "Cash Conversion Cycle + 库存周转 + payback period + LTV / CAC + 毛利率"
)
declare -a DIM_SOURCES=(
  "Helium 10 Black Box / Jungle Scout Opportunity Finder / Brand Analytics SQP / Keepa 历史曲线"
  "各国法规一手 (EUR-Lex / gov.uk / bundestag.de) + Avalara / Avask / hellotax 等服务商白皮书 + 跨境眼合规专题"
  "Brand Analytics SQP (Brand Registry 后) + Helium 10 Cerebro 反查 + Jungle Scout Keyword Scout"
  "Brand Analytics + Pacvue / Sellerise / Helium 10 Adtomic + 行业 benchmark (蝉妈妈 / Pacvue 报告)"
  "SellerBoard / FeedbackWhiz / 自家 BI + ERP 报表"
)
declare -a DIM_OUTPUT_FORMATS=(
  "类目机会 score (1-10) + 1 句关键瓶颈 + 推荐细分"
  "low / medium / high 合规风险等级 + 必做清单 + 估算成本 / 时间"
  "关键词金字塔 (高 / 中 / 长尾) + Listing 优化方向"
  "预期 ACOS 区间 + 是否值得投 + 1 句获利节奏判断"
  "财务健康度 (1-10) + payback 周期 + 资金周转风险点"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
