#!/usr/bin/env bash
# voice.sh — Voice 决策助手 for 公众号写作助手 (微信公众号文章 全链路 — 选题 / 标题 / 开篇 / 结构 / 行文 / 排版 / 配图 / 推送 / 涨粉 / 留言 / 二次传播 / 变现, 单 artifact = 一篇公众号推文).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="公众号写作助手 (微信公众号文章 全链路 — 选题 / 标题 / 开篇 / 结构 / 行文 / 排版 / 配图 / 推送 / 涨粉 / 留言 / 二次传播 / 变现, 单 artifact = 一篇公众号推文)"
TOPIC="Voice"

usage() {
  cat <<EOF
voice.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 1 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./voice.sh             # interactive
  ./voice.sh --dry-run   # walk through but no file
  ./voice.sh --json      # JSON to stdout
  ./voice.sh --explain   # show backing playbook rules + mental models
  ./voice.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 Voice 主题下的 playbook 规则组合成交互树。

基于 1 条规则:
  • 如果 矩阵号同质化 > 70% → 则 (跨号选题 / 标题 / 结构 / voice 相似度), 则 整改; 否则微信算法识别为关联号同步降权, 2023 自

相关心智模型:
  • 「单篇是产品, 账号是公司」 (Account-as-Product): 单篇推文是 product release, 账号是 company; 不为单篇 metric 牺牲账号长期资产 (定位 / voice / 读者画像).
  • 「头部效应是结构性事实, 不是个人努力问题」 (Power-Law Reality): 90% 公众号永远做不到全职收入, 不是「再努力就能突破」, 是流量 / 注意力 / 算法权重的结构性分布; 商业化必须基于此事实设计对冲 (多平台 / 多变现路径), 不卖速成幻想.

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "矩阵号同质化 > 70%"
)
declare -a RULE_ACTIONS=(
  "(跨号选题 / 标题 / 结构 / voice 相似度), 则 整改; 否则微信算法识别为关联号同步降权, 2023 自媒体 13 条 + 2025 不实信息专项明确点名"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "voice-decision"
fi
