#!/usr/bin/env bash
# workflow-1.sh — 跑一场完整直播（场前选品 → 场前预热 → 场中节奏 → 场后复盘） SOP walkthrough for 抖音直播带货 (商家 / 主播 / 直播间运营 + 千川 / 巨量引擎广告投放 + 选品 + 流量场承接 + 合规).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="抖音直播带货 (商家 / 主播 / 直播间运营 + 千川 / 巨量引擎广告投放 + 选品 + 流量场承接 + 合规)"
WORKFLOW="跑一场完整直播（场前选品 → 场前预热 → 场中节奏 → 场后复盘）"

usage() {
  cat <<EOF
workflow-1.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-1.sh             # interactive
  ./workflow-1.sh --dry-run
  ./workflow-1.sh --json
  ./workflow-1.sh --explain
  ./workflow-1.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "跑一场完整直播（场前选品 → 场前预热 → 场中节奏 → 场后复盘）" 工作流。

一句话: 从「决定开一场带货直播」到「这场播完且复盘出下一场优化清单」的完整闭环 —— 这一行最高频、最核心的单位工作流。

入门 SOP 共 6 步, 失败模式自检 5 项。

相关心智模型:
  • 算法生意：直播间是做给算法看的，不是做给用户看的: 抖音直播带货的本质是「向推荐算法证明这个直播间值得被推流」——理解算法如何用停留 / 转化 / GPM 这组指标分配免费流量，比话术技巧更底层；流量是非线性「大爆发」的，核心变量是流量 × 选品。
  • 承接 > 引流：流量是放大器不是发动机: 直播间能不能做起来，发动机是「承接能力」(UV 价值 / 停留时长 / GPM / 品组 / 话术)，流量 (自然 + 投流) 只是把这台发动机的输出放大——承接是负数时，加流量等于加速亏钱。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**场前选品 + 排品（提前 3-7 天）**: 操盘手按账号标签定选品方向，把货分成「五类款」—— 引流款/福利款（低价拉人留人）、主推款/爆款（人气峰值时主卖）、利润款（赚钱）、对比款（衬托主推款）、形象款（拉调性）；按「127 原则」(福利+主推 : 利润 : 对比+形象 = 1:2:7) 排出上架顺序，注意品之间有关联性、价格梯度不跳。**跳过会发生什么**：没引流款拉不起实时数据，全是利润款直播间起不来；选品与账号标签不符则流量进来不转化（UV 价值低）。 evidence: [T03-S001, T03-S002]"
  "**写脚本 + 定岗位分工（提前 1-3 天）**: 写整场脚本框架（主题/日期/时长/目标 + 前中后每个岗位做什么动作配什么福利）；话术按六板块准备（活动/互动/讲款/打单/逼单/气氛话术）；明确主播（讲款+互动）、中控（后台上下架/改价/库存/发福袋/递话）、场控（节奏把控：何时过款/憋单/拉互动）分工。**跳过会发生什么**：没脚本则节奏全靠主播即兴，数据节奏散；岗位不分则中控/场控/主播互相抢动作，后台操作出错（上错链接、改错价）。 evidence: [T03-S001, T03-S002]"
  "**场前预热（开播前 3 小时～提前 3-5 天）**: 提前 3-5 天发短视频作品（主打卖点/颜值/性价比）为直播间导初始精准流量；开播前 3 小时发带直播预告+福利的预热短视频。**跳过会发生什么**：开播时无初始流量，冷启动期数据更难看，算法没数据可判断；据二手测算预热视频可提升约 40% 初始流量。 evidence: [T03-S001, T03-S002]"
  "**场中执行 — 开场暖场（开播 0-10 分钟）**: 主播自我介绍 + 告知直播时间和福利预告 + 用利益点直给（「今天专属价仅 50 单」）和互动引导（「扣 1 抽免单」）快速建立观看理由、留住人。**跳过会发生什么**：开场留不住人，停留时长不达标（冷启动期第一权重指标，目标人均≥2 分钟），算法判定内容差不再推流。 evidence: [T03-S001, T03-S002]"
  "**场中执行 — 过款 + 憋单 + 节奏循环**: 按排品过款（单品讲解固定流程：卖点引出/手拿介绍/用户评价/促单，约 2+3+3+3 分钟），用憋单（低价钩子留人不上库存）蓄水实时数据，人气峰值时放主推款，每 15 分钟设福利节点（福袋/秒杀）防流失；场控盯实时数据调节奏。**跳过会发生什么**：没节奏设计则在线人数曲线平直、无法在峰值收割；不设福利节点观众流失快。 evidence: [T03-S001, T03-S002]"
  "**场后复盘（播后当天/次日）**: 四象限复盘 —— 流量数据（场观/峰值环比）、互动数据（停留率/点赞率/加粉率）、交易数据（GMV/客单价/转化率/UV 价值）、现场反馈（人员分工/技术问题）；梳理爆品与滞销品，定位异常时段，产出下一场优化项。**跳过会发生什么**：不复盘则同样的选品/话术/节奏错误每场重犯，直播间无法迭代。 evidence: [T03-S001, T03-S005]"
)
declare -a FAILURE_MODES=(
  "**只盯直播推荐流量、忽视短视频端培育**: 触发原因 —— 新手以为直播间流量只来自直播广场。后果 —— 流量结构单一、抗风险弱、起不来（数英稿称「99% 失败模式」之一）。怎么避免：**场前预热必须发短视频导流，把短视频端当与直播同等重要的流量入口，不要只在直播开始后才想流量**。 evidence: [T03-S001]"
  "**选品与账号标签不符**: 触发原因 —— 跟风大主播选品、不看自己账号的用户画像。后果 —— 流量进来不转化，UV 价值低，加投流等于加速亏钱。怎么避免：**选品前先拉账号实时标签和历史成交人群，按自己的用户画像选品，不要因为某品在别人直播间卖爆就上**。 evidence: [T03-S001, T03-S002]"
  "**憋单时间过长 / 承诺福利不兑现**: 触发原因 —— 为冲实时数据过度憋单。后果 —— 引发投诉和限流，且 2026 新规下虚假承诺有合规风险。怎么避免：**憋单设明确时间上限，承诺的福利款一定按量兑现，把「真实节奏控制」和「虚假紧缺欺骗」分清**。 evidence: [T03-S001, T03-S011]"
  "**场后不复盘 / 复盘只看 GMV 总量**: 触发原因 —— 嫌复盘麻烦，或只关心卖了多少钱。后果 —— 靠投流堆出的高 GMV 可能 GPM/UV 价值很低、不可持续，同样的错误每场重犯。怎么避免：**每场必复盘四象限，重点看 GPM/UV 价值/停留时长这组「算法评分代理」指标，而非只看 GMV**。 evidence: [T03-S001, T03-S005]"
  "**CLI 化暗示 (v0.6+)**: 上述每个 failure 写法已 actionable，可直接抽进 \`cli/workflow/run-one-live.sh\` 的失败模式自检环节，每条变成 yes/no 检查项（如「你这场的场前预热短视频发了吗？」「你的选品是按自己账号标签选的还是跟风选的？」「这场复盘你看了 GPM 和 UV 价值吗？」）。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-1-walkthrough"
fi
