#!/usr/bin/env bash
# workflow-2.sh — 千川直播间冷启动投放 SOP walkthrough for 抖音直播带货 (商家 / 主播 / 直播间运营 + 千川 / 巨量引擎广告投放 + 选品 + 流量场承接 + 合规).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="抖音直播带货 (商家 / 主播 / 直播间运营 + 千川 / 巨量引擎广告投放 + 选品 + 流量场承接 + 合规)"
WORKFLOW="千川直播间冷启动投放"

usage() {
  cat <<EOF
workflow-2.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-2.sh             # interactive
  ./workflow-2.sh --dry-run
  ./workflow-2.sh --json
  ./workflow-2.sh --explain
  ./workflow-2.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "千川直播间冷启动投放" 工作流。

一句话: 从「新账号/新计划没有付费数据」到「跑出一个过了学习期、ROI 达标、人群标签精准的千川计划组」的投放工作流 —— 投放派的核心日常，也是行业最高频痛点。

入门 SOP 共 5 步, 失败模式自检 5 项。

相关心智模型:
  • 算法生意：直播间是做给算法看的，不是做给用户看的: 抖音直播带货的本质是「向推荐算法证明这个直播间值得被推流」——理解算法如何用停留 / 转化 / GPM 这组指标分配免费流量，比话术技巧更底层；流量是非线性「大爆发」的，核心变量是流量 × 选品。
  • 承接 > 引流：流量是放大器不是发动机: 直播间能不能做起来，发动机是「承接能力」(UV 价值 / 停留时长 / GPM / 品组 / 话术)，流量 (自然 + 投流) 只是把这台发动机的输出放大——承接是负数时，加流量等于加速亏钱。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**确认前端「人货场」最优**: 投放前先保证直播间承接没问题（平均停留≥30 秒、进场留存≥30% 是流量承载力达标线）。**跳过会发生什么**：承接不行就投千川 = 加速亏钱，钱花了流量留不住。 evidence: [T03-S007]"
  "**选投放工具 + 定预算**: 冷启动期可用「小店随心推 + 相似达人定向」轻量起步，单场预算 300-500 元；或用千川标准推广。聚焦「进入直播间」「商品点击」等浅层目标。**跳过会发生什么**：一上来就投深层成交目标，模型没数据可学，跑不动。 evidence: [T03-S007]"
  "**搭计划 + 定向「先窄后宽」**: 定向先窄（精准人群优先跑出模型），跑稳后再放宽找增量。**跳过会发生什么**：一开始就宽定向，人群泛、标签校不准、ROI 难看。 evidence: [T03-S007]"
  "**跑量过学习期**: 让计划快速消耗预算跑出第一波转化数据，积累约 20-50 个转化前模型不稳定，期间**忌频繁改计划/调价**。**跳过会发生什么**：频繁改计划导致模型一直「学不会」，永远过不了学习期。 evidence: [T03-S007]"
  "**盯数据 + 优化 ROI**: 对有潜力的计划优化 ROI，衰减的素材及时换（素材投一两天后成本快速上升）。**跳过会发生什么**：不换衰减素材则成本越跑越高、ROI 持续下滑。 evidence: [T03-S007]"
)
declare -a FAILURE_MODES=(
  "**承接不行就投千川**: 触发原因 —— 以为投流能解决一切。后果 —— 钱花了流量留不住，加速亏损。怎么避免：**投千川前先确认直播间停留≥30 秒、进场留存≥30%，承接不达标先修承接再投流**。 evidence: [T03-S007]"
  "**学习期频繁改计划**: 触发原因 —— 看到数据难看忍不住调。后果 —— 模型一直学不会，永远过不了学习期，预算白烧。怎么避免：**学习期（积累约 20-50 个转化前）锁死计划不动，给算法学习时间**。 evidence: [T03-S007]"
  "**追求 ROI 越高越好**: 触发原因 —— 直觉觉得 ROI 高是好事。后果 —— ROI 高意味着不敢花钱、跑不出量，规模做不大。怎么避免：**目标 ROI 设为「保本 ROI×1.2」左右、能放量即可，不要把 ROI 拉到不敢投钱的程度**。 evidence: [T03-S007]"
  "**不换衰减素材**: 触发原因 —— 没有素材更换节奏。后果 —— 素材衰减后成本飙升、ROI 持续下滑。怎么避免：**按 3+3+3 节奏管理素材，CTR 跌破 3% 就淘汰**。 evidence: [T03-S007]"
  "**CLI 化暗示 (v0.6+)**: 可抽进 \`cli/workflow/qianchuan-coldstart.sh\`，每条变 yes/no（如「你的直播间停留时长到 30 秒了吗？没到先别投千川」「这个计划还在学习期吗？在的话不要改」）。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-2-walkthrough"
fi
