#!/usr/bin/env bash
# workflow-3.sh — 直播复盘与下一场优化 SOP walkthrough for 抖音直播带货 (商家 / 主播 / 直播间运营 + 千川 / 巨量引擎广告投放 + 选品 + 流量场承接 + 合规).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="抖音直播带货 (商家 / 主播 / 直播间运营 + 千川 / 巨量引擎广告投放 + 选品 + 流量场承接 + 合规)"
WORKFLOW="直播复盘与下一场优化"

usage() {
  cat <<EOF
workflow-3.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-3.sh             # interactive
  ./workflow-3.sh --dry-run
  ./workflow-3.sh --json
  ./workflow-3.sh --explain
  ./workflow-3.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "直播复盘与下一场优化" 工作流。

一句话: 从「一场直播刚结束」到「产出一份带异常值归因 + 下一场可执行优化项的复盘报告」的闭环工作流 —— 是 workflow 1 的 step 6 的独立展开，因为它是「直播间能不能迭代」的关键，单列。

入门 SOP 共 5 步, 失败模式自检 4 项。

相关心智模型:
  • 算法生意：直播间是做给算法看的，不是做给用户看的: 抖音直播带货的本质是「向推荐算法证明这个直播间值得被推流」——理解算法如何用停留 / 转化 / GPM 这组指标分配免费流量，比话术技巧更底层；流量是非线性「大爆发」的，核心变量是流量 × 选品。
  • 承接 > 引流：流量是放大器不是发动机: 直播间能不能做起来，发动机是「承接能力」(UV 价值 / 停留时长 / GPM / 品组 / 话术)，流量 (自然 + 投流) 只是把这台发动机的输出放大——承接是负数时，加流量等于加速亏钱。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**整体回顾关键数据**: 从人气维度（总场观/平均在线/停留时长/新增粉丝/互动率）和销售维度（销售额/转化率/UV 价值）拉数据。**跳过会发生什么**：不看数据则复盘变成「凭感觉」，无法定位真问题。 evidence: [T03-S005]"
  "**时段对比精细复盘**: 找直播过程中的异常值（某时段在线/转化突然掉或涨），对应到当时的直播流程动作；用 AB 测试（如福袋投放时机）找最佳路径。**跳过会发生什么**：只看整体均值，不知道问题出在哪个环节。 evidence: [T03-S005]"
  "**商品复盘优化选品**: 对比爆品和滞销品的销讲次数/时段/话术，判断选品是否符合用户标签。**跳过会发生什么**：滞销品下次还排进去，爆品没给够讲解时长。 evidence: [T03-S005]"
  "**用户分析匹配标签**: 检验引入的流量是不是目标用户，分析购买和价格偏好。**跳过会发生什么**：流量不精准的根因找不到，继续投错人。 evidence: [T03-S005]"
  "**流量分析优化渠道**: 区分自然流量（搜索/推荐/关注）和付费流量，分析引流视频为什么有效、复制或优化。**跳过会发生什么**：不知道哪个流量渠道有效，预算乱分配。 evidence: [T03-S005]"
)
declare -a FAILURE_MODES=(
  "**复盘只看 GMV 总量**: 触发原因 —— 只关心卖了多少钱。后果 —— 看不出 GPM/UV 价值低的不可持续问题。怎么避免：**复盘必看 GPM/UV 价值/停留时长这组「算法评分代理」指标**。 evidence: [T03-S005]（+ Track 04 seed）"
  "**复盘不落到具体流程环节**: 触发原因 —— 只看整体均值。后果 —— 知道「这场不行」但不知道哪步不行，下场重犯。怎么避免：**用时段异常值对应到当时的直播动作，定位到具体环节再优化**。 evidence: [T03-S005]"
  "**复盘和 SOP 两张皮**: 触发原因 —— 复盘完不更新 SOP。后果 —— 同样的错误每场重犯，复盘白做。怎么避免：**每次复盘结论必须迭代回直播脚本/排品 SOP，形成闭环**。 evidence: [T03-S005]"
  "**CLI 化暗示 (v0.6+)**: 可抽进 \`cli/workflow/post-live-review.sh\`（如「这场复盘你看了 GPM 吗？」「你定位到具体是哪个时段/动作出问题了吗？」「复盘结论写回 SOP 了吗？」）。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-3-walkthrough"
fi
