#!/usr/bin/env bash
# topic-2.sh — —— 决策助手 for 微信私域运营 (企微 + 个人号 + 公众号 + 视频号 + 小程序 + 朋友圈 + 社群 全链路 — 引流 / 沉淀 / 触达 / 转化 / 复购 / 裂变).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="微信私域运营 (企微 + 个人号 + 公众号 + 视频号 + 小程序 + 朋友圈 + 社群 全链路 — 引流 / 沉淀 / 触达 / 转化 / 复购 / 裂变)"
TOPIC="——"

usage() {
  cat <<EOF
topic-2.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 3 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-2.sh             # interactive
  ./topic-2.sh --dry-run   # walk through but no file
  ./topic-2.sh --json      # JSON to stdout
  ./topic-2.sh --explain   # show backing playbook rules + mental models
  ./topic-2.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 —— 主题下的 playbook 规则组合成交互树。

基于 3 条规则:
  • 如果 加了很多好友 / 建了很多群但没产出 → 则 先判断「有没有运营动作（SOP / 内容 / 人）」，无动作的池是死水——先补 SOP 和团队再谈规模，不是反过来先买工
  • 如果 要用一个现成的裂变 / 自动化 / 引流玩法 → 则 先核对微信当前「诱导分享 / 诱导关注 / 外挂」红线，3-6 个月前的玩法默认作废重验——做裂变第一步是合规审查，不是
  • 如果 要选企微 SCRM 或电商 SaaS → 则 同质工具只装一个、别花两周做选型对比——6 家头部企微 SCRM 90% 基础能力相同，微盟 / 有赞功能高度重叠（「重

相关心智模型:
  • 公私二分 / 流量自主权（mental model）: 私域人看一切流量的底层镜片是「这部分流量是租来的还是自己的」——租来的（公域）用一次付一次、平台控分发，自己的（私域）可反复免费触达；近年这对二分从「对立」演化为「全域协同」，但「自主权」这条轴没变。
  • 流量池 / 蓄水养鱼（mental model）: 私域人把流量当成「要蓄进池子、反复经营」的对象而非「这次能转化多少」的一次性曝光——但「建了群 / 加了好友」只是蓄了水，**没有运营动作的池是死水**；价值在「蓄水—养鱼—捕鱼」的循环，不在池子大小

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "加了很多好友 / 建了很多群但没产出"
  "要用一个现成的裂变 / 自动化 / 引流玩法"
  "要选企微 SCRM 或电商 SaaS"
)
declare -a RULE_ACTIONS=(
  "先判断「有没有运营动作（SOP / 内容 / 人）」，无动作的池是死水——先补 SOP 和团队再谈规模，不是反过来先买工具"
  "先核对微信当前「诱导分享 / 诱导关注 / 外挂」红线，3-6 个月前的玩法默认作废重验——做裂变第一步是合规审查，不是设计海报"
  "同质工具只装一个、别花两周做选型对比——6 家头部企微 SCRM 90% 基础能力相同，微盟 / 有赞功能高度重叠（「重技术 vs 重营销」是定位差异不是互补）；选型纠结的边际收益很低，那两周拿去搭 SOP 更值"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-2-decision"
fi
