#!/usr/bin/env bash
# topic-1.sh — 私域 决策助手 for 微信私域运营 (企微 + 个人号 + 公众号 + 视频号 + 小程序 + 朋友圈 + 社群 全链路 — 引流 / 沉淀 / 触达 / 转化 / 复购 / 裂变).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="微信私域运营 (企微 + 个人号 + 公众号 + 视频号 + 小程序 + 朋友圈 + 社群 全链路 — 引流 / 沉淀 / 触达 / 转化 / 复购 / 裂变)"
TOPIC="私域"

usage() {
  cat <<EOF
topic-1.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 7 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-1.sh             # interactive
  ./topic-1.sh --dry-run   # walk through but no file
  ./topic-1.sh --json      # JSON to stdout
  ./topic-1.sh --explain   # show backing playbook rules + mental models
  ./topic-1.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 私域 主题下的 playbook 规则组合成交互树。

基于 7 条规则:
  • 如果 流量越来越贵 / 投放 ROI 持续下滑 → 则 先问「这部分流量能不能沉淀成可反复免费触达的私域」，而不是继续加投放预算——把「买一次用一次」换成「买一次反复用」是私域
  • 如果 私域转化率低 / 用户反感 / 被屏蔽删好友 → 则 先查「是不是全员一套话术」，按标签 + 生命周期分层是精细化的第一刀；且标签体系要反推自「我要做哪些差异化动作」——没有
  • 如果 要选私域承接的主战场 / 现有个人号矩阵要不要迁 → 则 默认企业微信为主战场、个人号为辅助——2024 起已成定局；任何「个人号无脑加好友 / 多开矩阵」式建议直接判过时（撞封
  • 如果 私域 ROI 不行 → 则 不要笼统归因，按「引流 → 沉淀 → 触达 → 转化 → 复购 → 裂变」逐环看转化率，定位漏损最大的一环——尤其先查「
  • 如果 要判断「私域值不值得做」 → 则 用 LTV / 复购视角而非首单 ROI 评判（私域经济模型是「首购可能亏、复购才赚」），且先过品类适配性 + 三个前置
  • 如果 面对「要不要一次性把全套做全 / 做大 / 做完美」 → 则 默认先用最小版本验证跑通再放大——0→1 阶段先用「企微 1v1 + 朋友圈」两件套验证品类和话术，跑通了再加触点 / 
  • 如果 选私域工具 → 则 先过合规门槛（合规资质齐全 + 会话存档能力）再看别的，不看低价、不看功能数量——没有齐全合规资质的产品再便宜也是监管风

相关心智模型:
  • 公私二分 / 流量自主权（mental model）: 私域人看一切流量的底层镜片是「这部分流量是租来的还是自己的」——租来的（公域）用一次付一次、平台控分发，自己的（私域）可反复免费触达；近年这对二分从「对立」演化为「全域协同」，但「自主权」这条轴没变。
  • 流量池 / 蓄水养鱼（mental model）: 私域人把流量当成「要蓄进池子、反复经营」的对象而非「这次能转化多少」的一次性曝光——但「建了群 / 加了好友」只是蓄了水，**没有运营动作的池是死水**；价值在「蓄水—养鱼—捕鱼」的循环，不在池子大小

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "流量越来越贵 / 投放 ROI 持续下滑"
  "私域转化率低 / 用户反感 / 被屏蔽删好友"
  "要选私域承接的主战场 / 现有个人号矩阵要不要迁"
  "私域 ROI 不行"
  "要判断「私域值不值得做」"
  "面对「要不要一次性把全套做全 / 做大 / 做完美」"
  "选私域工具"
)
declare -a RULE_ACTIONS=(
  "先问「这部分流量能不能沉淀成可反复免费触达的私域」，而不是继续加投放预算——把「买一次用一次」换成「买一次反复用」是私域存在的理由"
  "先查「是不是全员一套话术」，按标签 + 生命周期分层是精细化的第一刀；且标签体系要反推自「我要做哪些差异化动作」——没有触达策略对应的标签是死标签"
  "默认企业微信为主战场、个人号为辅助——2024 起已成定局；任何「个人号无脑加好友 / 多开矩阵」式建议直接判过时（撞封号红线、客户不可继承）"
  "不要笼统归因，按「引流 → 沉淀 → 触达 → 转化 → 复购 → 裂变」逐环看转化率，定位漏损最大的一环——尤其先查「承接」（引流和承接是两段，引来 1000 个、加好友通过率 30%、破冰留存 50%，实际只剩 150，承接漏损往往比引流本身更致命）"
  "用 LTV / 复购视角而非首单 ROI 评判（私域经济模型是「首购可能亏、复购才赚」），且先过品类适配性 + 三个前置条件——品类高复购 / 高客单 / 决策链长才适合；稳定公域流量来源、能持续产内容的人、客单价能覆盖私域人力成本，三者缺一就先补前置条件、不硬启动"
  "默认先用最小版本验证跑通再放大——0→1 阶段先用「企微 1v1 + 朋友圈」两件套验证品类和话术，跑通了再加触点 / 加渠道 / 加标签维度 / 做归因体系。私域最大的死法不是做得不够，是摊子铺太大、每个都半成品"
  "先过合规门槛（合规资质齐全 + 会话存档能力）再看别的，不看低价、不看功能数量——没有齐全合规资质的产品再便宜也是监管风险；反向信号：对续费率自信的厂商不会自降身价推「多年使用权 + 打折」，看到这种促销要警惕"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-1-decision"
fi
