#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 内容创作者经济(Substack / Beehiiv / 公众号 / 知识星球 / 小报童 / Patreon — newsletter 写作 + 订阅制变现 + 受众沉淀 + 个人 IP).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="内容创作者经济(Substack / Beehiiv / 公众号 / 知识星球 / 小报童 / Patreon — newsletter 写作 + 订阅制变现 + 受众沉淀 + 个人 IP)"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 变现流派定位(推导自心智模型 1.3 + playbook 6)
  9.2 平台依赖与所有权审计(推导自心智模型 1.1)
  9.3 收入数据可信度核查(推导自心智模型 1.5)
  9.4 niche 锐度评估(推导自心智模型 1.4)
  9.5 平台规则与算法时效追踪(推导自心智模型 1.1 + 时效信号)
  9.6 增长杠杆逆向工程(推导自心智模型 1.6)
  9.7 locale 与监管语境判定(推导自智识谱系 §7.3)

背后的心智模型:
  • 平台是聚合者,创作者是租户 — 资产要握在自己手里: newsletter / 创作者经济里,平台(Substack / 公众号)靠控制需求与分发赢,创作者在平台上是租户;真正的资产是「能带走的 email 列表 + 自有域名(海外)/ 私域回流(国内)
  • 「先免费建信任、再变现」的耐心模型: 这一行的资深人默认「受众信任 / 受众深度」是前置资产,变现是它的函数 — 顺序不能反:先把价值无偿给出去、把漏斗顶部做够宽,再谈收费 / 接广告 / 卖课。
  • newsletter 是入口 / 漏斗,不是终点 — 真生意是「媒体公司」或下游: 把「做 newsletter」理解为一门生意(产品 + 分发 + 变现 + 下游),而非「写作」;newsletter 本体往往是飞轮的入口,真正的收入结构在订阅 + 赞助 + 社区 + podcas

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "变现流派定位(推导自心智模型 1.3 + playbook 6)"
  "平台依赖与所有权审计(推导自心智模型 1.1)"
  "收入数据可信度核查(推导自心智模型 1.5)"
  "niche 锐度评估(推导自心智模型 1.4)"
  "平台规则与算法时效追踪(推导自心智模型 1.1 + 时效信号)"
  "增长杠杆逆向工程(推导自心智模型 1.6)"
  "locale 与监管语境判定(推导自智识谱系 §7.3)"
)
declare -a DIM_QUESTIONS=(
  "这个创作者 / 这个问题属于或想走四大流派的哪一派(订阅优先 / 广告-赞助 / 课程漏斗 / 个人 IP 多元化);受众结构是窄而专(B2B、公司愿买单)还是宽而泛 —— 受众结构决定可行的变现路径。"
  "这个创作者的「真资产」现在握在谁手里 —— 有没有自有域名、email 列表能不能导出、是不是 all-in 单一平台、有没有跨 ≥2 平台;国内则看有没有私域回流。"
  "遇到的任何收入数字 / 「XX 月入 N 万能不能复制」—— 口径是什么(自报 build-in-public / 第三方拆解 / 平台数据)、分布如何(中位数 vs 头部)、样本是否含失败者。"
  "这个创作者的 niche 能不能用一句话讲清「为谁、解决什么、凭什么是你」,以及是否绑定本人不可替代经验 —— 「科技 / 商业」级别的宽类目不算。"
  "用户所在平台近 3-6 个月的规则 / 算法 / 政策**外部变动** —— Substack Notes/Recommendations 算法权重、内容政策、抽成、邮件认证要求(SPF/DKIM/DMARC)、国内自媒体管理规定。"
  "同 niche 已成功的 3-5 个 newsletter 用了哪几类可拆解的增长杠杆(推荐网络 / 借力他人受众 / content-market fit / 付费获取 / referral program);对方停滞的环节在 niche+分发+销售 70% 里的哪一块。"
  "这个创作者面向中文还是英文 / 全球读者 —— locale 决定整套工具栈、所有权假设、读者付费习惯;若 locale=CN,自动触发监管语境核查(自媒体许可证 / 算法备案 / 营销号清理 / 头部税务稽查)。"
)
declare -a DIM_SOURCES=(
  "对方现有内容的 niche 与读者画像;intake / 对话里「想靠什么赚钱」的表述;对照 §7.1 四派代表(Ben Thompson/Polina = A,Tyler Denk/Packy = B,Justin Welsh = C,罗振宇/万维钢 = D)的路径特征。"
  "对方当前用的平台(Substack/beehiiv/Ghost/公众号);是否有独立域名;平台是否支持 email 导出(查 §3.1 工具卡片 + Track 02);workflow #7 的检查项。"
  "数字的原始出处(本人 Note vs 第三方);对照 intake 警示(中位 newsletter 月入约 \$100、Substack top 0.1% 占订阅收入 50%+ 业内估计);Indie Hackers Income Reports / Growth In Reverse 拆解作交叉。"
  "对方对自己定位的自述;现有内容选题的离散度;对照 workflow #3 入门 SOP 的「一句话定位」标准 + canon Niche 概念。"
  "On Substack 官方 blog、Substack 帮助中心、各平台 changelog;Casey Newton / Platformer 对平台事件的报道;Growth In Reverse / The Newsletter Operator 对算法变动的实操复盘;§8.4 时效清单。"
  "Growth In Reverse 对头部创作者的逆向拆解长文;The Newsletter Operator podcast;同 niche 头部的公开访谈 / 推文 / 邮件存档;workflow #1 资深 add 的「逆向拆解」方法。"
  "对方目标读者语言 / 地域;若 CN,查《关于加强\"自媒体\"管理的通知》及后续、互联网信息服务算法推荐管理规定、近期自媒体税务稽查动态(intake 标「月度需校准」)。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "「该创作者属于流派 {A/B/C/D}(或混合 {X+Y});受众结构 {窄而专 / 宽而泛};因此变现优先级建议 {订阅 / 赞助 / 课程漏斗 / 下游 IP},理由 {1 句}。」"
  "「所有权状态 {健康 / 有风险:具体哪项缺失};若有风险,优先补 {自有域名 / email 导出 / 第二平台 / 私域回流} —— 这是退出门槛,不是『以防万一』。」"
  "「该收入数字口径 = {自报 / 第三方 / 平台};可信度 {打几折};真实分布 {中位数参照};结论:{可参考 / 须大幅打折 / 不可作复制依据},原因 {1 句}。」"
  "「niche 锐度 = {够窄 / 太宽};一句话定位测试 {通过 / 不通过:给出修正方向};是否绑定不可替代经验 {是 / 否}。」"
  "「{平台} 近 3-6 月变动:{1-3 条具体规则/算法变化 + 日期};对该创作者的影响 {增长 / 分发 / 变现哪一环};建议动作 {1 句}。」"
  "「同 niche 头部主用杠杆 = {列 2-4 类};该创作者当前缺失 {哪类杠杆};优先补 {1-2 个},注意 {付费获取须先算获客成本是否撑得住}。」"
  "「locale = {CN / global};适用工具栈 {国内:公众号+小报童+知识星球+得到 / 海外:Substack+beehiiv+Ghost+Kit};若 CN:当前监管风险点 {1-3 条 + 须前置的合规动作}。」"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
