#!/usr/bin/env bash
# deal-sourcing-proprietary-deal-f.sh — Deal sourcing — 建 proprietary deal flow SOP walkthrough for 风险投资人 / 早期投资判断(GP + Principal — Deal sourcing / 尽调 / 估值与 term sheet / 投后服务 / 退出 + LP 关系与 fundraising — 涵盖 US 美元基金 + 国内 RMB / 美元基金).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="风险投资人 / 早期投资判断(GP + Principal — Deal sourcing / 尽调 / 估值与 term sheet / 投后服务 / 退出 + LP 关系与 fundraising — 涵盖 US 美元基金 + 国内 RMB / 美元基金)"
WORKFLOW="Deal sourcing — 建 proprietary deal flow"

usage() {
  cat <<EOF
deal-sourcing-proprietary-deal-f.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./deal-sourcing-proprietary-deal-f.sh             # interactive
  ./deal-sourcing-proprietary-deal-f.sh --dry-run
  ./deal-sourcing-proprietary-deal-f.sh --json
  ./deal-sourcing-proprietary-deal-f.sh --explain
  ./deal-sourcing-proprietary-deal-f.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "Deal sourcing — 建 proprietary deal flow" 工作流。

一句话: 把「被动等 inbound deck」升级成「主动、有结构、有专属性的 deal flow 机器」—— 因为 70%+ 的 top deal 来自既有网络,sourcing 决定一支基金的回报上限。

入门 SOP 共 4 步, 失败模式自检 4 项。

相关心智模型:
  • Power-law 是世界观，不是事后观察到的结果 — 错过比投错致命: VC 的整门生意建立在「一支基金 80%+（业内估计，幂律分布的概数）回报来自 1-2 个 outlier、其余多数 deal 回本或归零」之上；因此判断一个 deal 的第一性问题不是「它稳不稳 /
  • 市场 / 赛道决定论 — 但「市场 vs 团队谁第一」是本行未决的派系张力: 这一行有一条强力镜片——「好团队遇上烂市场，市场赢；烂团队遇上好市场，市场赢」，市场天花板能不能容下一个 return-the-fund 的 outlier 是早期判断的硬约束；但与之并存的是另一极—

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**建多渠道入口**:打通 inbound(让人能找到你 —— 公开邮箱 / Twitter / firm 网站)+ outbound(主动按 thesis 扫公司)+ 引荐网络(其他 GP、portfolio 创始人、accelerator)。"
  "**持续撒网见人**:每周固定见 N 个公司 + N 个「非为投资」的人(其他投资人、潜在 scout、行业人),把网络当资产养。"
  "**初筛 + pattern match**:对进来的 deal 用 thesis / stage / geo 做快速过滤,30 秒-2 分钟判断「值不值得一次 first meeting」。"
  "**录入 + 跟踪 + 复盘**:所有接触过的 deal 录进 CRM(Affinity),标来源渠道;定期复盘「哪个渠道给的 deal 命中率最高」,把资源往高产渠道倾斜。"
)
declare -a FAILURE_MODES=(
  "**只等 inbound、不建 outbound + 引荐**:deal flow 完全被动 —— 「从第一周就主动 outbound 扫 thesis 赛道 + 系统经营引荐网络,别让漏斗顶端受制于人」。"
  "**撒网但无 thesis**:见很多公司但没有「我在哪个赛道比别人强」 —— 「先写清楚 thesis,再把 sourcing 聚焦到 thesis 命中区;大而不专的 deal flow 出不了 proprietary 优势」。"
  "**不跟踪 deal 来源、无法优化**:不知道哪个渠道有效 —— 「每个 deal 录 CRM 时标来源渠道,季度复盘命中率,把资源往高产渠道倾斜」。"
  "**把 AI sourcing 工具当 sourcing 的全部**:迷信工具自动出清单 —— 「AI sourcing 是初筛放大器不是 judgment 替代,且整层 experimental、6 个月后工具可能换一批,别把核心 deal flow 押在单一工具上」。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "deal-sourcing-proprietary-deal-f-walkthrough"
fi
