#!/usr/bin/env bash
# due-diligence-founder-reference-.sh — Due diligence 深做(founder reference call / market sizing / cap table review) SOP walkthrough for 风险投资人 / 早期投资判断(GP + Principal — Deal sourcing / 尽调 / 估值与 term sheet / 投后服务 / 退出 + LP 关系与 fundraising — 涵盖 US 美元基金 + 国内 RMB / 美元基金).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="风险投资人 / 早期投资判断(GP + Principal — Deal sourcing / 尽调 / 估值与 term sheet / 投后服务 / 退出 + LP 关系与 fundraising — 涵盖 US 美元基金 + 国内 RMB / 美元基金)"
WORKFLOW="Due diligence 深做(founder reference call / market sizing / cap table review)"

usage() {
  cat <<EOF
due-diligence-founder-reference-.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./due-diligence-founder-reference-.sh             # interactive
  ./due-diligence-founder-reference-.sh --dry-run
  ./due-diligence-founder-reference-.sh --json
  ./due-diligence-founder-reference-.sh --explain
  ./due-diligence-founder-reference-.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "Due diligence 深做(founder reference call / market sizing / cap table review)" 工作流。

一句话: 把一个「值得投的感觉」拆成可核查的证据 —— 系统化做 founder reference call、market sizing、产品 / 竞争 / unit economics 核查、cap table review,产出能在 IC 上站得住的尽调结论。

入门 SOP 共 5 步, 失败模式自检 4 项。

相关心智模型:
  • Power-law 是世界观，不是事后观察到的结果 — 错过比投错致命: VC 的整门生意建立在「一支基金 80%+（业内估计，幂律分布的概数）回报来自 1-2 个 outlier、其余多数 deal 回本或归零」之上；因此判断一个 deal 的第一性问题不是「它稳不稳 /
  • 市场 / 赛道决定论 — 但「市场 vs 团队谁第一」是本行未决的派系张力: 这一行有一条强力镜片——「好团队遇上烂市场，市场赢；烂团队遇上好市场，市场赢」，市场天花板能不能容下一个 return-the-fund 的 outlier 是早期判断的硬约束；但与之并存的是另一极—

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**Founder / team reference call**:打创始人提供的 reference,问「这个人是否值得跟随、co-founder 之间是否稳、过往怎么处理逆境」。"
  "**Market sizing(TAM 核查)**:独立核算市场规模(自下而上 + 自上而下),验证「这个市场大到能容下一个 return-the-fund 的 outlier 吗」。"
  "**产品 + 竞争核查**:试用产品 / 看 demo,扫竞争格局,判断 differentiation 和 defensibility(护城河 / 网络效应)。"
  "**Traction + unit economics 核查**:看真实使用 / 留存 / 收入数据,算 unit economics(LTV / CAC / 毛利 / 回收期),区分「健康增长」和「烧钱买的增长」。"
  "**Cap table review + 法律**:看 cap table(创始人还剩多少股、期权池、上轮投资人条款),必要时做法律尽调(IP 归属 / 诉讼 / 重大合同)。"
)
declare -a FAILURE_MODES=(
  "**跳过 reference call 或只打 friendly reference**:早期投资是投人却不查人 —— 「每个 deal 强制做 2-3 个 off-list 独立 reference,绕开创始人给的友好名单;co-founder 矛盾和人品问题只能从独立信源查出」。"
  "**被 pitch 叙事带走、不独立核 TAM**:接受创始人给的市场规模数字 —— 「自己自下而上 + 自上而下各算一遍 TAM,验证市场天花板能否容下一个 return-the-fund 的 outlier」。"
  "**种子期死抠 unit economics**:对数据太薄的早期公司做重量化尽调 —— 「种子期把尽调收敛到『人 + 市场天花板 + 一个核心假设』,把重量化留给成长期」。"
  "**平均用力填 checklist、不找致命伤**:每个维度都做但都不深 —— 「先问『这个 deal 最可能怎么死』,把尽调火力集中到那一个假设上深挖」。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "due-diligence-founder-reference--walkthrough"
fi
