#!/usr/bin/env bash
# fund-fundraising-exit-7-10-fund.sh — 一个 fund 从 fundraising 到 exit 的 7-10 年生命周期(三尺度之「一个 fund」) SOP walkthrough for 风险投资人 / 早期投资判断(GP + Principal — Deal sourcing / 尽调 / 估值与 term sheet / 投后服务 / 退出 + LP 关系与 fundraising — 涵盖 US 美元基金 + 国内 RMB / 美元基金).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="风险投资人 / 早期投资判断(GP + Principal — Deal sourcing / 尽调 / 估值与 term sheet / 投后服务 / 退出 + LP 关系与 fundraising — 涵盖 US 美元基金 + 国内 RMB / 美元基金)"
WORKFLOW="一个 fund 从 fundraising 到 exit 的 7-10 年生命周期(三尺度之「一个 fund」)"

usage() {
  cat <<EOF
fund-fundraising-exit-7-10-fund.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./fund-fundraising-exit-7-10-fund.sh             # interactive
  ./fund-fundraising-exit-7-10-fund.sh --dry-run
  ./fund-fundraising-exit-7-10-fund.sh --json
  ./fund-fundraising-exit-7-10-fund.sh --explain
  ./fund-fundraising-exit-7-10-fund.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "一个 fund 从 fundraising 到 exit 的 7-10 年生命周期(三尺度之「一个 fund」)" 工作流。

一句话: 把一支基金从「一份 PPM + 一个 thesis」走完整个 7-10+ 年生命:募资 → 部署期投出去 → 投后 + reserve 跟投 → 收获期退出 → 清算 + 给 LP 返钱(并以此业绩募下一支)。

入门 SOP 共 6 步, 失败模式自检 4 项。

相关心智模型:
  • Power-law 是世界观，不是事后观察到的结果 — 错过比投错致命: VC 的整门生意建立在「一支基金 80%+（业内估计，幂律分布的概数）回报来自 1-2 个 outlier、其余多数 deal 回本或归零」之上；因此判断一个 deal 的第一性问题不是「它稳不稳 /
  • 市场 / 赛道决定论 — 但「市场 vs 团队谁第一」是本行未决的派系张力: 这一行有一条强力镜片——「好团队遇上烂市场，市场赢；烂团队遇上好市场，市场赢」，市场天花板能不能容下一个 return-the-fund 的 outlier 是早期判断的硬约束；但与之并存的是另一极—

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**Fundraising / 募资(第 0-2 年)**:写 thesis + PPM,见各类 LP(机构 / FoF / family office / endowment / 国资),路演 deck,谈 fund terms(2% 管理费 / 20% carry / GP commitment),first close → final close。"
  "**Portfolio construction 定盘(募资后 / 部署前)**:用 fund size 反推 check size、目标项目数、ownership target、reserve 比例 —— 先把组合的数学画出来。(详见 W8)"
  "**部署期 / investment period(第 1-4 年)**:按 W2 一个个 deal 投出去,把初始 check 部署完(行业惯例 investment period 3-4 年)。"
  "**投后 + reserve / follow-on(第 2-8 年,与部署期重叠)**:board service、帮 portfolio 公司招人 / 融下一轮 / 处理危机;对跑出来的 winner 用 reserve 加倍跟投。(详见 W7、W8)"
  "**收获期 / 退出(第 5-10+ 年)**:推动 portfolio 公司走 IPO / 战略 M&A / secondary 出售,把账面价值(TVPI)变成真金白银(DPI);对明确失败的项目 write-off。(详见 W3 与退出相关的子流程)"
  "**清算 + LP 报告 + 募下一支**:基金到期清算,给 LP 季度 / 年度报告贯穿全程,用已实现业绩募下一支基金。"
)
declare -a FAILURE_MODES=(
  "**在估值高点把基金打光**:2021 那种高点一次性部署完,后续 down round 把整支基金的回报打骨折 —— 「刻意把 investment period 摊到 3-4 年、跨多个市场环境部署,用 vintage diversification 对冲;别因为 FOMO 在单一高点 all-in」。"
  "**reserve 不够、winner 接不住**:首轮投得太满 / 项目数太多,winner 起飞却没钱 follow-on —— 「募资后立刻定盘 portfolio construction,把 reserve 比例锁死(常见 40-60%),宁可初始少投几家」。"
  "**平时不理 LP,募资时才找**:把 LP 当一次性 ATM,基金中段零沟通 —— 「从第 1 年起固定季度 update + 闭门会,把 LP 关系当复利养;老 LP re-up 是下一支基金最便宜的钱」。"
  "**TVPI 高就躺平、不主动制造 DPI**:账面估值好看就不推退出,LP 拿不到现金 —— 「收获期主动用 secondary sale 制造流动性给 LP 返钱,别被动等 IPO 窗口;LP 考核的是 DPI 不是 TVPI」。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "fund-fundraising-exit-7-10-fund-walkthrough"
fi
