#!/usr/bin/env bash
# portfolio-construction-reserve.sh — Portfolio construction + reserve 策略 SOP walkthrough for 风险投资人 / 早期投资判断(GP + Principal — Deal sourcing / 尽调 / 估值与 term sheet / 投后服务 / 退出 + LP 关系与 fundraising — 涵盖 US 美元基金 + 国内 RMB / 美元基金).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="风险投资人 / 早期投资判断(GP + Principal — Deal sourcing / 尽调 / 估值与 term sheet / 投后服务 / 退出 + LP 关系与 fundraising — 涵盖 US 美元基金 + 国内 RMB / 美元基金)"
WORKFLOW="Portfolio construction + reserve 策略"

usage() {
  cat <<EOF
portfolio-construction-reserve.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./portfolio-construction-reserve.sh             # interactive
  ./portfolio-construction-reserve.sh --dry-run
  ./portfolio-construction-reserve.sh --json
  ./portfolio-construction-reserve.sh --explain
  ./portfolio-construction-reserve.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "Portfolio construction + reserve 策略" 工作流。

一句话: 在投出第一笔钱之前,把整支基金的数学先画出来 —— 用 fund size 反推 check size、目标项目数、ownership target、reserve 比例,让基金的结构本身能容纳一个 power-law 结果。

入门 SOP 共 4 步, 失败模式自检 4 项。

相关心智模型:
  • Power-law 是世界观，不是事后观察到的结果 — 错过比投错致命: VC 的整门生意建立在「一支基金 80%+（业内估计，幂律分布的概数）回报来自 1-2 个 outlier、其余多数 deal 回本或归零」之上；因此判断一个 deal 的第一性问题不是「它稳不稳 /
  • 市场 / 赛道决定论 — 但「市场 vs 团队谁第一」是本行未决的派系张力: 这一行有一条强力镜片——「好团队遇上烂市场，市场赢；烂团队遇上好市场，市场赢」，市场天花板能不能容下一个 return-the-fund 的 outlier 是早期判断的硬约束；但与之并存的是另一极—

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**从 fund size 反推组合宽度**:用基金规模 ÷ 计划的初始 check size,得出大致能投多少家公司(组合的宽度)。"
  "**定 ownership target**:决定每个 deal 要拿到的目标持股比例 —— 这个数决定了 check size 和能接受的估值,也决定 outlier 退出时能 return 多少。"
  "**留 reserve / follow-on**:把基金的一部分(行业常见 40-60%)留作 reserve,用于给跑出来的 winner 在后续轮加倍跟投。"
  "**定「集中 vs 分散」取向**:明确基金是 concentrated(少投、重投、深参与)还是 spray-and-pray(广撒小注),并让 check size / 项目数 / 投后强度一致。"
)
declare -a FAILURE_MODES=(
  "**不留够 reserve、winner 接不住**:首轮把基金投满 —— 「募资后立刻锁定 reserve 比例(常见 40-60%),宁可初始少投几家,也要留住接 winner 的子弹;这是新基金第一大结构性错误」。"
  "**ownership target 太低**:check size 相对估值太小,持股比例不够 —— 「先定每个 deal 的 ownership target,让它倒推 check size 和可接受估值;outlier 持股不够等于白投」。"
  "**策略和执行不一致**:口头 concentrated 却投了几十家,或口头广撒却每家深参与 —— 「明确『集中 vs 分散』取向,并让 check size / 项目数 / 投后强度全部对齐这个取向」。"
  "**把 construction 当开局设置、之后不管**:画完模型就投到底,不随 winner / loser 浮现重算 —— 「把 portfolio construction 当贯穿全程的实时约束,每次出 term sheet 前回头对一遍组合;reserve 是活的不是死的」。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "portfolio-construction-reserve-walkthrough"
fi
