#!/usr/bin/env bash
# term-sheet.sh — Term sheet 谈判 + 估值 SOP walkthrough for 风险投资人 / 早期投资判断(GP + Principal — Deal sourcing / 尽调 / 估值与 term sheet / 投后服务 / 退出 + LP 关系与 fundraising — 涵盖 US 美元基金 + 国内 RMB / 美元基金).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="风险投资人 / 早期投资判断(GP + Principal — Deal sourcing / 尽调 / 估值与 term sheet / 投后服务 / 退出 + LP 关系与 fundraising — 涵盖 US 美元基金 + 国内 RMB / 美元基金)"
WORKFLOW="Term sheet 谈判 + 估值"

usage() {
  cat <<EOF
term-sheet.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./term-sheet.sh             # interactive
  ./term-sheet.sh --dry-run
  ./term-sheet.sh --json
  ./term-sheet.sh --explain
  ./term-sheet.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "Term sheet 谈判 + 估值" 工作流。

一句话: 把「决定要投」翻译成一份双方能签的 term sheet —— 定估值(pre/post-money + option pool)、选轮次工具(SAFE / 可转债 / priced round)、谈关键条款(董事会 / liquidation preference / pro-rata / anti-dilution),并在「赢条款」和「保关系」之间找平衡。

入门 SOP 共 5 步, 失败模式自检 4 项。

相关心智模型:
  • Power-law 是世界观，不是事后观察到的结果 — 错过比投错致命: VC 的整门生意建立在「一支基金 80%+（业内估计，幂律分布的概数）回报来自 1-2 个 outlier、其余多数 deal 回本或归零」之上；因此判断一个 deal 的第一性问题不是「它稳不稳 /
  • 市场 / 赛道决定论 — 但「市场 vs 团队谁第一」是本行未决的派系张力: 这一行有一条强力镜片——「好团队遇上烂市场，市场赢；烂团队遇上好市场，市场赢」，市场天花板能不能容下一个 return-the-fund 的 outlier 是早期判断的硬约束；但与之并存的是另一极—

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**定估值结构**:确定 pre-money 估值、投资额、option pool 大小**和它算在 pre 还是 post**(pool 算在 pre 侧 = 创始人多稀释)。"
  "**选轮次工具**:种子期常用 SAFE / 可转债(不定价、快)；A 轮及以后用 priced round(定价、有完整条款)。"
  "**谈 economics 条款**:liquidation preference(1x non-participating 是市场标准,participating / multiple 是给创始人的隐性税)、估值、期权池。"
  "**谈 control 条款**:董事会席位 / 构成、保护性条款(protective provisions)、pro-rata 权利、anti-dilution。"
  "**谈判到签字**:与创始人(及其他 co-investor)来回,把非标条款收敛到双方能接受,签 term sheet。"
)
declare -a FAILURE_MODES=(
  "**只谈估值数字、忽略 option pool 在哪侧**:以为「高估值 = 对创始人好」 —— 「报 / 看估值时永远确认是 pre 还是 post、option pool 算在哪侧,这一步定创始人实际稀释」。"
  "**接受非标 liquidation preference 而不自知**:participating / 2x+ multiple 被当正常 —— 「记住 1x non-participating 是市场标准,任何超出都是隐性税;高估值 + 差 preference 不是好 deal」。"
  "**逐条款都想赢、输掉关系**:把 term sheet 当一次性博弈 —— 「term sheet 是 7-10 年关系的第一次握手,在不重要的条款让步、只守住估值合理性 / pro-rata / 董事会;赢光条款是输」。"
  "**拿不到 pro-rata 就签**:不争 pro-rata 权利 —— 「pro-rata 是接住 winner 的入场券,早期 deal 哪怕条款让步也要守住 pro-rata」。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "term-sheet-walkthrough"
fi
