#!/usr/bin/env bash
# general-playbook.sh — 通用 Playbook 决策助手 for 心理咨询 / 心理治疗(临床实践者视角 — 接案与评估 / 个案概念化 / 主流流派技术(CBT 与第三浪潮 / 精神动力 / 人本存在 / 家庭系统 / 创伤治疗) / 伦理边界与危机干预 / 督导与个人成长 / 执业形态与经营 — 涵盖中国大陆行业现状 + 欧美持照体系,两套体系差异极大).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="心理咨询 / 心理治疗(临床实践者视角 — 接案与评估 / 个案概念化 / 主流流派技术(CBT 与第三浪潮 / 精神动力 / 人本存在 / 家庭系统 / 创伤治疗) / 伦理边界与危机干预 / 督导与个人成长 / 执业形态与经营 — 涵盖中国大陆行业现状 + 欧美持照体系,两套体系差异极大)"
TOPIC="通用 Playbook"

usage() {
  cat <<EOF
general-playbook.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 1 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./general-playbook.sh             # interactive
  ./general-playbook.sh --dry-run   # walk through but no file
  ./general-playbook.sh --json      # JSON to stdout
  ./general-playbook.sh --explain   # show backing playbook rules + mental models
  ./general-playbook.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 通用 Playbook 主题下的 playbook 规则组合成交互树。

基于 1 条规则:
  • 如果 一个对话出现危机信号(自杀念头 / 自伤升级 / 透露受虐或施虐 / 急性精神病性症状) → 则 切换到硬边界模式:直接、具体地问(不因「怕诱导」而回避)→ 用结构化工具(如 C-SSRS)评估严重度 → 立即导向相应

相关心智模型:
  • 治疗关系 / 共同要素 > 单一技术: 这一行的资深人默认「治疗关系的质量、共情、期望、来访者因素」这些**跨流派共有的共同要素**对疗效的解释力,可能不亚于任一流派的特定技术 —— 所以「学对了流派」从来不够,「谁来做、和来访者建立了什么
  • 症状是有功能 / 是适应,不是单纯的「病」: 这一行的人看一个症状,默认先问「它在为这个人 / 这个系统**做什么**」—— 症状常是某个困境下能找到的最优解、是适应而非缺陷,去病理化地理解它,比急着「消除」它更接近治疗。

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "一个对话出现危机信号(自杀念头 / 自伤升级 / 透露受虐或施虐 / 急性精神病性症状)"
)
declare -a RULE_ACTIONS=(
  "切换到硬边界模式:直接、具体地问(不因「怕诱导」而回避)→ 用结构化工具(如 C-SSRS)评估严重度 → 立即导向相应强度的资源(高危→急诊 / 危机热线如美国 988;中危→协作安全计划 + 提高随访密度;涉虐待 / 对他人危险→履行法定报告 / 警告义务;急性精神病性→精神科评估)→ 调动上级督导 → 完整记录 + 安排随访"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "general-playbook-decision"
fi
