#!/usr/bin/env bash
# topic-1.sh — —— 决策助手 for 心理咨询 / 心理治疗(临床实践者视角 — 接案与评估 / 个案概念化 / 主流流派技术(CBT 与第三浪潮 / 精神动力 / 人本存在 / 家庭系统 / 创伤治疗) / 伦理边界与危机干预 / 督导与个人成长 / 执业形态与经营 — 涵盖中国大陆行业现状 + 欧美持照体系,两套体系差异极大).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="心理咨询 / 心理治疗(临床实践者视角 — 接案与评估 / 个案概念化 / 主流流派技术(CBT 与第三浪潮 / 精神动力 / 人本存在 / 家庭系统 / 创伤治疗) / 伦理边界与危机干预 / 督导与个人成长 / 执业形态与经营 — 涵盖中国大陆行业现状 + 欧美持照体系,两套体系差异极大)"
TOPIC="——"

usage() {
  cat <<EOF
topic-1.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 9 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-1.sh             # interactive
  ./topic-1.sh --dry-run   # walk through but no file
  ./topic-1.sh --json      # JSON to stdout
  ./topic-1.sh --explain   # show backing playbook rules + mental models
  ./topic-1.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 —— 主题下的 playbook 规则组合成交互树。

基于 9 条规则:
  • 如果 一个对话涉及来访者「该怎么办 / 该用什么技术」,而手上只有一个 DSM / ICD 诊断标签 → 则 不要止于标签 —— 先逼出一个成文的个案概念化:回答「什么在维持这个问题、来访者的资源在哪、从哪个点切入阻力最小」,技术
  • 如果 遇到任何执业资质 / 伦理守则 / 转介 / 监管 / 理论适配的判断 → 则 第一个动作是确定 locale —— 中国大陆和欧美持照体系是结构性不同的两套东西,不是同一套的本地化,绝不能把欧美执照
  • 如果 遇到危机个案 / 伦理两难 / 卡住的个案 / 强烈的反移情反应 → 则 不独自决定 —— 带进督导或同行咨询。这一行的「独立执业」从不意味着「独自工作」;危机个案理想是当天就联系专业支持网
  • 如果 遇到长期、反复、人际性的创伤个案(复杂性创伤 / C-PTSD) → 则 不要一上来就做创伤记忆暴露 —— 先评估稳定性与资源,缺乏稳定化时优先建立安全(情绪调节技能、生活结构、关系安全),稳定
  • 如果 来访者突然疏远 / 迟到 / 质疑 / 你感到治疗关系紧张(联盟破裂的信号) → 则 不回避也不归咎来访者 —— 直接在「此时此地」命名并探索这个紧张;修复破裂往往是最有价值的治疗时刻,一段从不破裂的关系反
  • 如果 要判断「这个治疗有没有用 / 该不该结案 / 该不该转介」,而手上只有治疗师的主观感觉 → 则 加上会谈级的结果监测(如 ORS / SRS,反馈知情治疗 FIT)—— 用数据看联盟与进展的曲线,数据提示联盟下降 /
  • 如果 被问「哪个流派最好」或自己在纠结该认同哪一派 → 则 把它当成错误问题来处理 —— 按「障碍 × 证据等级 × 来访者偏好与文化」匹配,而不是按流派身份认同;同时不要走到另一
  • 如果 在做临床仪器(测评量表 / 诊断系统 / 风险评估工具)的选型 → 则 按「信效度 + 临床定位 + 版权可得性 + 使用资质」判断,不是按「功能 / 价格」—— 且牢记「工具输出 ≠ 临床决
  • 如果 遇到来访者反应与所学理论「不符」,或要把一个西方框架用在中国来访者身上 → 则 先假设是文化差异而非病理或阻抗 —— 以文化谦逊的姿态持续核对,而不是用理论硬套。西方治疗理论的默认假设(个人主义、直接

相关心智模型:
  • 治疗关系 / 共同要素 > 单一技术: 这一行的资深人默认「治疗关系的质量、共情、期望、来访者因素」这些**跨流派共有的共同要素**对疗效的解释力,可能不亚于任一流派的特定技术 —— 所以「学对了流派」从来不够,「谁来做、和来访者建立了什么
  • 症状是有功能 / 是适应,不是单纯的「病」: 这一行的人看一个症状,默认先问「它在为这个人 / 这个系统**做什么**」—— 症状常是某个困境下能找到的最优解、是适应而非缺陷,去病理化地理解它,比急着「消除」它更接近治疗。

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "一个对话涉及来访者「该怎么办 / 该用什么技术」,而手上只有一个 DSM / ICD 诊断标签"
  "遇到任何执业资质 / 伦理守则 / 转介 / 监管 / 理论适配的判断"
  "遇到危机个案 / 伦理两难 / 卡住的个案 / 强烈的反移情反应"
  "遇到长期、反复、人际性的创伤个案(复杂性创伤 / C-PTSD)"
  "来访者突然疏远 / 迟到 / 质疑 / 你感到治疗关系紧张(联盟破裂的信号)"
  "要判断「这个治疗有没有用 / 该不该结案 / 该不该转介」,而手上只有治疗师的主观感觉"
  "被问「哪个流派最好」或自己在纠结该认同哪一派"
  "在做临床仪器(测评量表 / 诊断系统 / 风险评估工具)的选型"
  "遇到来访者反应与所学理论「不符」,或要把一个西方框架用在中国来访者身上"
)
declare -a RULE_ACTIONS=(
  "不要止于标签 —— 先逼出一个成文的个案概念化:回答「什么在维持这个问题、来访者的资源在哪、从哪个点切入阻力最小」,技术选择跟在概念化之后"
  "第一个动作是确定 locale —— 中国大陆和欧美持照体系是结构性不同的两套东西,不是同一套的本地化,绝不能把欧美执照路径(LMFT / LCSW / LPC / 博士;BACP / UKCP)套到中国,反之亦然"
  "不独自决定 —— 带进督导或同行咨询。这一行的「独立执业」从不意味着「独自工作」;危机个案理想是当天就联系专业支持网"
  "不要一上来就做创伤记忆暴露 —— 先评估稳定性与资源,缺乏稳定化时优先建立安全(情绪调节技能、生活结构、关系安全),稳定后再考虑创伤加工。跳过稳定化是高二次伤害风险"
  "不回避也不归咎来访者 —— 直接在「此时此地」命名并探索这个紧张;修复破裂往往是最有价值的治疗时刻,一段从不破裂的关系反而可疑"
  "加上会谈级的结果监测(如 ORS / SRS,反馈知情治疗 FIT)—— 用数据看联盟与进展的曲线,数据提示联盟下降 / 长期无进展时主动重新概念化或讨论转介,而非默认「继续做就会好」"
  "把它当成错误问题来处理 —— 按「障碍 × 证据等级 × 来访者偏好与文化」匹配,而不是按流派身份认同;同时不要走到另一极端否定特异性技术(某些障碍如 OCD / PTSD / 特定恐惧症确有技术效应证据)"
  "按「信效度 + 临床定位 + 版权可得性 + 使用资质」判断,不是按「功能 / 价格」—— 且牢记「工具输出 ≠ 临床决策」:诊断 ≠ 个案概念化,筛查量表 ≠ 诊断工具,评估工具 ≠ 临床判断"
  "先假设是文化差异而非病理或阻抗 —— 以文化谦逊的姿态持续核对,而不是用理论硬套。西方治疗理论的默认假设(个人主义、直接自我表达、清晰边界)对中国来访者需要再加工"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-1-decision"
fi
