#!/usr/bin/env bash
# scoping-ai-feature.sh — Scoping 一个 AI feature（「想法」阶段） SOP walkthrough for AI 产品经理 (LLM 应用 / 生成式 AI / Agent 产品 / Copilot 嵌入 — 跨模型评估 / 工作流设计 / 产品-工程协同).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="AI 产品经理 (LLM 应用 / 生成式 AI / Agent 产品 / Copilot 嵌入 — 跨模型评估 / 工作流设计 / 产品-工程协同)"
WORKFLOW="Scoping 一个 AI feature（「想法」阶段）"

usage() {
  cat <<EOF
scoping-ai-feature.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./scoping-ai-feature.sh             # interactive
  ./scoping-ai-feature.sh --dry-run
  ./scoping-ai-feature.sh --json
  ./scoping-ai-feature.sh --explain
  ./scoping-ai-feature.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "Scoping 一个 AI feature（「想法」阶段）" 工作流。

一句话: 把一个「能不能用 AI 做 X」的模糊想法，变成一份「该不该做 + 走哪条技术路 + 用什么标准判断成功」的可执行 scoping 文档 —— 从「业务诉求」状态到「团队可以开干」状态。

入门 SOP 共 6 步, 失败模式自检 3 项。

相关心智模型:
  • Eval 是地基,不是可选项（别 vibe-check）: 「AI 产品的『好』不是看几个 case 觉得行就 ship —— 是先针对你**自己产品的失败模式**建一套可重复、可回归的系统化测量;没有 eval 就是在瞎改。」
  • 先 error analysis,再加功能（PM 亲自看 trace）: 「质量上不去时,资深 AI PM 的第一反应**不是加功能**,是 PM 亲自拉 10-50 个真实 trace（trace 条数量级见 Hamel field-guide T03-S001 / ev

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**澄清「真问题」**：把「加个 AI X」翻译成「用户的什么 pain point」。PM 主导。跳过 → 做出一个技术上能跑但没人要的功能（intake warning「prompt engineering 不是核心，产品 fit 判断才是」）。"
  "**判断该不该用 AI**：问「这个问题确定性规则能不能解 / 传统 ML 能不能解 / 真的需要生成式吗」。PM 主导。跳过 → 用 LLM 做了一件正则就能做的事，背上不必要的成本和不可靠性。"
  "**技术路线初判**：和工程师一起过一遍 prompt-only → RAG → agent → finetune 的阶梯，**默认从最便宜的假设起**（Anthropic「先简单后复杂」）。PM + ML 工程师共同。跳过 → 一上来设计 agent / 上 vector DB，过度工程（06-glossary「一遇到不准就喊 fine-tune」反模式）。 (evidence: [T03-S002])"
  "**定义成功标准**：把「好」拆成具体、二元可判的 failure mode + 目标 pass 率，而不是「准确率」。PM 主导（PM 是首席领域专家）。跳过 → 进入迭代后没有靶子，全凭 vibes。 (evidence: [T03-S006, T03-S008])"
  "**粗算成本约束**：token 单价 × 预期用户行为 × 留存 → 单用户成本能不能撑住定价。PM 主导。跳过 → MVP 做出来才发现单位经济模型为负，ship 不了（intake warning「成本控制是被忽视的硬技能」）。"
  "**风险分级**：判断是否落入监管高风险类别（EU AI Act / 中国生成式 AI 办法），决定要不要法务早期介入。PM 主导，法务确认。跳过 → 高风险产品做到一半被合规打回。 (evidence: [T03-S006] + 06-glossary 工作流变化种子)"
)
declare -a FAILURE_MODES=(
  "**「从能力出发」而非「从问题出发」**：触发原因 = 被新模型能力诱惑（\"GPT-5.5 能做这个，我们也加\"）；怎么避免 = 强制 step 1 先写用户 pain point，能力是手段不是起点。（**CLI 自检项**：Did you start from a user pain point, or from a model capability you wanted to use? If the latter — stop and rewrite the problem statement.） (evidence: [T03-S006])"
  "**规格写得像传统 PRD（确定性、可穷举）**：触发原因 = 用传统 PM 习惯套 AI；怎么避免 = 接受规格只能写到「已知的失败模式 + 待 POC 回答的未知」，剩下靠迭代涌现。（**CLI 自检项**：Does your spec pretend every edge case is knowable up front? AI specs emerge from output inspection — list what you DON'T know yet.） (evidence: [T03-S006])"
  "**不算单用户经济模型就进 POC**：触发原因 = 课程不教、PM 觉得是工程的事；怎么避免 = scoping 文档强制一行「单用户/月预估 API 成本 vs 定价」。（**CLI 自检项**：Have you done a back-of-envelope token-cost-per-user-per-month estimate? If not, you may be scoping a product that can't ship.）"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "scoping-ai-feature-walkthrough"
fi
