#!/usr/bin/env bash
# topic-2.sh — —— 决策助手 for 风险投资人 / 早期投资判断(GP + Principal — Deal sourcing / 尽调 / 估值与 term sheet / 投后服务 / 退出 + LP 关系与 fundraising — 涵盖 US 美元基金 + 国内 RMB / 美元基金).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="风险投资人 / 早期投资判断(GP + Principal — Deal sourcing / 尽调 / 估值与 term sheet / 投后服务 / 退出 + LP 关系与 fundraising — 涵盖 US 美元基金 + 国内 RMB / 美元基金)"
TOPIC="——"

usage() {
  cat <<EOF
topic-2.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 3 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-2.sh             # interactive
  ./topic-2.sh --dry-run   # walk through but no file
  ./topic-2.sh --json      # JSON to stdout
  ./topic-2.sh --explain   # show backing playbook rules + mental models
  ./topic-2.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 —— 主题下的 playbook 规则组合成交互树。

基于 3 条规则:
  • 如果 在分配尽调时间 / 投后精力 / reserve 资金 → 则 按 power-law 给它们分级——winner 和「还能救」的公司优先，对明确的 loser 快速降投入甚至主动 w
  • 如果 在建一支新基金的组合 → 则 先留够 reserve（行业常见 40-60%）再投初始 check——首轮把基金投满、winner 起飞却无钱 fol
  • 如果 遇到「该走什么模式 / 该集中还是该分散 / 该不该做平台」这类方法论问题，或遇到「XX 月入 N 万、7 步进 VC」 → 则 先问对方属于或想走哪一派（thesis-driven / spray-and-pray / concentrated /

相关心智模型:
  • Power-law 是世界观，不是事后观察到的结果 — 错过比投错致命: VC 的整门生意建立在「一支基金 80%+（业内估计，幂律分布的概数）回报来自 1-2 个 outlier、其余多数 deal 回本或归零」之上；因此判断一个 deal 的第一性问题不是「它稳不稳 /
  • 市场 / 赛道决定论 — 但「市场 vs 团队谁第一」是本行未决的派系张力: 这一行有一条强力镜片——「好团队遇上烂市场，市场赢；烂团队遇上好市场，市场赢」，市场天花板能不能容下一个 return-the-fund 的 outlier 是早期判断的硬约束；但与之并存的是另一极—

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "在分配尽调时间 / 投后精力 / reserve 资金"
  "在建一支新基金的组合"
  "遇到「该走什么模式 / 该集中还是该分散 / 该不该做平台」这类方法论问题，或遇到「XX 月入 N 万、7 步进 VC」这类成功叙事"
)
declare -a RULE_ACTIONS=(
  "按 power-law 给它们分级——winner 和「还能救」的公司优先，对明确的 loser 快速降投入甚至主动 write-off，拒绝平均用力"
  "先留够 reserve（行业常见 40-60%）再投初始 check——首轮把基金投满、winner 起飞却无钱 follow-on，是新基金最常见的结构性错误；reserve 是活的，要随 winner / loser 浮现持续重算"
  "先问对方属于或想走哪一派（thesis-driven / spray-and-pray / concentrated / solo GP / 国内多元化），并对收入 / 业绩数字追问分布、样本、口径——同一问题不同派给完全相反的答案，且公开 brand ≠ 投资能力、公开数据是冰山一角"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-2-decision"
fi
