#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 八字命理 + 玄学相关数术 (子平派 / 盲派 / 新派 / 紫微斗数边界).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="八字命理 + 玄学相关数术 (子平派 / 盲派 / 新派 / 紫微斗数边界)"
DIM_COUNT=3

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (3 个):
  9.1 sub_skill 候选 (女娲蒸馏, 选 2-3 人)
  9.2 cli 候选 (cli_writer.py 抽取)
  9.3 Cumulative findings issues (跨 track 矛盾标注)

背后的心智模型:
  • 格局 + 用神 二元 (子平派核心): 「看八字第一步永远是『先定格局, 再取用神』 — 沈孝瞻"八字用神, 专求月令", 用神是格局生态里的角色, 不是孤立五行」
  • 调候 寒暖燥湿 (穷通宝鉴心法): 「不分寒暖燥湿就取用神 = 命理偏枯. 月令 + 日干两轴查表 — 庚金生申月需丁火炼 + 甲木引, 乙木生秋月需壬水滋, 这是物理 / 自然规律对应到八字气化层」
  • 象法 vs 理法 二分 (学派分歧标志, 子平 vs 盲派核心): 「同一八字, 子平派看『理法』(月令 + 格局 + 用神 + 扶抑) — 静态结构; 盲派看『象法』(主宾 + 体用 + 取象 + 直断) — 动态象征. 不是哪派对哪派错, 是看到的维度不同」

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "sub_skill 候选 (女娲蒸馏, 选 2-3 人)"
  "cli 候选 (cli_writer.py 抽取)"
  "Cumulative findings issues (跨 track 矛盾标注)"
)
declare -a DIM_QUESTIONS=(
  ""
  ""
  ""
)
declare -a DIM_SOURCES=(
  ""
  ""
  ""
)
declare -a DIM_OUTPUT_FORMATS=(
  ""
  ""
  ""
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
