#!/usr/bin/env bash
# trigger.sh — Trigger 决策助手 for iOS 应用上架大师 (审核 + ASO + 合规 + 国内/海外多区 + 付费策略).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="iOS 应用上架大师 (审核 + ASO + 合规 + 国内/海外多区 + 付费策略)"
TOPIC="Trigger"

usage() {
  cat <<EOF
trigger.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 8 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./trigger.sh             # interactive
  ./trigger.sh --dry-run   # walk through but no file
  ./trigger.sh --json      # JSON to stdout
  ./trigger.sh --explain   # show backing playbook rules + mental models
  ./trigger.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 Trigger 主题下的 playbook 规则组合成交互树。

基于 8 条规则:
  • 如果 D2 — Rejection 处理: Resolution Center 短/具体/引 ARG → 则 - **trigger**: 收到 Apple 拒绝信
  • 如果 D3 — 政策时效跟踪节奏 → 则 - **trigger**: 持续运营 + WWDC / iOS major / ASC 更新
  • 如果 D4 — ASO 优化: 数据驱动 vs Audience 驱动 → 则 - **trigger**: 上架后 30-90 天 + 持续 iterate
  • 如果 D5 — 多区策略: US / EU / CN → 则 - **trigger**: 决定上架哪些地区
  • 如果 D6 — 商业模型: 接受 30% Tax + IAP 内优化, 不抗议 → 则 - **trigger**: 决定 monetize 路径
  • 如果 D7 — 隐私合规: ATT + Privacy Manifest + GDPR 三件套 → 则 - **trigger**: 提审 / 持续运营
  • 如果 D8 — 国内合规 4 件套 (大陆出海 / 国内市场) → 则 - **trigger**: 上架国区 / 国内多市场
  • 如果 D9 — 工具栈选择: stage-appropriate → 则 - **trigger**: 选 build / ASO / 隐私 / 订阅 工具

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "D2 — Rejection 处理: Resolution Center 短/具体/引 ARG"
  "D3 — 政策时效跟踪节奏"
  "D4 — ASO 优化: 数据驱动 vs Audience 驱动"
  "D5 — 多区策略: US / EU / CN"
  "D6 — 商业模型: 接受 30% Tax + IAP 内优化, 不抗议"
  "D7 — 隐私合规: ATT + Privacy Manifest + GDPR 三件套"
  "D8 — 国内合规 4 件套 (大陆出海 / 国内市场)"
  "D9 — 工具栈选择: stage-appropriate"
)
declare -a RULE_ACTIONS=(
  "- **trigger**: 收到 Apple 拒绝信"
  "- **trigger**: 持续运营 + WWDC / iOS major / ASC 更新"
  "- **trigger**: 上架后 30-90 天 + 持续 iterate"
  "- **trigger**: 决定上架哪些地区"
  "- **trigger**: 决定 monetize 路径"
  "- **trigger**: 提审 / 持续运营"
  "- **trigger**: 上架国区 / 国内多市场"
  "- **trigger**: 选 build / ASO / 隐私 / 订阅 工具"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "trigger-decision"
fi
