#!/usr/bin/env bash
# adr.sh — Adr 决策助手 for 软件架构 (含 应用架构 / 系统架构 / 分布式 后端架构 / 前后端 数据流 与 数据模型 设计 / API 边界 / 可扩展性 / 演进式架构 — 不含 硬件架构 / 纯企业架构 / 纯 DevOps / 纯安全架构).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="软件架构 (含 应用架构 / 系统架构 / 分布式 后端架构 / 前后端 数据流 与 数据模型 设计 / API 边界 / 可扩展性 / 演进式架构 — 不含 硬件架构 / 纯企业架构 / 纯 DevOps / 纯安全架构)"
TOPIC="Adr"

usage() {
  cat <<EOF
adr.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 4 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./adr.sh             # interactive
  ./adr.sh --dry-run   # walk through but no file
  ./adr.sh --json      # JSON to stdout
  ./adr.sh --explain   # show backing playbook rules + mental models
  ./adr.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 Adr 主题下的 playbook 规则组合成交互树。

基于 4 条规则:
  • 如果 ADR 写完没人读 → 则 : ADR 流程死, 改成 lightweight (≤ 1 页) + per-PR 嵌入 + 跟 git diff 一
  • 如果 选型有 5 个候选 → 则 : 不开会拍板; POC 2 个候选 2 周, ADR 记录 trade-off + 退出策略
  • 如果 LLM (Copilot / Cursor / Claude Code) 提议关键 trade-off → 则 : **默认拒绝**, 自己想; LLM 仅用于 boilerplate / pattern lookup / ADR 
  • 如果 vendor 锁定 > 60% → 则 (业内估, 单一 cloud / 单一 db / 单一 observability): 标记 risk + 写 exit

相关心智模型:
  • 耦合 (coupling) 是唯一的硬通货 — 其它都是衍生: 软件架构本质 = 管理跨"独立变化速率"事物之间的依赖. Parnas 1972 "On the Criteria" 已说清: 模块边界要按"未来变化的轴"划, 不是按"功能流程"划. Fowler 
  • 架构 = 你早期希望做对、晚期改不动的那些决定 (the stuff that's hard to change later): Fowler 1999 给"architecture" 的工作定义: *architecture is about the important stuff, whatever that is — th

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "ADR 写完没人读"
  "选型有 5 个候选"
  "LLM (Copilot / Cursor / Claude Code) 提议关键 trade-off"
  "vendor 锁定 > 60%"
)
declare -a RULE_ACTIONS=(
  ": ADR 流程死, 改成 lightweight (≤ 1 页) + per-PR 嵌入 + 跟 git diff 一起 code review"
  ": 不开会拍板; POC 2 个候选 2 周, ADR 记录 trade-off + 退出策略"
  ": **默认拒绝**, 自己想; LLM 仅用于 boilerplate / pattern lookup / ADR draft / test gen / commit message"
  "(业内估, 单一 cloud / 单一 db / 单一 observability): 标记 risk + 写 exit-strategy ADR + 至少 1 个 abstraction layer (OpenTelemetry / Terraform / SQL-only ORM) 隔离"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "adr-decision"
fi
