#!/usr/bin/env bash
# jd.sh — 简历优化流程（JD 拆解 → 量化成就 → 关键词 → 格式） SOP walkthrough for 求职 / 面试辅导(求职教练视角 — 求职定位与职业叙事 / 简历与 ATS 优化 / 求职渠道与内推策略 / 职场社交 / 行为面试与专业面试 / 面试心理与表达 / 谈薪与 offer 决策 / 校招与应届生 / 转行求职 / 特殊群体求职 / 求职教练的执业经营 — 涵盖中国大陆求职生态 + 海外英语区求职体系,两套差异极大).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="求职 / 面试辅导(求职教练视角 — 求职定位与职业叙事 / 简历与 ATS 优化 / 求职渠道与内推策略 / 职场社交 / 行为面试与专业面试 / 面试心理与表达 / 谈薪与 offer 决策 / 校招与应届生 / 转行求职 / 特殊群体求职 / 求职教练的执业经营 — 涵盖中国大陆求职生态 + 海外英语区求职体系,两套差异极大)"
WORKFLOW="简历优化流程（JD 拆解 → 量化成就 → 关键词 → 格式）"

usage() {
  cat <<EOF
jd.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./jd.sh             # interactive
  ./jd.sh --dry-run
  ./jd.sh --json
  ./jd.sh --explain
  ./jd.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "简历优化流程（JD 拆解 → 量化成就 → 关键词 → 格式）" 工作流。

一句话: 把一份简历针对一个 / 一类岗位优化到「机器读得顺、人看得清、且全部属实」—— 核心是「针对性」和「举证」，硬约束是**优化不是造假**。

入门 SOP 共 5 步, 失败模式自检 5 项。

相关心智模型:
  • 定位先于一切执行（定位错了，后面是高效地做错事）: 求职的第一性问题不是「简历怎么写 / 该投哪」，而是「要找哪一类岗位 + 为什么是我」—— 目标不收敛时，改简历、海投、练面试都是在高效地做错的事。
  • 从招聘方 / ATS / 岗位的痛点出发倒推（不是从「我想要什么」出发）: 简历、触达、面试答案的组织原点是「这个岗位 / 招聘经理在解决什么问题」，不是「我想说什么」—— 招聘经理立项前往往已缺人 6-12 个月，他要的是「缓解」。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**JD 拆解**：把目标 JD 拆成「硬性要求 / 加分项 / 高频关键词 / 这个岗位真正在解决什么问题」。**跳过会发生什么**：不拆 JD 直接写 → 简历是「我有什么」而非「岗位要什么」，匹配度低、初筛（机器或人）都过不去。"
  "**经历 → 量化成就改写**：把每段经历从「负责 X」改写成「做到了 X（用 Y 衡量），靠做 Z」（Jeff Su 的 X-Y-Z 公式）—— 用数字 / 结果，不用职责描述。**跳过会发生什么**：简历是职责罗列 → 招聘方看不出你「干成了什么」，和所有同岗位候选人长一样。"
  "**关键词对齐**：把 JD 里的关键技能 / 工具 / 术语，在简历里用**真实经历**自然覆盖（海外网申场景用 Jobscan / Teal 做匹配度检查）。**跳过会发生什么**：海外网申场景关键词不匹配 → ATS 初筛 + 人眼初筛都判「不相关」。"
  "**格式与可读性**：海外格式严格匿名化（无照片 / 年龄 / 婚育）+ 简洁可解析（避免复杂表格 / 图片破坏机器可读性）；国内格式常含照片 / 学校 / 实习。**跳过会发生什么**：海外简历带照片 → 给招聘方制造合规顾虑；格式花哨 → ATS 解析失败 / 人眼疲劳。"
  "**真实性核对（红线步骤）**：核对每一条 —— 经历真实、数字可验证、头衔没改、能力没夸大。**跳过会发生什么**：编造经历 / 改头衔 / 虚构数字 → 背调和试用期会暴露，offer 撤回 + 职业污点。**这一步不可跳过、不可外包给 AI 决定**。"
)
declare -a FAILURE_MODES=(
  "**把「美化」和「编造」混为一谈**：触发原因 = 红线模糊 + 「大家都美化」；后果 = 越过造假线，背调 / 试用期暴露，offer 撤回 + 职业污点。怎么避免：教练硬划红线 —— 重新组织和包装真实经历可以，编造事实不可以。"
  "**不拆 JD，写一份「万能简历」投所有岗位**：触发原因 = 嫌定制麻烦；后果 = 简历是「我有什么」而非「岗位要什么」，全线低匹配。怎么避免：每类岗位先拆 JD，至少做岗位簇级别的定制。"
  "**把 ATS 匹配度刷到越高越好**：触发原因 = 把工具分数当 KPI；后果 = keyword stuffing，人眼看到反而减分，且 ATS 语义化后纯关键词失效。怎么避免：匹配度当参考不当目标，关键词要用真实经历自然覆盖。"
  "**让 LLM 直接生成整份简历就投出去**：触发原因 = 图省事；后果 = AI 味措辞被识别成减分项，且 LLM 容易「美化到编造」。怎么避免：AI 辅助后必做「去 AI 味 + 个性化 + 真实性核对」。"
  "**海外简历照搬国内格式（带照片 / 年龄）**：触发原因 = 不懂匿名化反歧视惯例；后果 = 不专业 + 给招聘方制造合规顾虑。怎么避免：按目标地区惯例 —— 海外严格匿名化。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "jd-walkthrough"
fi
