#!/usr/bin/env bash
# workflow-6.sh — 谈薪流程 SOP walkthrough for 求职 / 面试辅导(求职教练视角 — 求职定位与职业叙事 / 简历与 ATS 优化 / 求职渠道与内推策略 / 职场社交 / 行为面试与专业面试 / 面试心理与表达 / 谈薪与 offer 决策 / 校招与应届生 / 转行求职 / 特殊群体求职 / 求职教练的执业经营 — 涵盖中国大陆求职生态 + 海外英语区求职体系,两套差异极大).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="求职 / 面试辅导(求职教练视角 — 求职定位与职业叙事 / 简历与 ATS 优化 / 求职渠道与内推策略 / 职场社交 / 行为面试与专业面试 / 面试心理与表达 / 谈薪与 offer 决策 / 校招与应届生 / 转行求职 / 特殊群体求职 / 求职教练的执业经营 — 涵盖中国大陆求职生态 + 海外英语区求职体系,两套差异极大)"
WORKFLOW="谈薪流程"

usage() {
  cat <<EOF
workflow-6.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-6.sh             # interactive
  ./workflow-6.sh --dry-run
  ./workflow-6.sh --json
  ./workflow-6.sh --explain
  ./workflow-6.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "谈薪流程" 工作流。

一句话: 从「即将拿 offer」到「谈定并完成 offer 决策」—— 谈薪是有信息基础、有时机、有话术、多变量的博弈，不是「张口要个数字」；核心是「把球踢回去 + 比总包不比 base + 用真实杠杆」。

入门 SOP 共 5 步, 失败模式自检 5 项。

相关心智模型:
  • 定位先于一切执行（定位错了，后面是高效地做错事）: 求职的第一性问题不是「简历怎么写 / 该投哪」，而是「要找哪一类岗位 + 为什么是我」—— 目标不收敛时，改简历、海投、练面试都是在高效地做错的事。
  • 从招聘方 / ATS / 岗位的痛点出发倒推（不是从「我想要什么」出发）: 简历、触达、面试答案的组织原点是「这个岗位 / 招聘经理在解决什么问题」，不是「我想说什么」—— 招聘经理立项前往往已缺人 6-12 个月，他要的是「缓解」。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**信息搜集（定 anchor）**：查目标岗位 / 职级 / 地点的市场薪资 —— 海外科技岗用 levels.fyi、通用岗用 Glassdoor / Payscale；国内用招聘平台区间 + 看准网 + 脉脉职言交叉。定一个 anchor（目标值）和 walk-away（底线）。**跳过会发生什么**：没有市场数据 → 报价没有锚、不知道对方报的合不合理，要么贱卖要么报得离谱出局。"
  "**管理「先报数字」的时机**：被过早问期望薪资时，尽量把球踢回去（「想先了解这个岗位的预算区间 / 整体 package」），不在信息不足时第一个报数字。**跳过会发生什么**：过早报数 —— 报低了贱卖自己、报高了被直接 pass（Madeline Mann 的「别先报数字」核心）。"
  "**拿到 offer 后再正式谈**：口头 / 正式 offer 到手后才是谈判窗口（offer 没正式接受前都还能谈），用「我对这个机会很感兴趣 + 基于市场数据 / 我的经验，希望能在 X 上调整」的结构。**跳过会发生什么**：在没 offer 时硬谈 → 没有筹码；接了 offer 才想谈 → 窗口已过。"
  "**按总包谈，不止 base**：base、奖金、股票 / RSU、签字费、假期、提前 review、搬家补助、签证 sponsorship 等都是可谈筹码。**跳过会发生什么**：只盯 base 一个数字 → 放弃了其他可谈空间，且无法跨 offer 公平比较。"
  "**多 offer 横向决策**：有多个 offer 时，按总包 + 平台 + 发展 + 文化 + 地点 + 风险综合比较（不是只比钱），做决策。**跳过会发生什么**：只比 base 月薪 / 只比单一维度 → 决策失真，可能选错。"
)
declare -a FAILURE_MODES=(
  "**没有市场数据就开谈**：触发原因 = 嫌查数据麻烦 / 不知道去哪查；后果 = 报价没锚，要么贱卖要么离谱出局。怎么避免：先用 levels.fyi / Glassdoor（海外）或招聘平台 + 看准网（国内）定 anchor。"
  "**过早第一个报数字**：触发原因 = 被问就答的本能；后果 = 报低贱卖 / 报高出局。怎么避免：信息不足时把球踢回去问预算区间（但薪资透明地区要变形 —— 给有数据支撑的区间）。"
  "**只比 base 月薪**：触发原因 = base 最直观；后果 = 放弃其他筹码 + 跨 offer 比较失真。怎么避免：按总包谈、按总包比，base 之外都是可谈空间。"
  "**编造竞争性 offer 做杠杆**：触发原因 = 想增加筹码；后果 = 被识破直接出局，行业小、口碑受损。怎么避免：杠杆只用真实的 offer / 薪资 / 技能稀缺性。"
  "**为小涨幅把关系谈僵**：触发原因 = 「能多谈就多谈」的执念；后果 = 入职前就和未来雇主关系紧张。怎么避免：权衡边际收益和关系成本，谈判有度。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-6-walkthrough"
fi
