#!/usr/bin/env bash
# workflow-5.sh — 求职定位与职业叙事流程 SOP walkthrough for 求职 / 面试辅导(求职教练视角 — 求职定位与职业叙事 / 简历与 ATS 优化 / 求职渠道与内推策略 / 职场社交 / 行为面试与专业面试 / 面试心理与表达 / 谈薪与 offer 决策 / 校招与应届生 / 转行求职 / 特殊群体求职 / 求职教练的执业经营 — 涵盖中国大陆求职生态 + 海外英语区求职体系,两套差异极大).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="求职 / 面试辅导(求职教练视角 — 求职定位与职业叙事 / 简历与 ATS 优化 / 求职渠道与内推策略 / 职场社交 / 行为面试与专业面试 / 面试心理与表达 / 谈薪与 offer 决策 / 校招与应届生 / 转行求职 / 特殊群体求职 / 求职教练的执业经营 — 涵盖中国大陆求职生态 + 海外英语区求职体系,两套差异极大)"
WORKFLOW="求职定位与职业叙事流程"

usage() {
  cat <<EOF
workflow-5.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-5.sh             # interactive
  ./workflow-5.sh --dry-run
  ./workflow-5.sh --json
  ./workflow-5.sh --explain
  ./workflow-5.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "求职定位与职业叙事流程" 工作流。

一句话: 把「我想找工作」收敛成「我要找哪一类岗位 + 为什么是我」—— 求职的第一性问题。定位错了，后面简历 / 投递 / 面试全是高效地做错的事。

入门 SOP 共 4 步, 失败模式自检 4 项。

相关心智模型:
  • 定位先于一切执行（定位错了，后面是高效地做错事）: 求职的第一性问题不是「简历怎么写 / 该投哪」，而是「要找哪一类岗位 + 为什么是我」—— 目标不收敛时，改简历、海投、练面试都是在高效地做错的事。
  • 从招聘方 / ATS / 岗位的痛点出发倒推（不是从「我想要什么」出发）: 简历、触达、面试答案的组织原点是「这个岗位 / 招聘经理在解决什么问题」，不是「我想说什么」—— 招聘经理立项前往往已缺人 6-12 个月，他要的是「缓解」。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**自我盘点**：盘点能力 / 经历 / 兴趣 / 价值观 / 约束条件（薪资底线、地点、签证等）—— Bolles 的 Flower Exercise、DYL 的能量 / 心流日志都是这一步的工具。**跳过会发生什么**：跳过自我盘点直接定目标 → 定的是「听起来好」的目标而非「适合且能进」的目标。"
  "**目标收敛**：把「什么都能做」收敛到 1-3 个具体方向（职能 + 行业 + 层级），列目标岗位 / 公司清单。**跳过会发生什么**：目标不收敛 → 简历无法针对、海投、面试讲不出「为什么是这家」。"
  "**卖点提炼**：针对收敛后的目标，提炼「我相对这个岗位的核心卖点」（可迁移技能 + 量化成就 + 差异化）。**跳过会发生什么**：不提炼卖点 → 简历是「职责清单」、面试讲不清「为什么选我」。"
  "**故事线编织**：把零散经历串成一条连贯叙事 —— 「我从哪来、为什么走到这里、为什么这个方向是合理的下一步」。**跳过会发生什么**：经历是散点 → 招聘方看不出逻辑，尤其转行 / 有空窗 / 频繁跳槽的人会被「看不懂」直接刷。"
)
declare -a FAILURE_MODES=(
  "**跳过定位直接改简历 / 海投**：触发原因 = 「定位很虚 / 浪费时间，先动起来再说」；后果 = 高效地做错的事 —— 简历无法针对、海投低转化、面试讲不清动机。怎么避免：把定位当强制前置步骤，目标不收敛不进 W6（简历）。"
  "**定一个忽略约束的「理想目标」**：触发原因 = 不愿面对薪资 / 地点 / 签证等现实约束；后果 = 投到后期才发现走不通，前功尽弃。怎么避免：定位第一步就把约束条件显性化，当硬筛选条件。"
  "**职业叙事 = 编一个完美故事**：触发原因 = 以为「叙事」就是「包装得好看」；后果 = 故事和真实经历脱节，面试一追问就崩、且越过造假红线。怎么避免：叙事是「把真实经历串成有逻辑的线」，不是虚构 —— 逻辑可以重新组织，事实不能编。"
  "**把定位做成「找到天命才能投」的奢侈品**：触发原因 = 完美主义 + 不顾生计压力；后果 = 迟迟不投、生计危机加剧。怎么避免：有生计压力时，「先拿过渡 offer + 继续定位」是合法策略；定位追求「可行动」不追求「完美」。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-5-walkthrough"
fi
