#!/usr/bin/env bash
# workflow-1.sh — 国内校招求职弧线 SOP walkthrough for 求职 / 面试辅导(求职教练视角 — 求职定位与职业叙事 / 简历与 ATS 优化 / 求职渠道与内推策略 / 职场社交 / 行为面试与专业面试 / 面试心理与表达 / 谈薪与 offer 决策 / 校招与应届生 / 转行求职 / 特殊群体求职 / 求职教练的执业经营 — 涵盖中国大陆求职生态 + 海外英语区求职体系,两套差异极大).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="求职 / 面试辅导(求职教练视角 — 求职定位与职业叙事 / 简历与 ATS 优化 / 求职渠道与内推策略 / 职场社交 / 行为面试与专业面试 / 面试心理与表达 / 谈薪与 offer 决策 / 校招与应届生 / 转行求职 / 特殊群体求职 / 求职教练的执业经营 — 涵盖中国大陆求职生态 + 海外英语区求职体系,两套差异极大)"
WORKFLOW="国内校招求职弧线"

usage() {
  cat <<EOF
workflow-1.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-1.sh             # interactive
  ./workflow-1.sh --dry-run
  ./workflow-1.sh --json
  ./workflow-1.sh --explain
  ./workflow-1.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "国内校招求职弧线" 工作流。

一句话: 应届生从「不知道投什么」到「拿到并接受一个 offer」的全过程 —— 国内校招的特征是**工业化时间窗**（春招 / 秋招 / 提前批是硬节点，错过当季就要等下一季甚至失去应届生身份），主通道是「网申 + 笔试 + 多轮面试」而非 networking。

入门 SOP 共 6 步, 失败模式自检 4 项。

相关心智模型:
  • 定位先于一切执行（定位错了，后面是高效地做错事）: 求职的第一性问题不是「简历怎么写 / 该投哪」，而是「要找哪一类岗位 + 为什么是我」—— 目标不收敛时，改简历、海投、练面试都是在高效地做错的事。
  • 从招聘方 / ATS / 岗位的痛点出发倒推（不是从「我想要什么」出发）: 简历、触达、面试答案的组织原点是「这个岗位 / 招聘经理在解决什么问题」，不是「我想说什么」—— 招聘经理立项前往往已缺人 6-12 个月，他要的是「缓解」。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**定位与岗位收敛**：确定目标行业 / 职能 / 城市 / 公司梯队（大厂 / 国企 / 外企 / 中小厂），列一份目标岗位清单。inputs：专业、实习经历、能力盘点；outputs：目标清单。**跳过会发生什么**：海投所有看到的岗位 → 笔面试时间冲突、简历无法针对性、面试讲不出「为什么是这家」，转化率全线崩。"
  "**简历定稿**：做一份校招简历（国内格式：常含照片 / 年龄 / 学校 / 实习 / 项目，一页为主），针对岗位类型微调。**跳过会发生什么**：用一份「万能简历」投所有岗位 → 网申初筛和面试都被「不匹配」刷掉。"
  "**网申 + 内推并行**：在公司官网 / 校招系统提交网申；同时通过牛客内推帖、师兄师姐、宣讲会要内推码（国内内推主要作用是「免笔试 / 简历直达 HR」，不是「保过」）。**跳过会发生什么**：只网申不内推 → 简历淹没在网申池；只等内推不网申 → 没内推渠道的公司全错过。"
  "**笔试准备 + 参加**：技术岗刷题（LeetCode / 牛客题库），非技术岗练行测 / 综合素质题型，研究目标公司历年笔试题型（牛客笔经）。**跳过会发生什么**：国内校招笔试是硬门槛，裸考被刷，连面试机会都没有。"
  "**多轮面试**：群面 / 行为面 / 专业面 / HR 面，逐轮推进。每轮前研究面经（牛客）、准备 STAR 故事。**跳过会发生什么**：不准备直接上 → 行为面讲成流水账、专业面露怯，被刷。"
  "**拿 offer + 决策 + 签三方**：比较手上的 offer（薪资 / 平台 / 城市 / 发展），做决策，签三方协议。**跳过会发生什么**：不比较直接签第一个 → 后悔但三方违约有成本（违约金 + 关系损耗）。"
)
declare -a FAILURE_MODES=(
  "**跳过定位直接海投**：触发原因 = 焦虑 + 「先投了再说」；后果 = 笔面试时间冲突、面试讲不出动机、全线低转化。怎么避免：投递前先花 1-2 周做 W5（定位），把目标收敛到 30-50 家。"
  "**错过提前批 / 把希望压在春招**：触发原因 = 不懂校招时间窗结构（以为「提前批 = 还没准备好不该投」「春招还有机会」）；后果 = 提前批的低风险占坑机会浪费、春招岗位少导致 offer 荒。怎么避免：开学就做一张校招时间表，提前批当练兵 + 占坑，秋招当主战场。"
  "**笔试裸考**：触发原因 = 低估国内校招笔试的硬门槛属性；后果 = 连面试机会都拿不到。怎么避免：技术岗按目标公司高频题刷，非技术岗练行测题型，提前看牛客笔经。"
  "**把「付费内推 / 内推保过」当真**：触发原因 = 焦虑 + 机构营销话术；后果 = 花钱买的「内推」要么无效要么是绕过流程的灰色操作，背调有暴露风险。怎么避免：理解国内内推的真实作用是「免笔试 / 简历直达」不是「保过」，正规内推不收费。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-1-walkthrough"
fi
