#!/usr/bin/env bash
# workflow-7.sh — 转行求职流程 SOP walkthrough for 求职 / 面试辅导(求职教练视角 — 求职定位与职业叙事 / 简历与 ATS 优化 / 求职渠道与内推策略 / 职场社交 / 行为面试与专业面试 / 面试心理与表达 / 谈薪与 offer 决策 / 校招与应届生 / 转行求职 / 特殊群体求职 / 求职教练的执业经营 — 涵盖中国大陆求职生态 + 海外英语区求职体系,两套差异极大).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="求职 / 面试辅导(求职教练视角 — 求职定位与职业叙事 / 简历与 ATS 优化 / 求职渠道与内推策略 / 职场社交 / 行为面试与专业面试 / 面试心理与表达 / 谈薪与 offer 决策 / 校招与应届生 / 转行求职 / 特殊群体求职 / 求职教练的执业经营 — 涵盖中国大陆求职生态 + 海外英语区求职体系,两套差异极大)"
WORKFLOW="转行求职流程"

usage() {
  cat <<EOF
workflow-7.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-7.sh             # interactive
  ./workflow-7.sh --dry-run
  ./workflow-7.sh --json
  ./workflow-7.sh --explain
  ./workflow-7.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "转行求职流程" 工作流。

一句话: 帮一个人从 A 行业 / 职能进入 B —— 转行求职的核心难点不是「能不能做」，是「招聘方看不出你能做」；解法是「可迁移技能 + 转行叙事 + 一条降低风险的进入路径」。这是 W5（定位）的一个高难度特例。

入门 SOP 共 5 步, 失败模式自检 5 项。

相关心智模型:
  • 定位先于一切执行（定位错了，后面是高效地做错事）: 求职的第一性问题不是「简历怎么写 / 该投哪」，而是「要找哪一类岗位 + 为什么是我」—— 目标不收敛时，改简历、海投、练面试都是在高效地做错的事。
  • 从招聘方 / ATS / 岗位的痛点出发倒推（不是从「我想要什么」出发）: 简历、触达、面试答案的组织原点是「这个岗位 / 招聘经理在解决什么问题」，不是「我想说什么」—— 招聘经理立项前往往已缺人 6-12 个月，他要的是「缓解」。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**可迁移技能盘点**：盘点 A 行业 / 职能里「不绑定具体行业」的能力（项目管理、数据分析、沟通、某类工具、某类问题解决），并**用目标行业 B 的语言重新表述**。**跳过会发生什么**：用 A 行业的术语描述自己 → B 行业招聘方「看不懂 / 觉得不相关」，简历直接刷。"
  "**目标 B 的真实要求调研**：调研目标行业 / 岗位真正要什么（硬门槛、加分项、是否有「必须从这里入」的路径），判断转行的现实难度和缺口。**跳过会发生什么**：对 B 一无所知就转 → 撞上隐形硬门槛（如某些岗位的资质 / 经验硬要求），白费力气。"
  "**转行叙事编织**：把「为什么离开 A + 为什么选 B + 为什么我能胜任 B」串成一条让人信服的连贯故事（不是「我厌倦了 A」这种负面叙事，是「我在 A 积累的 X 正好是 B 需要的」）。**跳过会发生什么**：没有叙事 → 招聘方把你当「逃离者 / 不知道自己要什么的人」，而非「有备而来的转行者」。"
  "**进入路径设计**：设计一条降低风险的路径 —— 直接转（缺口小时）/ 过渡岗（先转职能或先转行业，不一次跨两步）/ 补能力（课程 / 项目 / 证书填硬缺口）/ 内部转岗（在现公司先转）/ networking 进入（转行者尤其需要有人「背书 + 引荐」）。**跳过会发生什么**：硬磕「一步到位直接转」→ 跨度太大、屡投屡拒、信心和时间双重消耗。"
  "**执行（进入 W1/W2/W3 对应弧线）**：按目标 locale 的求职弧线执行，但简历 / 面试都围绕「可迁移性 + 转行叙事」组织。"
)
declare -a FAILURE_MODES=(
  "**用原行业语言描述自己**：触发原因 = 没意识到「招聘方看不懂 ≠ 我不行」；后果 = B 行业招聘方判「不相关」直接刷。怎么避免：逐条把可迁移技能「翻译」成目标行业的语言。"
  "**一步到位同时换行业 + 换职能**：触发原因 = 急于彻底转变；后果 = 跨度过大、屡投屡拒。怎么避免：拆成中间步，先换一个维度，用过渡岗做跳板。"
  "**负面转行叙事（「我厌倦了 A」）**：触发原因 = 把转行说成「逃离」；后果 = 招聘方把你当「不知道自己要什么的人」。怎么避免：叙事围绕「A 的积累正好是 B 需要的 + 我想清楚了为什么是 B」。"
  "**只投网申、不做 networking**：触发原因 = 沿用一般求职习惯；后果 = 转行简历在初筛天然吃亏，纸面看不出能做。怎么避免：转行更要靠 networking，有人背书引荐能绕过「纸面看不出」的硬伤。"
  "**对转行成本预期不足**：触发原因 = 「换个赛道就能起飞」的幻想 / 营销话术；后果 = 撞上短期降薪降级的现实后崩盘放弃。怎么避免：教练前置做预期管理 —— 转行通常意味着短期降薪 / 降级 / 时间线更长，这是真实约束。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-7-walkthrough"
fi
