#!/usr/bin/env bash
# workflow-2.sh — 国内社招求职弧线 SOP walkthrough for 求职 / 面试辅导(求职教练视角 — 求职定位与职业叙事 / 简历与 ATS 优化 / 求职渠道与内推策略 / 职场社交 / 行为面试与专业面试 / 面试心理与表达 / 谈薪与 offer 决策 / 校招与应届生 / 转行求职 / 特殊群体求职 / 求职教练的执业经营 — 涵盖中国大陆求职生态 + 海外英语区求职体系,两套差异极大).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="求职 / 面试辅导(求职教练视角 — 求职定位与职业叙事 / 简历与 ATS 优化 / 求职渠道与内推策略 / 职场社交 / 行为面试与专业面试 / 面试心理与表达 / 谈薪与 offer 决策 / 校招与应届生 / 转行求职 / 特殊群体求职 / 求职教练的执业经营 — 涵盖中国大陆求职生态 + 海外英语区求职体系,两套差异极大)"
WORKFLOW="国内社招求职弧线"

usage() {
  cat <<EOF
workflow-2.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-2.sh             # interactive
  ./workflow-2.sh --dry-run
  ./workflow-2.sh --json
  ./workflow-2.sh --explain
  ./workflow-2.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "国内社招求职弧线" 工作流。

一句话: 有经验者从「想换工作」到「拿到 offer 并完成决策」的全过程 —— 国内社招的特征是 **BOSS 直聘聊天式直招**（求职者直接和 HR / 用人老板对话，对话本身就是触达 + 初筛），没有统一时间窗（rolling），背调环节比校招更实。

入门 SOP 共 6 步, 失败模式自检 4 项。

相关心智模型:
  • 定位先于一切执行（定位错了，后面是高效地做错事）: 求职的第一性问题不是「简历怎么写 / 该投哪」，而是「要找哪一类岗位 + 为什么是我」—— 目标不收敛时，改简历、海投、练面试都是在高效地做错的事。
  • 从招聘方 / ATS / 岗位的痛点出发倒推（不是从「我想要什么」出发）: 简历、触达、面试答案的组织原点是「这个岗位 / 招聘经理在解决什么问题」，不是「我想说什么」—— 招聘经理立项前往往已缺人 6-12 个月，他要的是「缓解」。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**定位 + 简历更新**：明确目标岗位 / 薪资区间 / 行业，把简历从「校招版」升级为「社招版」（社招简历重「成果与影响」不重「在校经历」，要量化）。**跳过会发生什么**：拿一份旧简历或目标模糊地投 → 聊天阶段 HR 一问「你想找什么」就露馅，匹配度低。"
  "**平台触达（聊天式）**：在 BOSS 直聘等平台主动「打招呼」，简洁说明匹配点，引导对话；同时可走脉脉弱关系、猎头（中高端岗位）。**跳过会发生什么**：只被动等 HR 来撩 / 只海投不主动开口 → 国内社招主动出击节奏，被动等的命中率低。"
  "**沟通 + 确认岗位真实性**：在聊天中确认 JD 细节、薪资范围、团队情况，筛掉「画大饼 / 不匹配 / 薪资不达标」的岗位。**跳过会发生什么**：不在聊天阶段筛 → 面试了一圈才发现岗位和预期差很远，浪费时间。"
  "**多轮面试**：专业面 + 主管面 + HR 面，逐轮推进；每轮针对性准备。**跳过会发生什么**：不准备 → 讲不清过往成果的「影响」，被刷。"
  "**谈薪**（详见 W7）：拿到口头意向后谈薪，争取合理涨幅。**跳过会发生什么**：直接接受首次报价 → 国内社招薪资有谈判空间，不谈通常拿不到最优。"
  "**背调 + offer 决策**：配合背调（社招背调查上家在职时间 / 职级 / 离职原因，比校招实），做 offer 横向决策，确认无误后走离职流程。**跳过会发生什么**：简历 / 面试有夸大 → 背调暴露，offer 撤回；不做横向决策直接跳 → 可能跳进一个更差的坑。"
)
declare -a FAILURE_MODES=(
  "**逃离式跳槽（动机不清）**：触发原因 = 只想离开现状、没想清去哪；后果 = 跳进一个新的坑，半年后又想走。怎么避免：跳槽前做动机校准 —— 「走了具体能解决什么、不能解决什么」。"
  "**冲动裸辞**：触发原因 = 现岗情绪积压；后果 = 失去「在职」的议价权和心态，越急越谈不好，空窗还要解释。怎么避免：除非现岗不可忍，在职骑驴找马。"
  "**背调翻车**：触发原因 = 简历 / 面试夸大了职级 / 在职时间 / 离职原因；后果 = offer 撤回 + 行业口碑受损。怎么避免：投递前做背调前置体检，简历与真实情况对齐。"
  "**聊天阶段不筛，面到一半才发现不匹配**：触发原因 = 「先面着再说」；后果 = 时间浪费在无效岗位上。怎么避免：在聊天前 3-5 句就确认 JD / 薪资 / 团队，不达标的不进面试。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-2-walkthrough"
fi
