#!/usr/bin/env bash
# workflow-8.sh — 求职教练的接案 / 服务流程 SOP walkthrough for 求职 / 面试辅导(求职教练视角 — 求职定位与职业叙事 / 简历与 ATS 优化 / 求职渠道与内推策略 / 职场社交 / 行为面试与专业面试 / 面试心理与表达 / 谈薪与 offer 决策 / 校招与应届生 / 转行求职 / 特殊群体求职 / 求职教练的执业经营 — 涵盖中国大陆求职生态 + 海外英语区求职体系,两套差异极大).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="求职 / 面试辅导(求职教练视角 — 求职定位与职业叙事 / 简历与 ATS 优化 / 求职渠道与内推策略 / 职场社交 / 行为面试与专业面试 / 面试心理与表达 / 谈薪与 offer 决策 / 校招与应届生 / 转行求职 / 特殊群体求职 / 求职教练的执业经营 — 涵盖中国大陆求职生态 + 海外英语区求职体系,两套差异极大)"
WORKFLOW="求职教练的接案 / 服务流程"

usage() {
  cat <<EOF
workflow-8.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-8.sh             # interactive
  ./workflow-8.sh --dry-run
  ./workflow-8.sh --json
  ./workflow-8.sh --explain
  ./workflow-8.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "求职教练的接案 / 服务流程" 工作流。

一句话: 求职教练接一个客户、把他带到「求职能力提升 + 可控部分做到位」的服务闭环 —— 初诊 → 诊断卡点 → 方案 → 执行陪跑 → 复盘。核心是「诊断对卡点 + 守住能力边界 + 不兜售确定性」。

入门 SOP 共 5 步, 失败模式自检 5 项。

相关心智模型:
  • 定位先于一切执行（定位错了，后面是高效地做错事）: 求职的第一性问题不是「简历怎么写 / 该投哪」，而是「要找哪一类岗位 + 为什么是我」—— 目标不收敛时，改简历、海投、练面试都是在高效地做错的事。
  • 从招聘方 / ATS / 岗位的痛点出发倒推（不是从「我想要什么」出发）: 简历、触达、面试答案的组织原点是「这个岗位 / 招聘经理在解决什么问题」，不是「我想说什么」—— 招聘经理立项前往往已缺人 6-12 个月，他要的是「缓解」。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**初诊（intake）**：了解客户的背景、目标、当前求职状态、卡在哪、之前做过什么、预期是什么、约束条件（时间 / 预算 / 签证 / 生计压力）。**跳过会发生什么**：不做初诊直接「上方案」→ 方案是套餐化的、不对人，客户体验差且无效。"
  "**诊断卡点**：判断客户的问题真正卡在哪一环 —— 用「求职漏斗」视角（投递→初筛→面试→offer，哪一层转化率掉）+ 定位 / 简历 / 渠道 / 面试表现 / 谈薪逐项排查。**跳过会发生什么**：不诊断就「客户说要改简历就改简历」→ 改了简历但真正的问题在定位 / 渠道，白做。"
  "**出方案**：基于诊断给一个有优先级的方案 —— 先解决卡点最重的那一环，明确「这次能解决什么 / 不能解决什么」。**跳过会发生什么**：方案没优先级 / 没边界 → 客户不知道先做什么、对结果预期失真。"
  "**执行陪跑**：按方案陪客户做 —— 改简历、mock interview + debrief、定位对话、谈薪演练等（mock + debrief 是教练 ROI 最高的交付物）。**跳过会发生什么**：只给方案不陪跑 → 客户「知道了但做不到」，方案落不了地。"
  "**复盘 + 边界交接**：阶段性复盘进展，校准预期；明确教练能力边界（自己不精通的专业领域 —— 如某类技术岗深度 —— 是「连接资源」而非「越界硬教」）。**跳过会发生什么**：不复盘 → 客户和教练对「进展」「下一步」没共识；不守边界硬教不懂的领域 → 给错误指导，害了客户。"
)
declare -a FAILURE_MODES=(
  "**跳过诊断，客户说改什么就改什么**：触发原因 = 客户的「自我诊断」很笃定 + 教练怕「不给客户想要的」；后果 = 改了简历但真问题在定位 / 渠道，客户花了钱没效果。怎么避免：先诊断再定方案，用求职漏斗排查真正的卡点。"
  "**把 output 定义成「拿到 offer」/ 做「保 offer」承诺**：触发原因 = 市场压力下想留住客户 / 行业噪音裹挟；后果 = 兜售确定性，做不到时信任崩塌，且滑向黑产边缘。怎么避免：output 定义成「可控部分实质提升 + 预期清醒」，从初诊就讲清边界。"
  "**越界硬教自己不懂的专业领域**：触发原因 = 不想拒客户 / 高估自己；后果 = 给错误的专业指导，害了客户。怎么避免：守能力边界，不精通的领域「连接资源 / 转介」而非硬教。"
  "**靠制造焦虑卖课 / 模糊利益关系**：触发原因 = 焦虑营销是行业常见变现套路；后果 = 短期变现、长期口碑崩，且与「教练站求职者一边」的角色冲突。怎么避免：给真实图景不贩卖焦虑；同时卖内推 / 与机构绑定的，向客户透明这层利益关系。"
  "**不做预期管理，把市场不可控的失败归给客户**：触发原因 = 回避「我的方法也有上限」；后果 = victim-blaming（「你没拿到 offer 是你不够努力」），既不诚实也伤客户。怎么避免：贯穿全程讲清「可控 vs 不可控」的边界，市场周期 / 结构性约束是真实的。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-8-walkthrough"
fi
