#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for SEO 专家.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="SEO 专家"
DIM_COUNT=5

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (5 个):
  9.1 内容质量诊断 (E-E-A-T)
  9.2 技术 SEO 健康度
  9.3 链接质量评估
  9.4 关键词机会评估
  9.5 AI Search 可见度 (GEO, 2024-2026)

背后的心智模型:
  • People-first content > Search engine first content (核心 PASS): Google 长期主线是「为用户写, 不为搜索引擎写」. 套路 6 个月一过期, 真实价值是长期资产.
  • Pillar + Cluster 内容架构 (核心 PASS): Pillar (主题枢纽) + Cluster (长尾分支) 是中型品牌内容 SEO 的标准架构.
  • 链接质量 > 链接数量 (industry-amplified): 10 个 DA 50+ 链接 > 100 个 DA 10 链接. 白帽路径, 不要走 spam.

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "内容质量诊断 (E-E-A-T)"
  "技术 SEO 健康度"
  "链接质量评估"
  "关键词机会评估"
  "AI Search 可见度 (GEO, 2024-2026)"
)
declare -a DIM_QUESTIONS=(
  "Experience / Expertise / Authoritativeness / Trustworthiness 4 维"
  "Crawlability / Indexability / Core Web Vitals / Schema 4 件套"
  "链接 DA / 主题相关性 / Anchor Text 多样性 / Toxic 比例"
  "KD / Search Volume / 当前排名 / 竞品分析"
  "AI Overviews / ChatGPT / Perplexity 引用频率 + 品牌 mention"
)
declare -a DIM_SOURCES=(
  "Google Quality Rater Guidelines + 自家内容 vs 竞品对比"
  "GSC + Screaming Frog + PageSpeed Insights"
  "Ahrefs / SEMrush / Moz 链接报告"
  "Ahrefs / SEMrush + GSC"
  "Otterly.ai / Profound / Peec AI"
)
declare -a DIM_OUTPUT_FORMATS=(
  "4 维各 score (1-10) + 1 句最大瓶颈"
  "4 维各通过率 + 高 / 中 / 低 优先级修复清单"
  "链接质量分 + Disavow 建议 + Outreach 优先级"
  "高 ROI 关键词清单 + 内容方向建议"
  "AI Search 可见度 baseline + 优化建议 (内容结构 / 数据密度 / Schema)"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
