#!/usr/bin/env bash
# general-playbook.sh — 通用 Playbook 决策助手 for 足踝外科.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="足踝外科"
TOPIC="通用 Playbook"

usage() {
  cat <<EOF
general-playbook.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 2 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./general-playbook.sh             # interactive
  ./general-playbook.sh --dry-run   # walk through but no file
  ./general-playbook.sh --json      # JSON to stdout
  ./general-playbook.sh --explain   # show backing playbook rules + mental models
  ./general-playbook.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 通用 Playbook 主题下的 playbook 规则组合成交互树。

基于 2 条规则:
  • 如果 儿童足部问题 (扁平足 / 跟骨骨突炎 等) → 则 按生长发育阶段决策, 不要套成人方案
  • 如果 拇外翻评估 → 则 负重 X 线 + 角度 + 严重度 + 关节炎 + 合并平足 / 跟腱挛缩 全维度决定术式, 不是单看 HVA

相关心智模型:
  • 保守治疗优先于手术 (3-6 月黄金期): 90% 的足踝慢性病变不需要手术, 但很多医生 / 患者直接跳到手术决策, 跳过保守治疗黄金期.
  • 影像学发现 ≠ 临床症状原因 (跟着症状走): MRI 看到的「异常」很多跟患者主诉无关. 影像跟症状对不上时, 跟着症状走, 不是跟着影像走.

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "儿童足部问题 (扁平足 / 跟骨骨突炎 等)"
  "拇外翻评估"
)
declare -a RULE_ACTIONS=(
  "按生长发育阶段决策, 不要套成人方案"
  "负重 X 线 + 角度 + 严重度 + 关节炎 + 合并平足 / 跟腱挛缩 全维度决定术式, 不是单看 HVA"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "general-playbook-decision"
fi
