#!/usr/bin/env bash
# topic-1.sh — 客户 决策助手 for 保险经纪人 / 保险代理人.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="保险经纪人 / 保险代理人"
TOPIC="客户"

usage() {
  cat <<EOF
topic-1.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 5 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-1.sh             # interactive
  ./topic-1.sh --dry-run   # walk through but no file
  ./topic-1.sh --json      # JSON to stdout
  ./topic-1.sh --explain   # show backing playbook rules + mental models
  ./topic-1.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 客户 主题下的 playbook 规则组合成交互树。

基于 5 条规则:
  • 如果 客户咨询新产品 → 则 不要直接推荐
  • 如果 客户老保单遇到利率切换决策 → 则 走 W4 4 路径决策树
  • 如果 客户健康告知有问题项 → 则 (甲状腺结节 / 息肉 / 乙肝携带 / 高血压等), 优先走人工核保 (而非智能核保), 多个保司同步预核 (用 T0
  • 如果 客户想要直接对比多个产品 → 则 用深蓝保金榜 (T02-S003) 或大童保险家产品库 (T02-S001) 出 3-5 款同价位带对比, 让客户参与决
  • 如果 客户出险走理赔 → 则 (重疾 / 意外 / 身故), 走 W5 5 步流程, 关键是: 24 小时内通知 + 关键档案早保存 + 拒赔 / 部

相关心智模型:
  • 监管驱动产品形态 (industry-amplified): 「想知道未来 12 个月卖什么 + 客户教育用什么口径, 先看 NFRA 最近 90 天发了什么文 — 中国保险产品形态 80% 由监管定义而非市场自发演化」
  • 服务即销售 (转介绍循环 = 收入护城河): 「成交后服务比成交前的销售更重要 — 客户不是在买产品, 是在买长期咨询关系; 续期 + 转介绍占资深经纪人 60-80% 收入, 一次性高佣金的获客模式撑不过 5 年」

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "客户咨询新产品"
  "客户老保单遇到利率切换决策"
  "客户健康告知有问题项"
  "客户想要直接对比多个产品"
  "客户出险走理赔"
)
declare -a RULE_ACTIONS=(
  "不要直接推荐"
  "走 W4 4 路径决策树"
  "(甲状腺结节 / 息肉 / 乙肝携带 / 高血压等), 优先走人工核保 (而非智能核保), 多个保司同步预核 (用 T02-S001 / T02-S002 工具), 比较结论"
  "用深蓝保金榜 (T02-S003) 或大童保险家产品库 (T02-S001) 出 3-5 款同价位带对比, 让客户参与决策, 不是 \"我说哪个好就买哪个\""
  "(重疾 / 意外 / 身故), 走 W5 5 步流程, 关键是: 24 小时内通知 + 关键档案早保存 + 拒赔 / 部分赔时先内部协调再走法律"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-1-decision"
fi
