#!/usr/bin/env bash
# 0-0-1.sh — 从 0 启动一个商家的私域（0→1 冷启动） SOP walkthrough for 微信私域运营 (企微 + 个人号 + 公众号 + 视频号 + 小程序 + 朋友圈 + 社群 全链路 — 引流 / 沉淀 / 触达 / 转化 / 复购 / 裂变).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="微信私域运营 (企微 + 个人号 + 公众号 + 视频号 + 小程序 + 朋友圈 + 社群 全链路 — 引流 / 沉淀 / 触达 / 转化 / 复购 / 裂变)"
WORKFLOW="从 0 启动一个商家的私域（0→1 冷启动）"

usage() {
  cat <<EOF
0-0-1.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./0-0-1.sh             # interactive
  ./0-0-1.sh --dry-run
  ./0-0-1.sh --json
  ./0-0-1.sh --explain
  ./0-0-1.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "从 0 启动一个商家的私域（0→1 冷启动）" 工作流。

一句话: 一个从没做过私域的商家，从「只有公域流量 / 门店客流 / 一堆散落微信好友」状态，到「有一个能跑通引流→沉淀→触达→首次转化的最小私域闭环」。

入门 SOP 共 7 步, 失败模式自检 4 项。

相关心智模型:
  • 公私二分 / 流量自主权（mental model）: 私域人看一切流量的底层镜片是「这部分流量是租来的还是自己的」——租来的（公域）用一次付一次、平台控分发，自己的（私域）可反复免费触达；近年这对二分从「对立」演化为「全域协同」，但「自主权」这条轴没变。
  • 流量池 / 蓄水养鱼（mental model）: 私域人把流量当成「要蓄进池子、反复经营」的对象而非「这次能转化多少」的一次性曝光——但「建了群 / 加了好友」只是蓄了水，**没有运营动作的池是死水**；价值在「蓄水—养鱼—捕鱼」的循环，不在池子大小

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**定目标 + 选品类适配性**：先算「私域 GMV = 用户池规模 × 转化率 × 复购率 × 客单价」这条公式哪一项是你的杠杆；判断品类是否适合私域（高复购 / 高客单 / 决策链长的更适合）。who: 老板 / 操盘手。"
  "**搭账号体系**：注册 / 启用企业微信主体，配齐「企微 + 视频号 + 小程序」基础三件套，设客服 / 导购的企微号与人设。(evidence: [T03-S002])"
  "**建引流路径（公转私入口）**：在企微后台建渠道活码，投放到公众号、电商包裹卡、线下门店物料、短视频主页等至少 1 个渠道（详见 W2）。(evidence: [T03-S002], [T03-S011])"
  "**配 1v1 承接 SOP**：写好加好友自动欢迎语 + 首 7 日触达节奏，挂进 SCRM（详见 W3）。"
  "**铺朋友圈底子**：定人设，排第一周的朋友圈内容表并开始发（详见 W5）。"
  "**跑第一次转化**：用一次群内秒杀 / 1v1 推荐 / 朋友圈福利做首批成交，验证闭环跑得通。"
  "**复盘**：看漏斗每一环的转化率，定位最漏的一环，决定下一轮迭代重点。"
)
declare -a FAILURE_MODES=(
  "**品类不适配硬上**: 触发原因 = 跟风「人人都要做私域」。怎么避免 = 启动前用 GMV 公式 + 复购率自检，低复购低客单品类先别投私域人力。"
  "**用个人号起盘**: 触发原因 = 觉得个人号「免费、轻」。怎么避免 = 直接上企微，个人号 2023-2025 自动化封号 + 客户不可继承，是已被行业判死的过时打法。"
  "**CLI 化暗示 (v0.6+)**: Build the whole stack（企微+视频号+小程序+公众号+社群）at once in week 1, end up with five half-built channels and no validated conversion loop — wastes 1-2 months. 应改为先跑「企微 1v1 + 朋友圈」两件套验证。"
  "**CLI 化暗示 (v0.6+)**: Copy a 裂变/引流 playbook that's 6+ months old without re-checking WeChat's current 红线 — risk account ban on day one."
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "0-0-1-walkthrough"
fi
