#!/usr/bin/env bash
# 1v1-sop-sop.sh — 1v1 触达 SOP：加好友后的标准化私聊触达（核心 SOP） SOP walkthrough for 微信私域运营 (企微 + 个人号 + 公众号 + 视频号 + 小程序 + 朋友圈 + 社群 全链路 — 引流 / 沉淀 / 触达 / 转化 / 复购 / 裂变).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="微信私域运营 (企微 + 个人号 + 公众号 + 视频号 + 小程序 + 朋友圈 + 社群 全链路 — 引流 / 沉淀 / 触达 / 转化 / 复购 / 裂变)"
WORKFLOW="1v1 触达 SOP：加好友后的标准化私聊触达（核心 SOP）"

usage() {
  cat <<EOF
1v1-sop-sop.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./1v1-sop-sop.sh             # interactive
  ./1v1-sop-sop.sh --dry-run
  ./1v1-sop-sop.sh --json
  ./1v1-sop-sop.sh --explain
  ./1v1-sop-sop.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "1v1 触达 SOP：加好友后的标准化私聊触达（核心 SOP）" 工作流。

一句话: 用户加企微好友后，从「一个陌生新好友」到「被标准化话术 + 节奏私聊触达、完成首次信任建立或首单转化」，让新手客服 / 导购也能达到及格线。

入门 SOP 共 6 步, 失败模式自检 4 项。

相关心智模型:
  • 公私二分 / 流量自主权（mental model）: 私域人看一切流量的底层镜片是「这部分流量是租来的还是自己的」——租来的（公域）用一次付一次、平台控分发，自己的（私域）可反复免费触达；近年这对二分从「对立」演化为「全域协同」，但「自主权」这条轴没变。
  • 流量池 / 蓄水养鱼（mental model）: 私域人把流量当成「要蓄进池子、反复经营」的对象而非「这次能转化多少」的一次性曝光——但「建了群 / 加了好友」只是蓄了水，**没有运营动作的池是死水**；价值在「蓄水—养鱼—捕鱼」的循环，不在池子大小

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**客户分阶段**：把客户按生命周期切成关键阶段——典型如「破冰 → 培育 → 产品介绍/促单 → 售后」（不同行业阶段数不同，如医美常分 4 阶段）。who: 操盘手设计、客服执行。(evidence: [T03-S014])"
  "**写首次欢迎语**：加好友瞬间自动发，做自我介绍 + 兑现钩子 + 一句轻提问引导回复。"
  "**配 7 日触达节奏**：为「破冰 / 培育」阶段排好逐日触达内容——如「加好友第 1 天：你好，昨天介绍的服务你考虑得怎么样了？」每天一个动作，内容是「价值 + 轻引导」而非硬广。(evidence: [T03-S014], [T03-S008])"
  "**挂进 SCRM 做半自动化**：把 SOP 任务挂进 SCRM，按客户标签 / 进入时间自动提醒客服「今天该对谁发什么」，客服确认后发出（不是全自动群发）。(evidence: [T03-S014])"
  "**按回复打标 + 分层**：根据用户在触达中的回应（有无回复 / 问了什么 / 是否下单）打标签，把人分流到「已转化 / 待培育 / 沉睡」不同池子。(evidence: [T03-S004])"
  "**促单话术**：对「培育」到位的用户用成交话术（一个常见公式：戳痛点 → 给方案 → 限时理由 → 临门一脚）推首单。(evidence: [T03-S012])"
)
declare -a FAILURE_MODES=(
  "**SOP 僵化成骚扰式群发**: 触发原因 = 把 SOP 理解成「全员同一套话定时群发」。怎么避免 = SOP 只定框架和下限，每条话术留个性化变量，并严控触达频次。"
  "**不分层、热客户被养凉**: 触发原因 = 对所有新好友无差别走 7 日慢节奏。怎么避免 = 加好友首次互动就做轻分层，高意向直接进促单。"
  "**CLI 化暗示 (v0.6+)**: Run the same 7-day script for every new contact regardless of intent — high-intent buyers go cold while you \"nurture\" them. 高意向用户应跳过慢节奏直接促单。"
  "**CLI 化暗示 (v0.6+)**: Send \"one more message, something will land\" daily without frequency control — trigger user mute/delete, the touchpoint dies permanently."
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "1v1-sop-sop-walkthrough"
fi
