#!/usr/bin/env bash
# sop.sh — 公转私漏斗：把公域流量承接进私域（核心 SOP） SOP walkthrough for 微信私域运营 (企微 + 个人号 + 公众号 + 视频号 + 小程序 + 朋友圈 + 社群 全链路 — 引流 / 沉淀 / 触达 / 转化 / 复购 / 裂变).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="微信私域运营 (企微 + 个人号 + 公众号 + 视频号 + 小程序 + 朋友圈 + 社群 全链路 — 引流 / 沉淀 / 触达 / 转化 / 复购 / 裂变)"
WORKFLOW="公转私漏斗：把公域流量承接进私域（核心 SOP）"

usage() {
  cat <<EOF
sop.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./sop.sh             # interactive
  ./sop.sh --dry-run
  ./sop.sh --json
  ./sop.sh --explain
  ./sop.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "公转私漏斗：把公域流量承接进私域（核心 SOP）" 工作流。

一句话: 把散落在公域（抖音 / 小红书 / 视频号 / 公众号 / 电商订单 / 线下门店）的流量，从「平台上用一次付一次的曝光」转化为「沉淀进企微、可反复免费触达的私域用户」。

入门 SOP 共 6 步, 失败模式自检 4 项。

相关心智模型:
  • 公私二分 / 流量自主权（mental model）: 私域人看一切流量的底层镜片是「这部分流量是租来的还是自己的」——租来的（公域）用一次付一次、平台控分发，自己的（私域）可反复免费触达；近年这对二分从「对立」演化为「全域协同」，但「自主权」这条轴没变。
  • 流量池 / 蓄水养鱼（mental model）: 私域人把流量当成「要蓄进池子、反复经营」的对象而非「这次能转化多少」的一次性曝光——但「建了群 / 加了好友」只是蓄了水，**没有运营动作的池是死水**；价值在「蓄水—养鱼—捕鱼」的循环，不在池子大小

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**设计引流钩子**：用「用户想要 + 与产品强相关」的福利做诱饵（试用装 / 资料包 / 优惠券 / 专属服务），并预先核算单个钩子成本。who: 操盘手。"
  "**建承接入口（活码）**：在企微后台建渠道活码——不同渠道用不同活码，便于后续归因；活码可设「免验证自动通过」。(evidence: [T03-S002])"
  "**铺渠道触点**：把活码 / 引导话术铺到公域各触点——公众号文章内嵌、电商包裹卡、短视频主页与评论区、直播间口播、线下门店物料、导购话术。(evidence: [T03-S002], [T03-S011])"
  "**承接（加好友瞬间）**：用户加企微的第一时间触发欢迎语，把「钩子」兑现，并引导下一步动作（进群 / 领券 / 看产品）。"
  "**打标签**：按来源渠道 + 用户行为给新用户打标（来源标签是后续分层和归因的基础）。(evidence: [T03-S004])"
  "**统计与迭代**：看各渠道「曝光→加粉→留存」转化率，砍掉成本过高的渠道，加码跑得通的。"
)
declare -a FAILURE_MODES=(
  "**只重引流不重承接**: 触发原因 = 把 KPI 定成「加粉量」。怎么避免 = KPI 改为「加粉后 7 日留存数」，承接 SOP 与引流同等重视（04-canon「公转私」概念的常见误用条目）。"
  "**用大额通用券做钩子**: 触发原因 = 大额券加粉数据好看。怎么避免 = 用产品强相关的轻钩子，宁可加粉慢，不要羊毛党稀释用户质量。"
  "**CLI 化暗示 (v0.6+)**: Use one shared QR code for all channels, then have no idea which channel actually works — every channel decision becomes a guess. 必须分渠道活码。"
  "**CLI 化暗示 (v0.6+)**: Optimize for 加粉量 as the KPI, attract coupon-hunters, watch private-domain conversion stay near zero — re-define KPI as 7-day retention."
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "sop-walkthrough"
fi
