#!/usr/bin/env bash
# general-playbook.sh — 通用 Playbook 决策助手 for 内容创作者经济(Substack / Beehiiv / 公众号 / 知识星球 / 小报童 / Patreon — newsletter 写作 + 订阅制变现 + 受众沉淀 + 个人 IP).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="内容创作者经济(Substack / Beehiiv / 公众号 / 知识星球 / 小报童 / Patreon — newsletter 写作 + 订阅制变现 + 受众沉淀 + 个人 IP)"
TOPIC="通用 Playbook"

usage() {
  cat <<EOF
general-playbook.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 2 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./general-playbook.sh             # interactive
  ./general-playbook.sh --dry-run   # walk through but no file
  ./general-playbook.sh --json      # JSON to stdout
  ./general-playbook.sh --explain   # show backing playbook rules + mental models
  ./general-playbook.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 通用 Playbook 主题下的 playbook 规则组合成交互树。

基于 2 条规则:
  • 如果 一个创作者问「写什么」或增长在几百订阅停滞 → 则 先回到 niche — 把定位收窄到「一句话能讲清、且绑定本人不可替代经验」,而不是追热点或定宽类目(「科技」「商业」不
  • 如果 遇到「XX 月入 N 万,我能不能复制」 → 则 先问分布(中位数多少)、问样本(失败者在哪)、问口径(自报还是审计),再回答 — 不照搬成功叙事

相关心智模型:
  • 平台是聚合者,创作者是租户 — 资产要握在自己手里: newsletter / 创作者经济里,平台(Substack / 公众号)靠控制需求与分发赢,创作者在平台上是租户;真正的资产是「能带走的 email 列表 + 自有域名(海外)/ 私域回流(国内)
  • 「先免费建信任、再变现」的耐心模型: 这一行的资深人默认「受众信任 / 受众深度」是前置资产,变现是它的函数 — 顺序不能反:先把价值无偿给出去、把漏斗顶部做够宽,再谈收费 / 接广告 / 卖课。

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "一个创作者问「写什么」或增长在几百订阅停滞"
  "遇到「XX 月入 N 万,我能不能复制」"
)
declare -a RULE_ACTIONS=(
  "先回到 niche — 把定位收窄到「一句话能讲清、且绑定本人不可替代经验」,而不是追热点或定宽类目(「科技」「商业」不是 niche)"
  "先问分布(中位数多少)、问样本(失败者在哪)、问口径(自报还是审计),再回答 — 不照搬成功叙事"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "general-playbook-decision"
fi
