#!/usr/bin/env bash
# 0-100-1k-10k.sh — 海外独立创作者全生命周期：0 → 100 → 1k → 10k → 全职收入 SOP walkthrough for 内容创作者经济(Substack / Beehiiv / 公众号 / 知识星球 / 小报童 / Patreon — newsletter 写作 + 订阅制变现 + 受众沉淀 + 个人 IP).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="内容创作者经济(Substack / Beehiiv / 公众号 / 知识星球 / 小报童 / Patreon — newsletter 写作 + 订阅制变现 + 受众沉淀 + 个人 IP)"
WORKFLOW="海外独立创作者全生命周期：0 → 100 → 1k → 10k → 全职收入"

usage() {
  cat <<EOF
0-100-1k-10k.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./0-100-1k-10k.sh             # interactive
  ./0-100-1k-10k.sh --dry-run
  ./0-100-1k-10k.sh --json
  ./0-100-1k-10k.sh --explain
  ./0-100-1k-10k.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "海外独立创作者全生命周期：0 → 100 → 1k → 10k → 全职收入" 工作流。

一句话: 一个海外独立创作者从「零受众、零订阅」一路走到「newsletter 收入能替代工资」的完整路径。这不是单个 workflow，是一条**分 5 阶段、每阶段有过关条件**的 pipeline——多数人卡在某一阶段，不是「步骤没做」而是「上一阶段地基没打牢」。

入门 SOP 共 28 步, 失败模式自检 5 项。

相关心智模型:
  • 平台是聚合者,创作者是租户 — 资产要握在自己手里: newsletter / 创作者经济里,平台(Substack / 公众号)靠控制需求与分发赢,创作者在平台上是租户;真正的资产是「能带走的 email 列表 + 自有域名(海外)/ 私域回流(国内)
  • 「先免费建信任、再变现」的耐心模型: 这一行的资深人默认「受众信任 / 受众深度」是前置资产,变现是它的函数 — 顺序不能反:先把价值无偿给出去、把漏斗顶部做够宽,再谈收费 / 接广告 / 卖课。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**选 niche + 定位**：用子流程 #3 锁定一个足够窄、与自己不可替代经验绑定的 niche（不是「科技」是「给 B2B SaaS PM 的增长拆解」）。"
  "**选平台 + 建站**：locale=global 默认 Substack 起步（免费、自带 Notes/Recommendations 发现网络）；同步绑一个自有域名（抗平台风险，见 #7）。"
  "**定可持续节奏**：选「1 个格式、1 个长度、1 周 1 次」的最低可维持节奏，写进 about 页作为对读者的契约。"
  "**写 + 发头 5-10 篇**：先攒一点存货证明「这个 newsletter 长什么样」，再开始公开拉人。"
  "**榨干一度人脉**：把 newsletter URL 放进 email 签名、社媒 bio、个人站；在 X / LinkedIn 公开宣布开新刊，逐个私信朋友 / 同事 / 旧同行请求订阅。"
  "**过关条件**：~100 订阅 + 至少连续 6-8 周没断更。**头 100 不来自内容，来自关系**——这是阶段 0 的本质。"
  "**守住节奏 + 提质**：这一阶段唯一不能妥协的是「按时发 + 每篇值得读」，复利来自坚持。"
  "**开站内发现引擎**：打开 Substack Recommendations，主动给同量级 / 略大的 newsletter 互荐；每周在 Notes 发 3-5 条短内容（站内主要发现入口）。"
  "**做 newsletter swap**：找 2-3 个同 niche、同量级的刊互推一次。"
  "**启动 Hub-and-Spoke 分发**（子流程 #5）：每篇 newsletter 拆成 4-6 条 X / LinkedIn 帖子，每周至少 1 条高质量长帖。"
  "**盯 3 个数**：open rate、订阅净增、退订率——找出「哪类选题带订阅」并加权。"
  "**过关条件**：~1k 订阅 + open rate 稳定（健康区间常见 40-50%+）+ 能说清「我的读者是谁、为什么订」。"
  "**叠加增长策略**：beehiiv/Morning Brew 式打法——把 10+ 个小增长动作（swap、referral、社媒、客座稿、SEO、合作署名）**同时常态化跑几个月**，单个都不惊艳，叠起来才有复利。"
  "**上 referral program**：老读者拉新换奖励（独家指南 / 周边 / 升级权益），平均能拉动约 17% 订阅增长。"
  "**做 collaboration / 客座**：和有细分专长的 creator 共同署名，文章可在对方刊转发——Aakash Gupta 近 10 篇里 4 篇是合作稿。"
  "**造「可分享 / top-of-funnel」内容**：偶尔写破圈大选题或「公司内部会传阅的指南」，把流量引回 niche 主线。"
  "**(可选) 上付费获客**：beehiiv Boosts / 付费推荐，约 \$1.5-2 / 订阅——有预算 + 单位经济算得过来才上。"
  "**过关条件**：~10k 订阅 + 至少 1 条变现渠道已被验证（哪怕收入还小）。"
  "**选变现路径**：按 niche 和受众属性，在订阅制（#6）/ 赞助（#4）/ 课程漏斗（intake 流派 C）里选一条主线——四大流派对同一问题答案不同，不存在通用解。"
  "**跑对应子流程**：subscription-first → 跑 #6 going-paid 流程；ad-supported → 跑 #4 赞助销售流程；course-from-newsletter → newsletter 当漏斗，下游建产品矩阵。"
  "**建多形态飞轮**（近期主流）：newsletter + podcast + 赞助 + coaching/课程 组合，单一 newsletter 正让位于「media company」形态。"
  "**公开收入 / build-in-public（可选）**：逐月公开收入结构本身成为增长杠杆（Aakash Gupta 路径），但要承受幸存者偏差争议。"
  "**过关条件**：单月收入达到「不靠工资也能活」的下限。"
  "**稳住飞轮**：把已验证的增长 + 变现动作流程化，能交给协作者 / 外包。"
  "**多平台分散风险**：自有域名 + email 列表为核心资产，平台只作分发渠道之一（#7）。"
  "**扩团队 / 扩品类**：Lenny / Aakash 路径——加 vertical、加人，从「一个人写」变「媒体公司」。"
  "**延伸个人 IP**：演讲 / 顾问 / 出书 / 投资作为收入第二曲线（与国内路径 #2 在此收敛）。"
  "**过关条件**：收入稳定 + 不依赖单一平台 + 单点故障（本人病一周）不致命。"
)
declare -a FAILURE_MODES=(
  "**niche 定太宽**：选「写科技」而非「给早期 SaaS 创始人的增长拆解」——增长在几百订阅停滞，因为读者说不清「订了能持续得到什么」。避免：用 #3 逼出一句话能讲清的窄 niche。"
  "**节奏崩盘**：开局定日更，3-4 周后断更，读者预期破裂前功尽弃。避免：按「最坏状态下还能维持」的频率定节奏（多数人是周更或双周更）。"
  "**太早全面收费 / 太早接广告**：受众信任和规模没到就把漏斗顶部收窄，转化是空的。避免：阶段 1-2 先免费建信任（参照 Lenny 免费写约 9 个月），到阶段 3 再变现。"
  "**All-in 单一平台、把平台关注数当资产**：平台一次政策 / 算法变动可让头部腰斩。避免：从第一天就建自有域名 + 把 email 列表导出权当核心资产。"
  "**平均用力试遍所有增长渠道**：每个渠道都浅尝、都没做透。避免：先 2-3 周 A/B 找出对自己 niche 有效的 2-3 个，再集中投入。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "0-100-1k-10k-walkthrough"
fi
