#!/usr/bin/env bash
# hub-and-spoke.sh — 写作产出 + Hub-and-Spoke 分发（内容生产与多平台触达） SOP walkthrough for 内容创作者经济(Substack / Beehiiv / 公众号 / 知识星球 / 小报童 / Patreon — newsletter 写作 + 订阅制变现 + 受众沉淀 + 个人 IP).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="内容创作者经济(Substack / Beehiiv / 公众号 / 知识星球 / 小报童 / Patreon — newsletter 写作 + 订阅制变现 + 受众沉淀 + 个人 IP)"
WORKFLOW="写作产出 + Hub-and-Spoke 分发（内容生产与多平台触达）"

usage() {
  cat <<EOF
hub-and-spoke.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./hub-and-spoke.sh             # interactive
  ./hub-and-spoke.sh --dry-run
  ./hub-and-spoke.sh --json
  ./hub-and-spoke.sh --explain
  ./hub-and-spoke.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "写作产出 + Hub-and-Spoke 分发（内容生产与多平台触达）" 工作流。

一句话: 从「写完一篇 newsletter」到「这一篇内容被高效切成多平台 Spoke、最大化触达并反哺订阅」。intake 强调「写作只占 30%、分发占 30%」——这个 workflow 管的就是产出 + 分发那 60%。

入门 SOP 共 5 步, 失败模式自检 4 项。

相关心智模型:
  • 平台是聚合者,创作者是租户 — 资产要握在自己手里: newsletter / 创作者经济里,平台(Substack / 公众号)靠控制需求与分发赢,创作者在平台上是租户;真正的资产是「能带走的 email 列表 + 自有域名(海外)/ 私域回流(国内)
  • 「先免费建信任、再变现」的耐心模型: 这一行的资深人默认「受众信任 / 受众深度」是前置资产,变现是它的函数 — 顺序不能反:先把价值无偿给出去、把漏斗顶部做够宽,再谈收费 / 接广告 / 卖课。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**守 Hub 节奏**：按 #1/#2 定的可持续节奏产出 newsletter 正文（Hub），这是一切的源头。"
  "**拆 Spoke**：每篇 newsletter 抽 4-6 个关键 takeaway，改写成 X thread / LinkedIn 帖 / Notes——**按平台改写**，不是机械复制同一段文字。"
  "**错峰发布**：白天写深度长文，碎片时间做 repurposing 和社媒分发（Aakash 的明确分工）。"
  "**多稿并行**：同时推进多篇 newsletter 草稿，降低「这周没灵感」的断更风险（Aakash / Lenny 都用这个工作法）。"
  "**Spoke 引流回 Hub**：每条社媒帖收尾导向「订阅 newsletter 看完整版」,形成「Spoke 获客 → Hub 沉淀」闭环。"
)
declare -a FAILURE_MODES=(
  "**机械搬运同一段文字到各平台**:不按平台改写,触达转化双差。避免:每个 Spoke 按平台调性重写。"
  "**社媒涨粉不回流**:Spoke 不导向订阅,Hub 不增长。避免:每条 Spoke 收尾引流回 newsletter。"
  "**单线程写作**:一周卡壳就断更。避免:常态保持 2-3 篇草稿在管线里。"
  "**把 AI 当正文作者**:用 AI 写 Hub 正文,做成可被商品化的通用内容。避免:AI 只进 repurposing / 草稿环节,Hub 的判断和不可替代视角靠人。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "hub-and-spoke-walkthrough"
fi
