#!/usr/bin/env bash
# niche.sh — Niche 选择与定位（选题方向锁定） SOP walkthrough for 内容创作者经济(Substack / Beehiiv / 公众号 / 知识星球 / 小报童 / Patreon — newsletter 写作 + 订阅制变现 + 受众沉淀 + 个人 IP).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="内容创作者经济(Substack / Beehiiv / 公众号 / 知识星球 / 小报童 / Patreon — newsletter 写作 + 订阅制变现 + 受众沉淀 + 个人 IP)"
WORKFLOW="Niche 选择与定位（选题方向锁定）"

usage() {
  cat <<EOF
niche.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./niche.sh             # interactive
  ./niche.sh --dry-run
  ./niche.sh --json
  ./niche.sh --explain
  ./niche.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "Niche 选择与定位（选题方向锁定）" 工作流。

一句话: 从「我想写点东西」到「一句话能讲清、足够窄、与本人不可替代经验绑定的 niche 定位」。这是全生命周期 #1/#2 阶段 0 的第一步，也是 intake 认定的「成败第一变量」。

入门 SOP 共 5 步, 失败模式自检 3 项。

相关心智模型:
  • 平台是聚合者,创作者是租户 — 资产要握在自己手里: newsletter / 创作者经济里,平台(Substack / 公众号)靠控制需求与分发赢,创作者在平台上是租户;真正的资产是「能带走的 email 列表 + 自有域名(海外)/ 私域回流(国内)
  • 「先免费建信任、再变现」的耐心模型: 这一行的资深人默认「受众信任 / 受众深度」是前置资产,变现是它的函数 — 顺序不能反:先把价值无偿给出去、把漏斗顶部做够宽,再谈收费 / 接广告 / 卖课。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**列「不可替代经验」清单**：写下自己真正有别人没有的经历 / 专长 / 视角（Aakash 称之为「personal monopoly」——他用 B2B+B2C 双重产品经验定位）。"
  "**交叉「我能持续写」×「有人愿意读」**：在清单里找既能写一年不枯竭、又有明确受众的交集。"
  "**收窄到「一句话」**：把宽类目（「科技」「职场」）逼成具体到能一句话讲清的 niche——窄不是限制，是增长前提（niche newsletter 增长比泛类目快约 27%）。"
  "**写理想读者画像**：具体到「这个人是谁、卡在什么问题上、订了我能持续得到什么」。"
  "**测 10-20 个选题**：能列出 10-20 个具体选题且不重复，niche 才站得住；列不出说明定太窄或定错。"
)
declare -a FAILURE_MODES=(
  "**niche 定太宽**：选「写科技」——读者说不清「订了能得到什么」。避免：逼到一句话能讲清。"
  "**追热点而非追不可替代性**：每篇换主题蹭流量，做成可替代内容。避免：从「不可替代经验」清单出发。"
  "**开局拍死、不再校准**：把第一版 niche 假设当真理。避免：发布后用数据滚动收窄。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "niche-walkthrough"
fi
