#!/usr/bin/env bash
# general-playbook.sh — 通用 Playbook 决策助手 for 抖音直播带货 (商家 / 主播 / 直播间运营 + 千川 / 巨量引擎广告投放 + 选品 + 流量场承接 + 合规).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="抖音直播带货 (商家 / 主播 / 直播间运营 + 千川 / 巨量引擎广告投放 + 选品 + 流量场承接 + 合规)"
TOPIC="通用 Playbook"

usage() {
  cat <<EOF
general-playbook.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 9 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./general-playbook.sh             # interactive
  ./general-playbook.sh --dry-run   # walk through but no file
  ./general-playbook.sh --json      # JSON to stdout
  ./general-playbook.sh --explain   # show backing playbook rules + mental models
  ./general-playbook.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 通用 Playbook 主题下的 playbook 规则组合成交互树。

基于 9 条规则:
  • 如果 「加了流量但 GMV / 转化不涨」 → 则 先查承接 (停留时长 / UV 价值 / 品组 / 话术)，不要继续加投千川
  • 如果 一个直播间长期起不来 → 则 先归因到选品 (货)，其次才是主播 (人) 和场
  • 如果 是新账号 / 新千川计划 → 则 学习期 (积累约 20-50 个转化前) 锁死计划不动、容忍数据难看，给算法学习时间
  • 如果 有人问「ROI 是不是越高越好」 → 则 回答不是；目标 ROI 设为「保本 ROI × 1.2」左右、能放量即可，不要拉到不敢花钱的程度
  • 如果 要选投放工具 → 则 ：直播间精细成交用千川、不用 DOU+ (DOU+ 是弱内容加热)；冷启动轻量起步用小店随心推 (单场预算约 300-5
  • 如果 要选品 → 则 先按自己账号的实时标签和历史成交人群选，不要因为某品在别人直播间卖爆就上
  • 如果 商家问「该做什么 / 怎么扩张」 → 则 先定位 ta 在 0→1 / 1→10 / 10→100 哪个阶段，按阶段给单一重点 (0→1 只追账号标签精准、不追 
  • 如果 0→1 还没跑通就想开矩阵号 → 则 先把一个号跑到稳定月销、验证 SOP 可复制，再做有明确分工的矩阵；不要在 0→1 阶段开第二个号
  • 如果 用户问任何「怎么做」 → 则 先用监管红线过一遍 (绝对化用语 / 退货率 / AI 数字人标识 / 资质公示 / 主播法律身份)，再谈运营；遇到「刷

相关心智模型:
  • 算法生意：直播间是做给算法看的，不是做给用户看的: 抖音直播带货的本质是「向推荐算法证明这个直播间值得被推流」——理解算法如何用停留 / 转化 / GPM 这组指标分配免费流量，比话术技巧更底层；流量是非线性「大爆发」的，核心变量是流量 × 选品。
  • 承接 > 引流：流量是放大器不是发动机: 直播间能不能做起来，发动机是「承接能力」(UV 价值 / 停留时长 / GPM / 品组 / 话术)，流量 (自然 + 投流) 只是把这台发动机的输出放大——承接是负数时，加流量等于加速亏钱。

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "「加了流量但 GMV / 转化不涨」"
  "一个直播间长期起不来"
  "是新账号 / 新千川计划"
  "有人问「ROI 是不是越高越好」"
  "要选投放工具"
  "要选品"
  "商家问「该做什么 / 怎么扩张」"
  "0→1 还没跑通就想开矩阵号"
  "用户问任何「怎么做」"
)
declare -a RULE_ACTIONS=(
  "先查承接 (停留时长 / UV 价值 / 品组 / 话术)，不要继续加投千川"
  "先归因到选品 (货)，其次才是主播 (人) 和场"
  "学习期 (积累约 20-50 个转化前) 锁死计划不动、容忍数据难看，给算法学习时间"
  "回答不是；目标 ROI 设为「保本 ROI × 1.2」左右、能放量即可，不要拉到不敢花钱的程度"
  "：直播间精细成交用千川、不用 DOU+ (DOU+ 是弱内容加热)；冷启动轻量起步用小店随心推 (单场预算约 300-500 元，行业经验值)；2025-05-22 起【推商品】场景只能用商品全域推广 (标准推广已下线)"
  "先按自己账号的实时标签和历史成交人群选，不要因为某品在别人直播间卖爆就上"
  "先定位 ta 在 0→1 / 1→10 / 10→100 哪个阶段，按阶段给单一重点 (0→1 只追账号标签精准、不追 GMV 与利润率)；扩张按预算阶段排序 F (自播打底) → A (达人放量) → C/T (有预算再上)，不要 FACT 四件齐做"
  "先把一个号跑到稳定月销、验证 SOP 可复制，再做有明确分工的矩阵；不要在 0→1 阶段开第二个号"
  "先用监管红线过一遍 (绝对化用语 / 退货率 / AI 数字人标识 / 资质公示 / 主播法律身份)，再谈运营；遇到「刷量 / 刷单 / 螺旋起号刷数据能不能做」直接判违法 (2026 新规数据真实性条款 + 黑名单封堵换号)，不进入「技巧」讨论"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "general-playbook-decision"
fi
