#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for AI 产品经理 (LLM 应用 / 生成式 AI / Agent 产品 / Copilot 嵌入 — 跨模型评估 / 工作流设计 / 产品-工程协同).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="AI 产品经理 (LLM 应用 / 生成式 AI / Agent 产品 / Copilot 嵌入 — 跨模型评估 / 工作流设计 / 产品-工程协同)"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 模型能力近 3-6 月迭代轨迹 + 该层会不会被模型 native 化
  9.2 eval / error analysis 现状诊断
  9.3 workflow vs agent 边界判定
  9.4 单用户 token 经济模型 + cost-quality-latency 硬约束定位
  9.5 学派语境定位（用户 / 公司在哪个产品决策流派）
  9.6 AI PM 角色类型 + 协作边界诊断
  9.7 失败模式 / 可靠性现实校准

背后的心智模型:
  • Eval 是地基,不是可选项（别 vibe-check）: 「AI 产品的『好』不是看几个 case 觉得行就 ship —— 是先针对你**自己产品的失败模式**建一套可重复、可回归的系统化测量;没有 eval 就是在瞎改。」
  • 先 error analysis,再加功能（PM 亲自看 trace）: 「质量上不去时,资深 AI PM 的第一反应**不是加功能**,是 PM 亲自拉 10-50 个真实 trace（trace 条数量级见 Hamel field-guide T03-S001 / ev
  • workflow vs agent 要分清,多数需求是 workflow: 「『agent』被严重滥用 —— 真正的 agent 是 LLM 自主决定用什么工具、何时用、多步执行;但多数 AI 需求其实是预定义路径能解决的 **workflow**,默认假设是 workflo

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "模型能力近 3-6 月迭代轨迹 + 该层会不会被模型 native 化"
  "eval / error analysis 现状诊断"
  "workflow vs agent 边界判定"
  "单用户 token 经济模型 + cost-quality-latency 硬约束定位"
  "学派语境定位（用户 / 公司在哪个产品决策流派）"
  "AI PM 角色类型 + 协作边界诊断"
  "失败模式 / 可靠性现实校准"
)
declare -a DIM_QUESTIONS=(
  "近 3-6 个月 frontier 模型(GPT / Claude / Gemini)发布了什么新能力;用户当前依赖的某个 capability(长 context / 工具调用 / reasoning / 多模态)有没有被模型 native 化、哪些第三方层(RAG / prompt 优化 / agent 框架)正被吃掉一层。"
  "用户的产品有没有针对自己 failure mode 的 eval 套件(不是公开 benchmark);有没有 golden set(30-50 个、PM+领域专家共建);LLM-judge 校准了没(75-90% 一致);PM 有没有亲自做过 error analysis。(「golden set 30-50 个」「judge 校准 75-90% 一致」均出自 Hamel evals-FAQ T03-S016,详见 §8.4)"
  "用户的需求能不能跑在预定义代码路径上;如果说要做 agent,是真需要 LLM 自主决策多步,还是一个 routing / chaining workflow 就够;有没有更便宜的低层方案没试。"
  "token 单价 × 预期用户行为 × 留存 → 单用户成本能不能撑住定价;这个场景 cost / quality / latency 哪个是硬约束;agent 多轮对话有没有二次方 token 增长陷阱。"
  "用户/公司的产品决策实际站在模型派 / 工作流派 / agent 派 / 数据飞轮派的哪一派(或混合);特别是「要不要建数据飞轮当护城河」这个 disputed 问题上的立场;这个立场和他们的实际资源是否匹配。"
  "在用户这家公司,「AI PM」具体是 4 种里的哪种(传统 PM+AI 项目 / 技术 PM / eval 专员+PM / AI 业务负责人);PM 和 ML 工程师 / 数据标注 / 法务安全的边界是否清楚;谁拥有 prompt、谁拥有 eval 策略。"
  "用户对 AI 不可靠的预期是否现实(知不知道 pass^k、demo-to-production gap);有没有 defensive UX(设预期 / 可撤销 / 给出处 / 失败回退);ship 门是不是「demo 跑通一次」;有没有把所有错误都笼统叫 hallucination。"
)
declare -a DIM_SOURCES=(
  "Simon Willison weblog(新模型发布当天评测)+ 他的年度「year in LLMs」;各 vendor 官方 news(Anthropic / OpenAI / Hugging Face blog,作事实源);artificialanalysis.ai 类模型对比(作榜单,不作判断源)。"
  "Hamel Husain blog(field-guide / evals-FAQ / 选型文)+ Eugene Yan eval-process;Track 03 workflow 3/4 的入门 SOP 作 checklist;用户自己产品的 trace 和现有评估流程。"
  "Anthropic「Building Effective Agents」(五种 workflow 模式作对照)+ Simon Willison 的 agent 定义;Track 02 选型决策树 Branch 2d;Track 03 workflow 5 step 1 的判断门。"
  "vendor API 定价页(OpenAI / Anthropic / Gemini docs)+ CloudZero 类对比;Chip Huyen《AI Engineering》的 cost-quality-latency 三角章;Track 03 workflow 1 step 5。"
  "Track 04 canon 的四流派种子 + §7 智识谱系;a16z「The Empty Promise of Data Moats」(飞轮祛魅一手观点);Anthropic Building Effective Agents(工作流派奠基)。"
  "Track 06 glossary「AI Product Manager 角色定义混乱」详条 + Data Science PM / Arize / Product School 的(彼此不一致的)分类法;Track 03「贯穿全流程协作边界」表。"
  "τ-bench 的 pass^k 数据 + Eugene Yan llm-patterns 的 defensive UX 节;Track 03 workflow 5 的失败模式 + CLI 自检项;用户产品的 incident / 失败案例。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "1-2 句:「过去 X 个月模型新增了 ___ 能力;用户依赖的 ___ 层 [会 / 不会] 在 6-12 个月内被模型 native 化,建议 [现在投入 / 按周末能不能剥掉判断 / 推迟]。」"
  "1-2 句:「eval 成熟度 = [无 / 有 dashboard 无 error analysis / 有 golden set 未校准 judge / 完整];最高 ROI 的下一步是 ___(通常是 PM 先读 10-50 条 trace 做 error analysis)。」"
  "1-2 句:「这个需求是 [workflow / agent / 混合];推荐用 ___(若 workflow,指明五模式里哪个);若坚持 agent,ship 门必须是 pass^k。」"
  "1-2 句:「单用户/月预估 API 成本 ≈ ___ vs 定价 ___,[能 / 不能 / 勉强] ship;硬约束是 ___,建议倒推方案 ___。」"
  "1-2 句:「用户当前决策倾向 ___ 派;这一派在 ___ 问题上的已知风险是 ___(如:飞轮派需诚实评估 data moat 是否空头支票);建议保留的反方视角是 ___。」"
  "1-2 句:「用户的 AI PM 角色 ≈ 第 ___ 种;与工程师的边界 [清晰 / 模糊在 ___];建议明确归属的事项是 ___(如 error analysis 起点应归 PM)。」"
  "1-2 句:「用户对可靠性的预期 [现实 / 过于乐观];当前缺的兜底是 ___(defensive UX / pass^k ship 门 / failure mode 拆分);建议把 ship 标准改成 ___。」"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
