#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for LLM agent 基础设施.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="LLM agent 基础设施"
DIM_COUNT=5

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (5 个):
  9.1 Framework current state
  9.2 Production reality check
  9.3 Eval methodology
  9.4 Tool stack alignment
  9.5 Regulatory blast radius

背后的心智模型:
  • Framework as scaffold, not foundation: 你今天选的 agent framework 6 个月后大概率不再合适，因为模型能力升级会让上层抽象失效。
  • Eval > model architecture (industry-amplified): 在 LLM agent infra, eval data 比 model architecture 重要; 「build the eval first」是这一行的 first principle.
  • Production reality vs demo glamour (industry-amplified): 一个 agent demo 看起来惊艳和它在生产环境跑得起来是两个不同的问题; LLM stochasticity 把这个差距放大到比传统软件大一个数量级.

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "Framework current state"
  "Production reality check"
  "Eval methodology"
  "Tool stack alignment"
  "Regulatory blast radius"
)
declare -a DIM_QUESTIONS=(
  "GitHub stars / 最近 30 天 commit 频率 / breaking change 历史"
  "有没有公司在用这个 framework / tool 跑生产? 规模如何? pain points 是什么?"
  "该问题的 eval set 是否存在? 行业 benchmark 是什么? human-validation 比例是?"
  "当前选型符合 thin-vs-thick 流派 + 是否 hybrid-retrieval-aware"
  "EU AI Act / China 备案 / US executive order 在这个场景适用吗?"
)
declare -a DIM_SOURCES=(
  "repo 本身 (\`langchain-ai/langgraph\`, \`microsoft/autogen\`, \`crewAIInc/crewAI\`, \`pydantic/pydantic-ai\`) 的 releases"
  "a) 框架官方 case studies (打折扣 — 自营销); b) Twitter/X 工程师吐槽 (搜 \"{name} + production\"); c) HN 评论"
  "Hamel Husain blog / Eugene Yan / Inspect AI examples"
  "Track 02 输出 + 行业 podcast 最近评测"
  "Track 06 法规节; 相关 law firm 长稿"
)
declare -a DIM_OUTPUT_FORMATS=(
  "each candidate 的「活跃度 / 稳定度」二维标记"
  "production-readiness 等级 (toy / pilot / scaled)"
  "评估这个 agent / workflow 的 1-3 个 measurable indicator"
  "当前选型 + 1-2 个替代"
  "low / medium / high regulatory exposure + 1 句具体来源"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
