#!/usr/bin/env bash
# vs.sh — 自住 vs 投资决策分流 + 杠杆/断供应对(两条逻辑严格分开) SOP walkthrough for 国内房产投资(房产投资人视角 — 城市与地段选择 / 政策与调控解读 / 一手房与二手房 / 房产金融与杠杆 / 估值与尽职调查 / 交易流程与税费 / 持有运营与出租 / 退出与流动性 / 风险识别 / 房产在个人资产配置中的位置 / 投资者的决策框架与心态 — 聚焦中国大陆,2021 年以来深度下行期的真实市场).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="国内房产投资(房产投资人视角 — 城市与地段选择 / 政策与调控解读 / 一手房与二手房 / 房产金融与杠杆 / 估值与尽职调查 / 交易流程与税费 / 持有运营与出租 / 退出与流动性 / 风险识别 / 房产在个人资产配置中的位置 / 投资者的决策框架与心态 — 聚焦中国大陆,2021 年以来深度下行期的真实市场)"
WORKFLOW="自住 vs 投资决策分流 + 杠杆/断供应对(两条逻辑严格分开)"

usage() {
  cat <<EOF
vs.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./vs.sh             # interactive
  ./vs.sh --dry-run
  ./vs.sh --json
  ./vs.sh --explain
  ./vs.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "自住 vs 投资决策分流 + 杠杆/断供应对(两条逻辑严格分开)" 工作流。

一句话: 从「我要不要买/已经买了房有压力」到「先把自住逻辑和投资逻辑分清,再设定杠杆纪律和断供应对预案」—— 这是一条「元决策 + 风险底线」工作流:自住看居住效用、投资看回报率/流动性/退出,两套逻辑不能混;杠杆纪律是硬规矩。 (evidence: [T01-S015, T01-S001, T03-S003])

入门 SOP 共 5 步, 失败模式自检 5 项。

相关心智模型:
  • 没有「全国房价」—— 城市与板块分化是第一性问题: 不存在「全国房价怎么样」这回事 —— 2021 年后一线核心、三四线、人口流出城市可能同时涨 / 跌 / 阴跌;「买对城市、买对板块」是国内房产投资的第一性问题,选错城市后面所有努力都白费,而且城市内
  • 中国房产是政策驱动 > 市场驱动 —— 读政策、留余量、不赌政策: 中国房产市场是政策驱动多于市场驱动的市场 —— 限购/限贷/限售/认房认贷/LPR/参考价/房产税/保交楼都是可随时启用或急转的政策工具,「读政策原文」是核心能力;但读政策是为了「判方向、留余量」,不

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**先定性:这套房是自住还是投资**:买之前先回答「这是自住还是投资」—— 这决定用哪套逻辑,不能含糊。混合用途的也要拆出「自住部分」和「投资部分」分别评估。inputs: 购房意图;outputs: 用途定性。"
  "**【自住】按居住效用决策**:自住房看通勤、学区、居住舒适度、家庭需求、长期稳定性 —— 不用投资回报率绑架自住决策,「买得起、住得舒服、长期不折腾」是核心。inputs: 家庭需求;outputs: 自住决策。"
  "**【投资】按回报率/流动性/退出决策**:投资房走 W1-W7 完整弧线,看净租金回报率、流动性、退出可行性 —— 不用「反正能自住」掩盖投资亏损。inputs: W1-W7 输出;outputs: 投资决策。"
  "**设定杠杆纪律**:上杠杆前算清「断供线在哪、首付来源是不是 100% 自有资金、现金流断了能撑几个月」—— 而不是只算「最多能贷多少」。首付贷/经营贷置换/假流水是红线,不碰。inputs: 收入/负债/储备;outputs: 杠杆纪律线。"
  "**做断供应对预案**:万一收入中断,预案是什么 —— 动用储备金、与银行协商、必要时主动卖出(W7)止损,而不是等到断供。断供后果是房子被处置 + 征信污点 + 可能被追差额。inputs: 压力情景;outputs: 应对预案。"
)
declare -a FAILURE_MODES=(
  "**用「反正自住」掩盖投资亏损**:触发原因 = 不愿承认投资判断错了;怎么避免 = 买入时就定性,投资房就按投资标准复盘,自住效用不能用来掩盖回报率为负。Don't: 一套明显是投资目的的房跌了,改口说「反正是自住」,从此不再正视这笔亏损也不做退出决策。"
  "**杠杆只听「放大收益」**:触发原因 = 上行期叙事残留 + 大师话术;怎么避免 = 每次上杠杆同等算「放大的亏损能不能扛、现金流会不会断」。Don't: 因为「用足杠杆才聪明」上到极限,房价跌 + 收入降双击,现金流断裂滑向断供。"
  "**把灰色操作当「资深技巧」**:触发原因 = 「技术流大师」包装成认知差;怎么避免 = 经营贷置换/首付贷/假流水识别为红线,首付必须自有资金。"
  "**all in 房产、不留流动性**:触发原因 = 「房产最保值」的旧信念;怎么避免 = 把房产放进家庭资产负债表控占比、留流动性。"
  "**Decay risk**: medium —— 决策分流逻辑和杠杆纪律框架是稳态的(low),但认房认贷口径、首付比例、LPR、灰色操作的监管环境是 12 个月内会变的项,整体 medium。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "vs-walkthrough"
fi
