#!/usr/bin/env bash
# workflow-6.sh — 退出与流动性(卖出时机判断 + 挂牌成交 + 止损决策) SOP walkthrough for 国内房产投资(房产投资人视角 — 城市与地段选择 / 政策与调控解读 / 一手房与二手房 / 房产金融与杠杆 / 估值与尽职调查 / 交易流程与税费 / 持有运营与出租 / 退出与流动性 / 风险识别 / 房产在个人资产配置中的位置 / 投资者的决策框架与心态 — 聚焦中国大陆,2021 年以来深度下行期的真实市场).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="国内房产投资(房产投资人视角 — 城市与地段选择 / 政策与调控解读 / 一手房与二手房 / 房产金融与杠杆 / 估值与尽职调查 / 交易流程与税费 / 持有运营与出租 / 退出与流动性 / 风险识别 / 房产在个人资产配置中的位置 / 投资者的决策框架与心态 — 聚焦中国大陆,2021 年以来深度下行期的真实市场)"
WORKFLOW="退出与流动性(卖出时机判断 + 挂牌成交 + 止损决策)"

usage() {
  cat <<EOF
workflow-6.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-6.sh             # interactive
  ./workflow-6.sh --dry-run
  ./workflow-6.sh --json
  ./workflow-6.sh --explain
  ./workflow-6.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "退出与流动性(卖出时机判断 + 挂牌成交 + 止损决策)" 工作流。

一句话: 从「决定要卖 / 该不该卖」到「真正成交拿到钱」—— 这是国内房产投资里最被低估、2024-2025 最残酷的一环:房产是低流动性资产,挂出去可能 12 个月卖不掉或必须大幅折价,「想卖」不等于「卖得掉」。 (evidence: [T05-S010, T05-S013, T01-S015])

入门 SOP 共 5 步, 失败模式自检 5 项。

相关心智模型:
  • 没有「全国房价」—— 城市与板块分化是第一性问题: 不存在「全国房价怎么样」这回事 —— 2021 年后一线核心、三四线、人口流出城市可能同时涨 / 跌 / 阴跌;「买对城市、买对板块」是国内房产投资的第一性问题,选错城市后面所有努力都白费,而且城市内
  • 中国房产是政策驱动 > 市场驱动 —— 读政策、留余量、不赌政策: 中国房产市场是政策驱动多于市场驱动的市场 —— 限购/限贷/限售/认房认贷/LPR/参考价/房产税/保交楼都是可随时启用或急转的政策工具,「读政策原文」是核心能力;但读政策是为了「判方向、留余量」,不

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**判断流动性环境(先看卖不卖得掉)**:用贝壳研究院看目标城市/板块的二手房挂牌量(暴增=供给堆积)、成交周期(从挂牌到成交几个月)、带看量、业主调价比例;用易居研究院看存销比 —— 先确认「这个市场现在能不能卖」,而不是先想「能卖多少钱」。inputs: 研究院流动性数据;outputs: 流动性环境标签。"
  "**定一个「能成交」的挂牌价**:参照同板块同户型的真实网签成交价(不是别人的挂牌价)定价 —— 下行期挂「卖家心理价」等于不卖。定价要对标成交,不对标挂牌。inputs: 网签成交价;outputs: 挂牌价。"
  "**挂牌 + 观察带看反馈**:多平台挂牌,观察带看量 —— 挂了一段时间带看个位数 = 价格虚高或有硬伤,带看多不成交 = 价格还在博弈区间。inputs: 平台挂牌;outputs: 带看反馈。"
  "**根据反馈做降价 / 继续持有 / 止损决策**:带看冷清就要么降价对标成交、要么承认「现在卖不掉」继续持有;若是现金流压力驱动的卖出,要算清「降到能成交的价 = 亏多少」,做止损决策 —— 止损是承认判断错误,不是失败。inputs: 带看反馈 + 财务约束;outputs: 降价/持有/止损结论。"
  "**成交 + 走资金监管完成交易**:接受报价后,同样走网签→资金监管→缴税→过户→收款的流程(W5 的镜像,这次你是卖方)。inputs: 买方;outputs: 回款到账。"
)
declare -a FAILURE_MODES=(
  "**按心理价挂牌,在冰封市场干等**:触发原因 = 不接受「现在的市场价低于我的预期」;怎么避免 = 定价对标真实网签成交价,先确认流动性环境再挂牌。Don't: 按「我当年买入价 + 应得收益」定挂牌价,挂 12 个月零成交,期间市场继续下行,最后卖得比一开始就定合理价还低。"
  "**该止损时死扛「等回本」**:触发原因 = 把止损当失败、回避面对亏损;怎么避免 = 买入时就设止损触发线,该执行时按纪律执行,沉没成本和未来现金流分开算。"
  "**等「市场反转」再卖**:触发原因 = 择时幻想;怎么避免 = 按自己的资金需求和标的基本面决定,不赌不可预测的拐点。"
  "**只看价格指数不看流动性指标**:触发原因 = 以为「价格没大跌就还能卖」;怎么避免 = 看挂牌量/成交周期/带看量,流动性崩塌早于价格下跌(evidence: [T05-S010])。"
  "**Decay risk**: high —— 流动性环境、成交周期、限售/限购政策都是 12 个月内会显著变化的项;2024-2025 流动性变差是当前最大变量,本 workflow 是首要刷新对象。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-6-walkthrough"
fi
