#!/usr/bin/env bash
# workflow-1.sh — 选城市(判断「这个城市的房子有没有基本面」) SOP walkthrough for 国内房产投资(房产投资人视角 — 城市与地段选择 / 政策与调控解读 / 一手房与二手房 / 房产金融与杠杆 / 估值与尽职调查 / 交易流程与税费 / 持有运营与出租 / 退出与流动性 / 风险识别 / 房产在个人资产配置中的位置 / 投资者的决策框架与心态 — 聚焦中国大陆,2021 年以来深度下行期的真实市场).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="国内房产投资(房产投资人视角 — 城市与地段选择 / 政策与调控解读 / 一手房与二手房 / 房产金融与杠杆 / 估值与尽职调查 / 交易流程与税费 / 持有运营与出租 / 退出与流动性 / 风险识别 / 房产在个人资产配置中的位置 / 投资者的决策框架与心态 — 聚焦中国大陆,2021 年以来深度下行期的真实市场)"
WORKFLOW="选城市(判断「这个城市的房子有没有基本面」)"

usage() {
  cat <<EOF
workflow-1.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-1.sh             # interactive
  ./workflow-1.sh --dry-run
  ./workflow-1.sh --json
  ./workflow-1.sh --explain
  ./workflow-1.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "选城市(判断「这个城市的房子有没有基本面」)" 工作流。

一句话: 从「我想买房投资」到「锁定 1-3 个值得继续往下看的候选城市」—— 「买对城市」是国内房产投资的第一性问题,2021 年后城市间走势分化极大,选错城市后面所有努力都白费。 (evidence: [T01-S001, T05-S011, T05-S013])

入门 SOP 共 5 步, 失败模式自检 4 项。

相关心智模型:
  • 没有「全国房价」—— 城市与板块分化是第一性问题: 不存在「全国房价怎么样」这回事 —— 2021 年后一线核心、三四线、人口流出城市可能同时涨 / 跌 / 阴跌;「买对城市、买对板块」是国内房产投资的第一性问题,选错城市后面所有努力都白费,而且城市内
  • 中国房产是政策驱动 > 市场驱动 —— 读政策、留余量、不赌政策: 中国房产市场是政策驱动多于市场驱动的市场 —— 限购/限贷/限售/认房认贷/LPR/参考价/房产税/保交楼都是可随时启用或急转的政策工具,「读政策原文」是核心能力;但读政策是为了「判方向、留余量」,不

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**查城市能级与房价方向**:用国家统计局 70 城房价指数,看目标城市所在能级(一线/二线/三线)是涨是跌、连续涨跌几个月 —— 看「环比」不看「同比」(同比滞后一年)。inputs: 候选城市名单;outputs: 每城价格趋势标签。"
  "**查人口净流入还是净流出**:看常住人口近 3-5 年变化、小学在校生数变化(比户籍人口更真实)、是否有产业/就业在聚集。人口持续净流出的城市,房价没有基本面。inputs: 统计公报/人口数据;outputs: 人口流向标签。"
  "**查土地与库存(供给端)**:用中指 CREIS 看土地流拍率/溢价率,用易居研究院看存销比(去化周期月数)—— 存销比 > 18-24 个月 = 严重供过于求,这是识别三四线去库存陷阱的关键指标。inputs: 研究院报告;outputs: 供给压力标签。"
  "**查城市级政策环境**:到目标城市住建局官网查最新限购/限贷/限售文件,确认自己是否有购房资格、首付几成。inputs: 地方住建局公告;outputs: 政策资格标签。"
  "**三关合一出短名单**:价格方向 + 人口流向 + 供给压力 + 政策资格四个标签同时过关的城市才进短名单;任一硬伤(人口流出 / 存销比超高 / 无购房资格)直接排除。"
)
declare -a FAILURE_MODES=(
  "**在整城下行能级里找「洼地」**:触发原因 = 把「跌得多」当「便宜」;怎么避免 = 先用统计局指数确认城市能级方向,能级在跌就不在里面找洼地。Don't: 看到某三四线城市房价腰斩就觉得「抄底机会」,买进后发现人口外流、库存巨大,十年阴跌还卖不掉。"
  "**信地方政府宣传口径的人口数据**:触发原因 = 用易造假的口径;怎么避免 = 用小学在校生数、社保参保人数等难造假的代理指标交叉。Do: 拉目标城市近 5 年小学在校生数曲线,下滑就不碰。"
  "**用中介挂牌价做城市横向比较**:触发原因 = 各城口径不一 + 卖方报价;怎么避免 = 横向比较只用统计局 70 城指数(evidence: [T02-S001])。"
  "**Decay risk**: medium —— 方法论(人口/土地/政策三查)稳定,但「具体城市的政策资格 + 库存数据」12 个月内会变,需定期刷新。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-1-walkthrough"
fi
