#!/usr/bin/env bash
# workflow-7.sh — 政策跟踪(政策原文 → 影响判断 → 留余量) SOP walkthrough for 国内房产投资(房产投资人视角 — 城市与地段选择 / 政策与调控解读 / 一手房与二手房 / 房产金融与杠杆 / 估值与尽职调查 / 交易流程与税费 / 持有运营与出租 / 退出与流动性 / 风险识别 / 房产在个人资产配置中的位置 / 投资者的决策框架与心态 — 聚焦中国大陆,2021 年以来深度下行期的真实市场).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="国内房产投资(房产投资人视角 — 城市与地段选择 / 政策与调控解读 / 一手房与二手房 / 房产金融与杠杆 / 估值与尽职调查 / 交易流程与税费 / 持有运营与出租 / 退出与流动性 / 风险识别 / 房产在个人资产配置中的位置 / 投资者的决策框架与心态 — 聚焦中国大陆,2021 年以来深度下行期的真实市场)"
WORKFLOW="政策跟踪(政策原文 → 影响判断 → 留余量)"

usage() {
  cat <<EOF
workflow-7.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-7.sh             # interactive
  ./workflow-7.sh --dry-run
  ./workflow-7.sh --json
  ./workflow-7.sh --explain
  ./workflow-7.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "政策跟踪(政策原文 → 影响判断 → 留余量)" 工作流。

一句话: 从「听到一个政策消息/传闻」到「确认政策原文 + 判断对自己的具体影响 + 留出余量」—— 中国房产是政策驱动 > 市场驱动,读政策是核心能力;这是一条贯穿 W1-W7 全程的横切工作流,不是某个环节的一次性动作。 (evidence: [T02-S005, T03-S001])

入门 SOP 共 4 步, 失败模式自检 5 项。

相关心智模型:
  • 没有「全国房价」—— 城市与板块分化是第一性问题: 不存在「全国房价怎么样」这回事 —— 2021 年后一线核心、三四线、人口流出城市可能同时涨 / 跌 / 阴跌;「买对城市、买对板块」是国内房产投资的第一性问题,选错城市后面所有努力都白费,而且城市内
  • 中国房产是政策驱动 > 市场驱动 —— 读政策、留余量、不赌政策: 中国房产市场是政策驱动多于市场驱动的市场 —— 限购/限贷/限售/认房认贷/LPR/参考价/房产税/保交楼都是可随时启用或急转的政策工具,「读政策原文」是核心能力;但读政策是为了「判方向、留余量」,不

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**回到政策原文**:看到任何政策消息,先回官方原文 —— 顶层定调看中国政府网(政治局会议/中央经济工作会议),全国性政策看住建部/央行,城市政策看地方住建局/房管局,房产税看全国人大/沪渝市政府。不把自媒体解读当政策本身。inputs: 政策传闻;outputs: 政策原文。"
  "**判断政策性质与层级**:是顶层定调(领先、抽象)还是地方落地文件(具体、可执行)?是松还是紧?适用范围(全国/本城/本区)?inputs: 政策原文;outputs: 政策性质标签。"
  "**判断对自己的具体影响**:把政策落到「我能不能买/首付几成/能不能卖/月供变不变/持有成本变不变」—— 抽象定调要等地方落地文件才能转成动作。inputs: 政策标签 + 自己的持仓/计划;outputs: 影响判断。"
  "**留余量,不赌政策**:政策可以急转(收紧或放松),决策时为「政策可能往反方向走」留余量 —— 不基于「政策一定会继续放松」或「一定会救市」下注。inputs: 影响判断;outputs: 调整后的动作 + 余量。"
)
declare -a FAILURE_MODES=(
  "**把自媒体解读当政策原文**:触发原因 = 原文难找/看不懂、解读省事;怎么避免 = 限购/限贷/限售/利率/参考价一律以官方公告原文为准,读到传闻先回官方渠道证实再行动。Don't: 看到公众号「XX 城要全面放开限购」就赶紧出手,结果是误读或传闻,正式文件根本不是那个意思。"
  "**赌政策放松/救市**:触发原因 = 「政策不会让房价跌」;怎么避免 = 不赌政策,每个决策为政策反向留余量,「政策托底 ≠ 你的房保值」。"
  "**顶层定调当执行动作**:触发原因 = 看到「止跌回稳」就以为市场已稳;怎么避免 = 顶层判方向、地方判动作,等地方落地文件。"
  "**等自媒体解读完再动**:触发原因 = 依赖二手转述;怎么避免 = 政策出台即看原文,不等解读。"
  "**Decay risk**: high —— 工作流方法论本身稳定(读原文→判影响→留余量),但「当前有效的具体政策」是 12 个月内持续变动的,作为政策跟踪工作流必须高频刷新所跟踪的政策内容。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-7-walkthrough"
fi
