#!/usr/bin/env bash
# workflow-2.sh — 选板块与地段(在选定城市内部锁定区域价值单元) SOP walkthrough for 国内房产投资(房产投资人视角 — 城市与地段选择 / 政策与调控解读 / 一手房与二手房 / 房产金融与杠杆 / 估值与尽职调查 / 交易流程与税费 / 持有运营与出租 / 退出与流动性 / 风险识别 / 房产在个人资产配置中的位置 / 投资者的决策框架与心态 — 聚焦中国大陆,2021 年以来深度下行期的真实市场).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="国内房产投资(房产投资人视角 — 城市与地段选择 / 政策与调控解读 / 一手房与二手房 / 房产金融与杠杆 / 估值与尽职调查 / 交易流程与税费 / 持有运营与出租 / 退出与流动性 / 风险识别 / 房产在个人资产配置中的位置 / 投资者的决策框架与心态 — 聚焦中国大陆,2021 年以来深度下行期的真实市场)"
WORKFLOW="选板块与地段(在选定城市内部锁定区域价值单元)"

usage() {
  cat <<EOF
workflow-2.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-2.sh             # interactive
  ./workflow-2.sh --dry-run
  ./workflow-2.sh --json
  ./workflow-2.sh --explain
  ./workflow-2.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "选板块与地段(在选定城市内部锁定区域价值单元)" 工作流。

一句话: 从「选定了城市」到「锁定 2-4 个值得具体看房的板块/地段」—— 城市内部分化和城市间分化一样大,板块逻辑(产业/交通/学区/规划/配套)决定了同城不同板块可能一个虹吸一个被抽血。 (evidence: [T05-S010, T05-S011])

入门 SOP 共 5 步, 失败模式自检 4 项。

相关心智模型:
  • 没有「全国房价」—— 城市与板块分化是第一性问题: 不存在「全国房价怎么样」这回事 —— 2021 年后一线核心、三四线、人口流出城市可能同时涨 / 跌 / 阴跌;「买对城市、买对板块」是国内房产投资的第一性问题,选错城市后面所有努力都白费,而且城市内
  • 中国房产是政策驱动 > 市场驱动 —— 读政策、留余量、不赌政策: 中国房产市场是政策驱动多于市场驱动的市场 —— 限购/限贷/限售/认房认贷/LPR/参考价/房产税/保交楼都是可随时启用或急转的政策工具,「读政策原文」是核心能力;但读政策是为了「判方向、留余量」,不

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**建立板块价值地图**:把城市分成板块/地段单元,标注每个板块的核心驱动 —— 产业就业(有没有大企业/园区)、交通(地铁/通勤时间)、配套(商业/医院)成熟度。inputs: 城市规划 + 地图;outputs: 板块价值排序。"
  "**核查规划(利好与利空都要查)**:到城市规划/自然资源部门官网查目标板块的规划 —— 地铁线路、学校、商业是否落地;同时查「利空规划」:垃圾站、变电站、高压线、高架。inputs: 规划部门公示;outputs: 规划利好/利空清单。"
  "**核查学区(如果板块靠学区溢价)**:确认目标板块对应的学校、最新的学区划片政策(多校划片/摇号)、入学年限要求 —— 学区政策是高 decay 项,会变。inputs: 教育局划片文件;outputs: 学区有效性判断。"
  "**读板块二手房流动性**:用贝壳研究院/找房平台看目标板块的二手房挂牌量、成交周期、带看量 —— 同城里挂牌量暴增、成交周期拉到 12 个月的板块,流动性已经在恶化。inputs: 贝壳研究院/平台数据;outputs: 板块流动性标签。"
  "**筛出短名单**:产业/交通/配套有支撑 + 规划无重大利空 + (如靠学区)学区有效 + 流动性未崩 —— 同时满足才进短名单。"
)
declare -a FAILURE_MODES=(
  "**把规划的「饼」算进估值**:触发原因 = 听信「这里要通地铁/建名校」;怎么避免 = 只把已出让土地、已开工的配套算数,规划利好打折看。Don't: 因为「规划有地铁」溢价买入,十年后地铁仍未动工,板块价值兑现遥遥无期。"
  "**买「睡城」当价值洼地**:触发原因 = 单价低误判为便宜;怎么避免 = 先看板块有没有产业就业,无产业不碰。"
  "**信中介的学区承诺**:触发原因 = 中介「保证能上 XX 学校」;怎么避免 = 查教育局最新划片文件原文,政策可变。"
  "**Decay risk**: medium —— 板块价值逻辑稳定,但学区政策、规划进度、板块流动性是 12 个月内会变的高频项。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-2-walkthrough"
fi
