#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 现代建筑设计 (从 concept 草图到施工图与现场服务的整套设计流程, 含 BIM / 可持续 / 参数化 / 在地性 模块, 全球语境 + 中国本土实践并重).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="现代建筑设计 (从 concept 草图到施工图与现场服务的整套设计流程, 含 BIM / 可持续 / 参数化 / 在地性 模块, 全球语境 + 中国本土实践并重)"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 Program × Site × Tectonics 三轴诊断 (mental model 1.2 + 1.5 直接对应)
  9.2 业主真 motivation 解码 (mental model 1.4 直接对应)
  9.3 衰退周期分层诊断 (mental model 1.3 直接对应)
  9.4 三件事自检 — render / model / build (mental model 1.1 直接对应)
  9.5 流派定位 + 业内同代对照 (mental model 1.5 + 智识谱系 §7 对应)
  9.6 5-phase 节奏 + 当下应该 lock / leave open 自检 (mental model 1.6 直接对应)
  9.7 Carbon 决策窗口诊断 (mental model 1.7 直接对应)

背后的心智模型:
  • 三件事原则 — 可视化 ≠ 设计 ≠ 可建造 (visualization ≠ design ≠ buildable): 渲染图 / 数字模型 / 实建物 是三个独立 artifact, 各有不同的成功标准 + 不同读者 + 不同保鲜期; 混淆三者是 90% (业内估) 业主-建筑师冲突 + 项目失约的根因.
  • 三轴决定 — Program × Site × Tectonics (everything else is decoration): 每个设计决策必须在三轴上同时合理 — Program (人在里面做什么) × Site (在哪 + 什么气候 + 什么文化) × Tectonics (用什么材料 + 什么节点 + 谁来造); 缺一轴
  • 衰退周期分层 — Style 15-25 年, 工具 5-10 年, 节点 / 材料 / 结构原理 50+ 年: 建筑师押注的"知识层"决定职业寿命 — 押 parametricism / 解构 / minimalism 等"风格", 15-25 年周期即过时; 押 BIM / AI 工具掌握, 5-10 年周期

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "Program × Site × Tectonics 三轴诊断 (mental model 1.2 + 1.5 直接对应)"
  "业主真 motivation 解码 (mental model 1.4 直接对应)"
  "衰退周期分层诊断 (mental model 1.3 直接对应)"
  "三件事自检 — render / model / build (mental model 1.1 直接对应)"
  "流派定位 + 业内同代对照 (mental model 1.5 + 智识谱系 §7 对应)"
  "5-phase 节奏 + 当下应该 lock / leave open 自检 (mental model 1.6 直接对应)"
  "Carbon 决策窗口诊断 (mental model 1.7 直接对应)"
)
declare -a DIM_QUESTIONS=(
  "项目 program (建筑类型 + 主要 user + 使用模式) / site (地理 + 气候 + 文化 + 周边 + 规范限制 — 容积率 / 限高 / 退线 / 防火) / tectonics (业主 budget tier + 主要可用材料 + 当地施工能力 + 主要节点系统)"
  "业主 stated goal (reputation / iconic / cost / schedule / asset value) 之外的 implicit motivation (政治 / 内部权力 / family legacy / 业务 PR / 上市估值); past project 历史 (业主之前合作的建筑师 / 项目失败原因); 决策链 (业主一人 / 业主夫妇 / 业主+董事会 / 政府委员会)"
  "项目 / 决策 / 工具选择对应哪个时间层 (15-25 年 style / 5-10 年 tool / 50+ 年 tectonics-material-structure-history); 押注的层是否匹配项目 lifespan (e.g. 公共建筑 50 年 vs 商业 zone 15 年 vs 临展 1 年)"
  "当前 deliverable 是 render / digital model / building, 各自 success criteria (render: communication impact; model: coordination accuracy; build: durability + use + cost); 三件事之间 misalignment 信号 (renderer 出图业主签了, 但 model 几何不可建; model 协调了, 但 spec 与现实成本差 2x)"
  "项目 / 设计师所在流派 (9 流派中哪 1-2 个); 同流派 ≥ 3 当代 figures 在做什么 (e.g. critical regionalism: Wang Shu / Liu Jiakun / Kéré 当前项目); 流派内分歧 (e.g. critical regionalism 内 \"符号贴图\" vs \"抽象在地策略\" 之争)"
  "当前项目所在 phase (SD/DD/CD/CA), 应该 lock 的内容 (体块 / 材料 / spec) vs 应该故意 leave open 的内容; 是否被业主 / 施工方 pressure 提前画大样 / 提前 lock spec"
  "当前 phase 是否在 carbon 决策的最佳窗口 (Programming → SD 锁 envelope + 朝向 + 主体材料 = 80% (业内估, 引 EC3 + Architecture 2030) embodied carbon 已定); operational target vs embodied target priority; 业主对 carbon 的 真正 commitment (rhetoric vs budget)"
)
declare -a DIM_SOURCES=(
  "业主 RFP / 用地红线图 / 当地气候数据 (CSWD 中国 / ASHRAE 国际) / 规划法规原文 (zh: 住建部 / 国标全文; en: IBC / local building code) / 同 typology 同地区 reference building (有方 / 谷德 / ArchDaily 项目库) / 当地承包商 capability 报告"
  "第一次会议 + 后续 3 次会议的细节笔记 (谁先开口 / 谁拍板 / 谁问钱); 业主之前项目 (求职业主 LinkedIn / 上市公司 annual report / 项目所在城市 news); 同行 reference (问做过该业主的同行建筑师)"
  "项目 brief 中的 expected lifespan / 业主 horizon; 材料 spec 的 service life (混凝土 50-100 年 / 钢 50-80 年 / 玻璃 30-50 年 / curtain wall 25-40 年); 风格 / 工具的 hype curve (Gartner 类 + 行业 journals 历史 issue 对比)"
  "SD/DD/CD deliverable 对照 (3 阶段渲染 vs 模型 vs spec); BIM clash report; 业主 feedback 是基于 render 还是基于 model 还是基于 reference building"
  "Track 01 figures 9 流派矩阵 (本 skill referenes/research/01-figures.md); Architectural Review / Domus / El Croquis 当代专题 (流派分类); 中国当代: 有方 / 谷德 当代专题"
  "AIA Project Delivery Guide (各 phase deliverable 标准) / RIBA Plan of Work / 中国设计周期对照; 项目当前 deliverable 检查 — SD 有大样? DD 还在改方案? CD 还在改材料?"
  "ClimateStudio + One Click LCA / Tally / EC3 早期 quick estimate; AIA 2030 Commitment 实际公开数据 (行业落后情况); Architecture 2030 baseline; 业主 carbon target spec (在合同中?)"
)
declare -a DIM_OUTPUT_FORMATS=(
  "3 行结构化 — \`Program: {1 句描述 + 主要 user + 使用模式}\` / \`Site: {气候 + 文化 + 规范关键约束 3 件}\` / \`Tectonics: {budget tier \$X-\$Y/sqft + 主要材料 + 关键节点系统}\`. 三轴任一空白 → 设计不成立, 回业主补 brief."
  "\`Stated goal: {业主口头表达}\` / \`Implicit motivation: {推断的真动力 + 置信度 high/medium/low}\` / \`决策链: {who decides what + sign-off 节奏}\` / \`red flag: {风险信号 3 件}\`."
  "\`Project lifespan: {N 年}\` / \`押注层匹配度: {high/medium/low}\` / \`mismatch risk: {如有 — e.g. 100 年公共建筑用 5 年 cycle parametric tool 出图 → 形式 + 工具都 25 年内过时, 但建筑本体 100 年, 推荐切回更长周期 tectonic + material 决策}\`."
  "\`Render integrity: {当前渲染基础是 model 真实数据 还是 mood board}\` / \`Model integrity: {LOD 是否匹配 phase 期望}\` / \`Build feasibility: {当前节点 + 材料 + budget 在当地施工方能力内吗}\` / \`Misalignment risk: {如有, 立即修正}\`."
  "\`当前流派: {1-2 流派 + 立场}\` / \`同代代表 3 件事: {N people + N projects + N debates}\` / \`分歧定位: {项目落在流派内哪个 sub-position}\` / \`差异化机会: {如有 — 同流派别人没做的 niche}\`."
  "\`当前 phase: {SD/DD/CD/CA}\` / \`应该 lock: {3 件}\` / \`应该 leave open: {3 件}\` / \`Mismatch: {如有 lock 早了 / lock 晚了 — 立即回正}\`."
  "\`Current carbon target: {operational kgCO2e/m²/yr + embodied kgCO2e/m² + 业内 reference}\` / \`Window status: {Programming/SD = high-leverage 决策窗口 / DD = medium / CD = low / CA = patch-only}\` / \`业主 commitment: {budget allocated / 仅 PR / 不 clear}\` / \`Recommended action: {early LCA + 替代材料对比 / 中期监控 / 后期 communication 管理}\`."
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
