#!/usr/bin/env bash
# topic-1.sh — 子平 决策助手 for 八字命理 + 玄学相关数术 (子平派 / 盲派 / 新派 / 紫微斗数边界).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="八字命理 + 玄学相关数术 (子平派 / 盲派 / 新派 / 紫微斗数边界)"
TOPIC="子平"

usage() {
  cat <<EOF
topic-1.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 4 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-1.sh             # interactive
  ./topic-1.sh --dry-run   # walk through but no file
  ./topic-1.sh --json      # JSON to stdout
  ./topic-1.sh --explain   # show backing playbook rules + mental models
  ./topic-1.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 子平 主题下的 playbook 规则组合成交互树。

基于 4 条规则:
  • 如果 开始批一个新八字 → 则 先走"排盘 → 起运 → 取格 → 定用神"四步主轴 (子平流程)
  • 如果 学派分歧 → 则 (同盘子平 vs 盲派 vs 新派给不同结论), **保留双方结论**, 让命主自己感受验证
  • 如果 回答时间应期 → 则 子平派多看大运 + 流年; 盲派可下流日, 但流月以下精度边界看个人功夫 (新手不强求)
  • 如果 客户带着神煞问题来 → 则 ("我命带 X 神煞会怎样"), 子平派古法**弱化神煞** — 主张五行生克为根本; 盲派 + 紫微斗数倚重 (象法核

相关心智模型:
  • 格局 + 用神 二元 (子平派核心): 「看八字第一步永远是『先定格局, 再取用神』 — 沈孝瞻"八字用神, 专求月令", 用神是格局生态里的角色, 不是孤立五行」
  • 调候 寒暖燥湿 (穷通宝鉴心法): 「不分寒暖燥湿就取用神 = 命理偏枯. 月令 + 日干两轴查表 — 庚金生申月需丁火炼 + 甲木引, 乙木生秋月需壬水滋, 这是物理 / 自然规律对应到八字气化层」

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "开始批一个新八字"
  "学派分歧"
  "回答时间应期"
  "客户带着神煞问题来"
)
declare -a RULE_ACTIONS=(
  "先走\"排盘 → 起运 → 取格 → 定用神\"四步主轴 (子平流程)"
  "(同盘子平 vs 盲派 vs 新派给不同结论), **保留双方结论**, 让命主自己感受验证"
  "子平派多看大运 + 流年; 盲派可下流日, 但流月以下精度边界看个人功夫 (新手不强求)"
  "(\"我命带 X 神煞会怎样\"), 子平派古法**弱化神煞** — 主张五行生克为根本; 盲派 + 紫微斗数倚重 (象法核心载体); 看学派语境取舍"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-1-decision"
fi
