#!/usr/bin/env bash
# ppc-cycle.sh — PPC 投放优化 cycle SOP walkthrough for 跨境电商运营.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="跨境电商运营"
WORKFLOW="PPC 投放优化 cycle"

usage() {
  cat <<EOF
ppc-cycle.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./ppc-cycle.sh             # interactive
  ./ppc-cycle.sh --dry-run
  ./ppc-cycle.sh --json
  ./ppc-cycle.sh --explain
  ./ppc-cycle.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "PPC 投放优化 cycle" 工作流。

一句话: 从「计划上线」到「ROAS 稳定在类目均值上」, 持续运营 cycle

入门 SOP 共 7 步, 失败模式自检 5 项。

相关心智模型:
  • 合规优先于流量: 在欧美主流站点, 新品类上线前先解决「能不能合规开卖」, 再考虑「能不能跑出量」。
  • 选品决定 90% 命运: 在亚马逊体系里, 一个品的最终成败 90% 在选品阶段已经决定, 后续运营只能放大这 10% 空间。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "关键词调研 + 分类 — Helium 10 Cerebro 反查 top 5 ASIN → 分高 / 中 / 低竞争 + 长尾"
  "冷启动 Auto 计划 — 系统试人群, 7-14 天积累数据 (不要硬调出价 / 加预算)"
  "第二周 Manual SP — Auto 跑出的高转化关键词转 Manual, 提价精准投放"
  "加 SB Sponsored Brands — 品牌词 + 品牌防御 + 视频"
  "加 SD Sponsored Display — 站内展示 + retargeting 老用户"
  "每周复盘 — 看 ACOS / TACOS / CTR / CVR 四维度, 杀死 < 类目均值 0.5x 的关键词"
  "每月加预算 — 表现好的计划逐步加 (每次 ≤ 30%), 不要 ALL-IN"
)
declare -a FAILURE_MODES=(
  "冷启动期硬调出价 / 加预算 — 打断系统学习"
  "不杀低效关键词, ACOS 居高不下"
  "旺季前不预热, 直接旺季加预算 — 系统没积累人群信号"
  "完全交给智能投放, 不人工 sanity check"
  "看 ACOS 不看 TACOS, 实际广告全花在抢自家自然单"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "ppc-cycle-walkthrough"
fi
