#!/usr/bin/env bash
# 0-long-term-account-growth.sh — 一个号 0 → 商业化 (Long-term Account Growth) SOP walkthrough for 公众号写作助手 (微信公众号文章 全链路 — 选题 / 标题 / 开篇 / 结构 / 行文 / 排版 / 配图 / 推送 / 涨粉 / 留言 / 二次传播 / 变现, 单 artifact = 一篇公众号推文).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="公众号写作助手 (微信公众号文章 全链路 — 选题 / 标题 / 开篇 / 结构 / 行文 / 排版 / 配图 / 推送 / 涨粉 / 留言 / 二次传播 / 变现, 单 artifact = 一篇公众号推文)"
WORKFLOW="一个号 0 → 商业化 (Long-term Account Growth)"

usage() {
  cat <<EOF
0-long-term-account-growth.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./0-long-term-account-growth.sh             # interactive
  ./0-long-term-account-growth.sh --dry-run
  ./0-long-term-account-growth.sh --json
  ./0-long-term-account-growth.sh --explain
  ./0-long-term-account-growth.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "一个号 0 → 商业化 (Long-term Account Growth)" 工作流。

一句话: 从开号到稳定商业化收入的 4 阶段长期 SOP, 总耗时 1-3 年.

入门 SOP 共 4 步, 失败模式自检 0 项。

相关心智模型:
  • 「单篇是产品, 账号是公司」 (Account-as-Product): 单篇推文是 product release, 账号是 company; 不为单篇 metric 牺牲账号长期资产 (定位 / voice / 读者画像).
  • 「头部效应是结构性事实, 不是个人努力问题」 (Power-Law Reality): 90% 公众号永远做不到全职收入, 不是「再努力就能突破」, 是流量 / 注意力 / 算法权重的结构性分布; 商业化必须基于此事实设计对冲 (多平台 / 多变现路径), 不卖速成幻想.

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "0 → 第一篇 (Week 1-2): 定位 5 件套 (vertical + 受众画像 + voice + 名字 + 头像) + 第一篇深度内容"
  "1 → 1000 粉 (Month 1-3): 持续节奏 (周 3-7 篇 hard-stick) + 5 渠道涨粉 (互推 + 跨平台 + 朋友圈 + 微信群 + 视频号联动)"
  "1000 → 1 万 粉 (Month 3-12): 内容升级 + 涨粉加速 + 原创权拿到 + 流量主准入 (粉丝 ≥ 500 / 内容合规)"
  "1 万 → 商业化 (Year 1-3): 矩阵化 + 5-7 路并行变现 (流量主 + 互选广告 + 软广 + 知识付费 funnel + 私域 funnel + 卖货 + 出版引流) + 团队化 + 跨平台 IP 化"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "0-long-term-account-growth-walkthrough"
fi
