#!/usr/bin/env bash
# monetization-pipeline.sh — 变现路径选择 + 接入 (Monetization Pipeline) SOP walkthrough for 公众号写作助手 (微信公众号文章 全链路 — 选题 / 标题 / 开篇 / 结构 / 行文 / 排版 / 配图 / 推送 / 涨粉 / 留言 / 二次传播 / 变现, 单 artifact = 一篇公众号推文).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="公众号写作助手 (微信公众号文章 全链路 — 选题 / 标题 / 开篇 / 结构 / 行文 / 排版 / 配图 / 推送 / 涨粉 / 留言 / 二次传播 / 变现, 单 artifact = 一篇公众号推文)"
WORKFLOW="变现路径选择 + 接入 (Monetization Pipeline)"

usage() {
  cat <<EOF
monetization-pipeline.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./monetization-pipeline.sh             # interactive
  ./monetization-pipeline.sh --dry-run
  ./monetization-pipeline.sh --json
  ./monetization-pipeline.sh --explain
  ./monetization-pipeline.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "变现路径选择 + 接入 (Monetization Pipeline)" 工作流。

一句话: 5-7 路变现选择 + 流量主 / 互选 / 知识付费 funnel 三大子流程接入 SOP.

入门 SOP 共 5 步, 失败模式自检 0 项。

相关心智模型:
  • 「单篇是产品, 账号是公司」 (Account-as-Product): 单篇推文是 product release, 账号是 company; 不为单篇 metric 牺牲账号长期资产 (定位 / voice / 读者画像).
  • 「头部效应是结构性事实, 不是个人努力问题」 (Power-Law Reality): 90% 公众号永远做不到全职收入, 不是「再努力就能突破」, 是流量 / 注意力 / 算法权重的结构性分布; 商业化必须基于此事实设计对冲 (多平台 / 多变现路径), 不卖速成幻想.

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "评估账号变现 phase (B 流当前阶段) + vertical 适配的 1-2 路主变现"
  "流量主接入 (粉丝 ≥ 500 申请 + 广告位设置 + 屏蔽类目 + 月度复盘)"
  "互选广告 / 软广 接单 (粉丝 ≥ 1 万 + 报价计算 + 平台互选 vs 直签 + 软广写作合规标识)"
  "知识付费 funnel (公众号文章 → explicit CTA 引流私域 → 私域 1-3 周培育 → 3 层漏斗销售 → 售后复购)"
  "月度商业化复盘 + 调整下季度多元化配比"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "monetization-pipeline-walkthrough"
fi
