#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 软件架构 (含 应用架构 / 系统架构 / 分布式 后端架构 / 前后端 数据流 与 数据模型 设计 / API 边界 / 可扩展性 / 演进式架构 — 不含 硬件架构 / 纯企业架构 / 纯 DevOps / 纯安全架构).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="软件架构 (含 应用架构 / 系统架构 / 分布式 后端架构 / 前后端 数据流 与 数据模型 设计 / API 边界 / 可扩展性 / 演进式架构 — 不含 硬件架构 / 纯企业架构 / 纯 DevOps / 纯安全架构)"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 场景上下文识别 (context discovery)
  9.2 NFR 与硬约束 (non-functional requirements)
  9.3 trade-off 显式化 (explicit trade-offs)
  9.4 历史与对手案例 (industry case lookup)
  9.5 演进路径 + fitness function
  9.6 AI 辅助边界 (2024-2026 当前 vertical)
  9.7 ADR 闭环 (decision record + review)

背后的心智模型:
  • 耦合 (coupling) 是唯一的硬通货 — 其它都是衍生: 软件架构本质 = 管理跨"独立变化速率"事物之间的依赖. Parnas 1972 "On the Criteria" 已说清: 模块边界要按"未来变化的轴"划, 不是按"功能流程"划. Fowler 
  • 架构 = 你早期希望做对、晚期改不动的那些决定 (the stuff that's hard to change later): Fowler 1999 给"architecture" 的工作定义: *architecture is about the important stuff, whatever that is — th
  • 没有最佳实践, 只有 context — 大厂 ≠ scale-up ≠ 创业 ≠ enterprise (4 套不同 SOP): 同一架构问题在 4 种规模公司答案完全不同 — 创业期 (5-15 eng) modular monolith + PostgreSQL + 1 cloud 是正解; 大厂 (1000+ eng, 1

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "场景上下文识别 (context discovery)"
  "NFR 与硬约束 (non-functional requirements)"
  "trade-off 显式化 (explicit trade-offs)"
  "历史与对手案例 (industry case lookup)"
  "演进路径 + fitness function"
  "AI 辅助边界 (2024-2026 当前 vertical)"
  "ADR 闭环 (decision record + review)"
)
declare -a DIM_QUESTIONS=(
  ""
  ""
  ""
  ""
  ""
  ""
  ""
)
declare -a DIM_SOURCES=(
  ""
  ""
  ""
  ""
  ""
  ""
  ""
)
declare -a DIM_OUTPUT_FORMATS=(
  ""
  ""
  ""
  ""
  ""
  ""
  ""
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
