#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for iOS 应用上架大师 (审核 + ASO + 合规 + 国内/海外多区 + 付费策略).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="iOS 应用上架大师 (审核 + ASO + 合规 + 国内/海外多区 + 付费策略)"
DIM_COUNT=5

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (5 个):
  9.1 学派语境 (用户在 6 派哪派)
  9.2 stage 边界 (0→1 上架 vs 已运营 vs scale-up)
  9.3 区域语境 (US / EU / CN / 多区)
  9.4 时效新鲜度 (12 月内 vs 老攻略)
  9.5 学派分歧识别 (6 派会怎么各自答)

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "学派语境 (用户在 6 派哪派)"
  "stage 边界 (0→1 上架 vs 已运营 vs scale-up)"
  "区域语境 (US / EU / CN / 多区)"
  "时效新鲜度 (12 月内 vs 老攻略)"
  "学派分歧识别 (6 派会怎么各自答)"
)
declare -a DIM_QUESTIONS=(
  "用户用什么术语. 判断他在 Apple 官方派 / 海外 Indie / 大厂 release eng / ASO 优化派 / 反 Apple 反垄断 / 国内合规 哪派. 决定 §2 决策规则的应用版本"
  "用户处于什么阶段. 0→1 第一次上架 / 已上架持续运营 / scale-up 多区扩展 / 拒审救火 / 政策适配"
  "用户上架的目标区域. US 默认 Apple 单家 / EU DMA 后允许 link-out + sideloading / CN 4 件套 (ICP + 算法备案 + 游戏版号 + 8-10 应用市场) / 多区策略"
  "用户依赖的政策 / 工具 / 数字是不是 12 月内的. iOS 政策高频变化 (年度 WWDC + 季度 ASC + iOS major). 老的需先 D3 复盘"
  "同一问题 6 派会怎么各自答. 揭示分歧根源是学派身份 (Apple 派 vs 反 Apple) / GTM 哲学 (Indie audience-first vs ASO 数据驱动) / 区域 (海外 vs 国内) 而非 \"对错\""
)
declare -a DIM_SOURCES=(
  "看用户原话关键词. 例: \"ARG 5.1.1 条款\" → Apple 派; \"我又被拒了\" / \"ATP 提到\" → Indie 派; \"CPP A/B / keyword 排名\" → ASO 派; \"30% Tax / DMA\" → 反 Apple 派; \"ICP 备案 / 算法备案 / 8 大市场\" → 国内合规派"
  "用户问题的具体动作 (e.g. \"我准备提审\" → 0→1; \"我又被拒了\" → 拒审救火; \"扩到 EU 还是 CN\" → 多区扩展; \"Privacy Manifest 怎么搞\" → 政策适配)"
  "用户原话区域线索 (e.g. \"在国内上架\" → CN; \"Lemon Squeezy\" → 海外 indie; \"DMA 后\" → EU; \"多区策略\" → 多区)"
  "用户引用的 deadline / 规则 / 工具版本. 例: \"Privacy Manifest 强制 2024-05-01\" / \"iOS 26 SDK 2026-04-28\" / \"Age Rating 5 档 2026-01-31\" / \"DMA 2024-03-07\" 都是 12 月内强制"
  "§7 智识谱系 6 派对照矩阵 + §1.4 / 1.5 / 1.6 跨派 mental model"
)
declare -a DIM_OUTPUT_FORMATS=(
  "一行学派标签 (e.g. \"用户在 Indie 派, 最相关心智模型 1.6 拒绝是日常 + 决策规则 D2 Resolution Center 短回复\")"
  "stage 标签 + 适用决策规则号 (e.g. \"stage = 拒审救火, 走 D2 + W2 工作流\")"
  "区域 + 必应 obligations (e.g. \"区域 = CN, 必应 D5 + D7 + D8 国内 4 件套, 不能抄海外 link-out\")"
  "时效标签 (新鲜 / 12 月内 / 老攻略需复盘) + 强制 deadline 提醒"
  "列出 2-3 派的不同 take, 标\"分歧根源 = X\". 用户自己看选哪派, 不强加"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
