#!/usr/bin/env bash
# sop-5-phase-aia-dual.sh — 单项目设计 SOP (5 phase, AIA + 中国 dual) SOP walkthrough for 现代建筑设计 (从 concept 草图到施工图与现场服务的整套设计流程, 含 BIM / 可持续 / 参数化 / 在地性 模块, 全球语境 + 中国本土实践并重).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="现代建筑设计 (从 concept 草图到施工图与现场服务的整套设计流程, 含 BIM / 可持续 / 参数化 / 在地性 模块, 全球语境 + 中国本土实践并重)"
WORKFLOW="单项目设计 SOP (5 phase, AIA + 中国 dual)"

usage() {
  cat <<EOF
sop-5-phase-aia-dual.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./sop-5-phase-aia-dual.sh             # interactive
  ./sop-5-phase-aia-dual.sh --dry-run
  ./sop-5-phase-aia-dual.sh --json
  ./sop-5-phase-aia-dual.sh --explain
  ./sop-5-phase-aia-dual.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "单项目设计 SOP (5 phase, AIA + 中国 dual)" 工作流。

入门 SOP 共 5 步, 失败模式自检 0 项。

相关心智模型:
  • 三件事原则 — 可视化 ≠ 设计 ≠ 可建造 (visualization ≠ design ≠ buildable): 渲染图 / 数字模型 / 实建物 是三个独立 artifact, 各有不同的成功标准 + 不同读者 + 不同保鲜期; 混淆三者是 90% (业内估) 业主-建筑师冲突 + 项目失约的根因.
  • 三轴决定 — Program × Site × Tectonics (everything else is decoration): 每个设计决策必须在三轴上同时合理 — Program (人在里面做什么) × Site (在哪 + 什么气候 + 什么文化) × Tectonics (用什么材料 + 什么节点 + 谁来造); 缺一轴

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "Programming / 需求定位 (1-4 周) → OPR / Program Doc / Site Analysis / fee proposal / BOD baseline."
  "Schematic Design / 方案设计 (4-10 周) → SD package: site plan / 主要平面 / sections / 立面 / 渲染 / sketch model + 早期 ROM cost estimate."
  "Design Development / 扩初 / 初设 (6-14 周) → DD set 1:100 + MEP federated model LOD 300 + 中国初步设计 + 概算 + 关键节点详图."
  "Construction Documents / 施工图 (8-20 周) → 全套 CD 图纸 (US: 150-300 张; 中国: 300-800 张) + spec book + permit set + 图审 (中国) + final cost estimate."
  "Bidding & Construction Administration / 招标 + 现场服务 (整个施工期 6-36 月) → RFI / submittal / ASI / CO log + field reports + Certificate of Substantial Completion + punch list + record drawings."
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "sop-5-phase-aia-dual-walkthrough"
fi
