#!/usr/bin/env bash
# sop-5-type.sh — 事务所类型 SOP (5 type) SOP walkthrough for 现代建筑设计 (从 concept 草图到施工图与现场服务的整套设计流程, 含 BIM / 可持续 / 参数化 / 在地性 模块, 全球语境 + 中国本土实践并重).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="现代建筑设计 (从 concept 草图到施工图与现场服务的整套设计流程, 含 BIM / 可持续 / 参数化 / 在地性 模块, 全球语境 + 中国本土实践并重)"
WORKFLOW="事务所类型 SOP (5 type)"

usage() {
  cat <<EOF
sop-5-type.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./sop-5-type.sh             # interactive
  ./sop-5-type.sh --dry-run
  ./sop-5-type.sh --json
  ./sop-5-type.sh --explain
  ./sop-5-type.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "事务所类型 SOP (5 type)" 工作流。

入门 SOP 共 5 步, 失败模式自检 0 项。

相关心智模型:
  • 三件事原则 — 可视化 ≠ 设计 ≠ 可建造 (visualization ≠ design ≠ buildable): 渲染图 / 数字模型 / 实建物 是三个独立 artifact, 各有不同的成功标准 + 不同读者 + 不同保鲜期; 混淆三者是 90% (业内估) 业主-建筑师冲突 + 项目失约的根因.
  • 三轴决定 — Program × Site × Tectonics (everything else is decoration): 每个设计决策必须在三轴上同时合理 — Program (人在里面做什么) × Site (在哪 + 什么气候 + 什么文化) × Tectonics (用什么材料 + 什么节点 + 谁来造); 缺一轴

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "评估 typology + 团队规模 + 设计费率 + 周期 + 客户来源 — 5 type: boutique 5-30 人 / 中型 firm 50-150 人 / starchitect 100-500 人 / 中国设计院 1000-5000 人 / 独立 lone wolf 4-15 人 (或 sole-prac 1-3 人)."
  "选定 type 后建立对应商业模式 — boutique: 业主主动 + monograph + 教席; 中型: 70% repeat client + 30% RFQ; starchitect: invitation + brand premium; 设计院: 资质 + 招投标 + 政府关系; lone wolf: 95% referral + 内容营销."
  "配置对应团队结构 — boutique: 扁平 + principal 画图; 中型: matrix + sector vertical; starchitect: HQ + global office + R+D lab; 设计院: 院 → 所 → 工作室 → 项目组 + 全专业; lone wolf: 1 principal + 高 outsource."
  "锁 typology mix + 不接超 capacity 项目 (boutique 接大项目崩 / lone wolf 接公建崩 / starchitect 不接小私宅)."
  "持续投入 brand asset (boutique: 出版 + 教学 / 中型: sector thought leadership / starchitect: monograph + 双年展 / 设计院: 资质 + 关系 / lone wolf: YouTube + Instagram)."
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "sop-5-type-walkthrough"
fi
