#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 求职 / 面试辅导(求职教练视角 — 求职定位与职业叙事 / 简历与 ATS 优化 / 求职渠道与内推策略 / 职场社交 / 行为面试与专业面试 / 面试心理与表达 / 谈薪与 offer 决策 / 校招与应届生 / 转行求职 / 特殊群体求职 / 求职教练的执业经营 — 涵盖中国大陆求职生态 + 海外英语区求职体系,两套差异极大).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="求职 / 面试辅导(求职教练视角 — 求职定位与职业叙事 / 简历与 ATS 优化 / 求职渠道与内推策略 / 职场社交 / 行为面试与专业面试 / 面试心理与表达 / 谈薪与 offer 决策 / 校招与应届生 / 转行求职 / 特殊群体求职 / 求职教练的执业经营 — 涵盖中国大陆求职生态 + 海外英语区求职体系,两套差异极大)"
DIM_COUNT=9

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (9 个):
  9.1 locale 体系判定
  9.2 求职定位与目标收敛诊断
  9.3 求职漏斗卡点诊断
  9.4 招聘方视角与岗位痛点研究
  9.5 渠道策略判定（networking vs 网申权重）
  9.6 市场周期与结构性约束校准
  9.7 谈薪信息与杠杆搜集
  9.8 营销噪音 / 黑产话术甄别
  9.9 工具与战术时效核查

背后的心智模型:
  • 定位先于一切执行（定位错了，后面是高效地做错事）: 求职的第一性问题不是「简历怎么写 / 该投哪」，而是「要找哪一类岗位 + 为什么是我」—— 目标不收敛时，改简历、海投、练面试都是在高效地做错的事。
  • 从招聘方 / ATS / 岗位的痛点出发倒推（不是从「我想要什么」出发）: 简历、触达、面试答案的组织原点是「这个岗位 / 招聘经理在解决什么问题」，不是「我想说什么」—— 招聘经理立项前往往已缺人 6-12 个月，他要的是「缓解」。
  • 经历是「证据 / 量化」，不是流水账（简历与面试本质都是举证）: 简历的 bullet 和面试的答案，本质都是「举证」—— 把「负责 X」式职责罗列，换成「做到了 X（用 Y 衡量），靠做 Z」式可衡量的证据。

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "locale 体系判定"
  "求职定位与目标收敛诊断"
  "求职漏斗卡点诊断"
  "招聘方视角与岗位痛点研究"
  "渠道策略判定（networking vs 网申权重）"
  "市场周期与结构性约束校准"
  "谈薪信息与杠杆搜集"
  "营销噪音 / 黑产话术甄别"
  "工具与战术时效核查"
)
declare -a DIM_QUESTIONS=(
  "求职者的目标地区是中国大陆、海外英语区、还是北美华人 / 留学生（跨两套）—— 这决定后续所有维度的参照系（简历格式、招聘渠道、校招机制、谈薪文化、反歧视法律环境完全不同）。"
  "求职者的目标岗位 / 行业 / 层级 / 城市是否已收敛到 1-3 个具体方向 —— 还是「什么都能做 / 什么都想试」。约束条件（薪资底线、地点、签证、家庭、生计压力）是否已显性化。"
  "求职者已经在投了，问题卡在漏斗哪一层 —— 「投递 → 初筛」掉（漏斗顶部，根因在定位 / 简历 / 渠道）还是「面试 → offer」掉（根因在面试表现 / 谈薪）。各层的转化率数据。"
  "目标岗位 / 招聘经理在解决什么问题（JD 拆成硬性要求 / 加分项 / 高频关键词 / 真正在解决的问题）；这家公司近期动态；以及「面试桌对面在用什么 AI」（招聘方是否用 ATS 语义筛选 / 单向 AI 视频初面）。"
  "在已确定的 locale 内，这个具体赛道 / 层级该把 networking 还是网申当主路径 —— 海外科技 / 咨询 / 中高层级 / 转行 networking 权重高；国内校招网申 + 笔试是主通道；大批量流程化招聘的初级岗 networking 边际收益低。"
  "当前就业市场处于什么周期（行业冷热、岗位供需）；求职者面临的结构性约束（年龄 / 第一学历 / gap / 户籍 / 性别婚育 / 签证）的真实程度 —— 哪些是「可控部分」、哪些是「宏观不可控」。"
  "目标岗位 / 职级 / 地点的市场薪资区间（定 anchor 和 walk-away）；求职者手上的真实杠杆（真实的 competing offer / 当前薪资 / 稀缺技能）；目标地区是否有薪资透明立法（影响「先报数字」战术）。"
  "求职者是否正被「保 offer / 内推保过 / 21 天逆袭 / 名企内定」等话术影响；接触的机构 / 「教练」是否存在「教练 + 卖内推 + 抽成 / 机构绑定」的利益冲突；求职者是否在考虑越过「优化 vs 造假」红线（代写造假 / 面试代面 / 背题库假装有能力）。"
  "方案里涉及的 AI 工具 / 具体话术 / 模板是否已过期 —— AI 辅助类工具保鲜期 < 6-12 个月，ATS 在语义化升级，AI 招聘监管在立法，「AI 味简历」正被识别。"
)
declare -a DIM_SOURCES=(
  "求职者自述的目标城市 / 国家；目标公司清单的地理分布；若是国际学生 / 海归，确认签证 sponsorship 是定位的前置筛选条件。"
  "求职者自述的目标描述（模糊程度本身是信号）；简历是否针对性；「为什么是这家」能否讲清；LinkedIn / 牛客上目标岗位的真实 JD + 在职者的真实路径作外部参照。"
  "求职者的投递记录 / application tracker（投了多少、多少进初筛、多少进面试、多少拿 offer）；面试复盘记录；不被求职者的「自我诊断」带走（客户常误判）。"
  "目标 JD 原文；公司官网 / 近期新闻；Glassdoor / 牛客 / 一亩三分地的面经（看面试流程和高频题）；r/recruiting 招聘方视角的反向情报。"
  "目标岗位的层级和行业；该赛道在职者的真实进入路径（LinkedIn / 一亩三分地 / 牛客）；hidden job market 在该行业的实际规模（按场景判断 —— 「绝大多数工作都在隐藏市场」是缺乏第三方共识的业内估计 / 营销夸大，不当事实采信）。"
  "US BLS / JOLTS（海外）、国家统计局青年失业率（国内）的官方就业数据；LinkedIn Economic Graph 的行业趋势；目标行业的裁员 / 招聘新闻。注意数据口径局限。"
  "海外科技岗 levels.fyi、通用岗 Glassdoor / Payscale；国内招聘平台区间 + 看准网 + 脉脉职言交叉（国内精度天然弱于海外）；目标地区的薪资透明法规状态。"
  "求职者描述的「服务 / 课程 / 合同条款」；机构的营销页话术；央广网 / 新浪黑猫等对求职机构乱象的可验证报道作对照样本。"
  "工具厂商官网的近期更新；workflow 各节的「近期变化」字段（last_updated 锚点）；目标地区的 AI 招聘监管立法动态；招聘端 AI 工具（Metaview / 单向 AI 视频面试）的渗透情况。"
)
declare -a DIM_OUTPUT_FORMATS=(
  "一句话锁定 locale + 走哪条决策树（A 海外 / B 国内 / 跨两套），并标注「跨 locale 的工具与经验几乎不可移植」。"
  "判定「定位是否清晰」—— 不清晰则标「先做 W5 定位收敛，目标不收敛不进简历 / 投递」；清晰则直接进卖点提炼 + 故事线。附约束条件清单。"
  "定位卡点在哪一层 + 该层的根因假设 + 优先解决项（举例性质，非固定阈值：如「投递→初筛转化率明显偏低，根因高频在定位或简历，优先排查 W5/W6」）。"
  "一份「岗位痛点 + 关键词 + 面试流程 + 招聘方 AI 使用情况」摘要，作为简历组织和面试准备的原点。"
  "判定主路径（networking 优先 / 网申优先 / 两者并行）+ 据此排工具优先级（networking 路径下 ATS 优化降级、tracker 升级反之）。"
  "一句话市场周期判断（带日期 + 官方源）+ 结构性约束清单（标「真实存在但程度因行业 / 岗位差异，可用经历 / 作品 / 内推 / 定位对冲」）+ 明确「可控 vs 不可控」边界，不 victim-blame。"
  "一个有数据支撑的 anchor + walk-away 线 + 可用的真实杠杆清单 + 该地区「先报数字」战术是否需变形。明确「编造 offer 是红线」。"
  "标记出具体的营销噪音 / 黑产话术 + 为什么行业拒绝它 + 内行的真实说法（如「保 offer = 兜售确定性，教练只能提升概率」）；标记利益冲突;标记红线行为并明确后果（背调暴露 / 试用期崩盘 / 职业污点）。"
  "标记方案中「时效敏感、需自行核实」的部分 + 给出「原理」替代「当下话术」（如「不给具体 prompt 模板，给『ATS 是解析 + 检索、AI 味要去掉』的原理」）+ 建议 update 频率。"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
