#!/usr/bin/env bash
# kfs.sh — KFS 组合营销 (中大品牌完整投放) SOP walkthrough for 小红书运营.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="小红书运营"
WORKFLOW="KFS 组合营销 (中大品牌完整投放)"

usage() {
  cat <<EOF
kfs.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./kfs.sh             # interactive
  ./kfs.sh --dry-run
  ./kfs.sh --json
  ./kfs.sh --explain
  ./kfs.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "KFS 组合营销 (中大品牌完整投放)" 工作流。

一句话: KOL × Feeds × Search 三件套组合投放 — 内容摸索 → 内容验证 → 规模化的标准 90 天打法.

入门 SOP 共 3 步, 失败模式自检 4 项。

相关心智模型:
  • 内容是种草, 不是销售 (核心 PASS): 小红书的内容逻辑是「让用户自己想买」, 不是「告诉用户来买」. 硬广直发必死.
  • 数据反馈驱动迭代 (核心 PASS): 小红书运营是**测试驱动的**, 不是经验驱动的 — 每篇笔记都是 A/B 测试.

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**阶段 1 内容摸索** (Day 1-30, K:F:S = 7:3:0):"
  "**阶段 2 内容验证** (Day 30-60, K:F:S = 5:3:2):"
  "**阶段 3 规模化** (Day 60-90, K:F:S = 4:4:2):"
)
declare -a FAILURE_MODES=(
  "阶段 1 跳过直接上聚光 → 内容没验证, 投流跑不动 → 投放预算浪费"
  "头部 KOL ROI 不如中腰部 → 多数类目下中腰部 ROI 更高, 不要押头部"
  "Search 不做品牌词 → 别人 SEO 抢走你的搜索词"
  "K:F:S 比例死板, 不按品牌阶段动态调"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "kfs-walkthrough"
fi
