#!/usr/bin/env bash
# workflow-3.sh — 跨平台联动 (小红书种草 + 站外转化) SOP walkthrough for 小红书运营.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="小红书运营"
WORKFLOW="跨平台联动 (小红书种草 + 站外转化)"

usage() {
  cat <<EOF
workflow-3.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-3.sh             # interactive
  ./workflow-3.sh --dry-run
  ./workflow-3.sh --json
  ./workflow-3.sh --explain
  ./workflow-3.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "跨平台联动 (小红书种草 + 站外转化)" 工作流。

一句话: 小红书种草 + 天猫 / 抖音 / 京东 / 美团等站外平台直播 / 闭环转化, 跨平台 ROI 归因.

入门 SOP 共 5 步, 失败模式自检 4 项。

相关心智模型:
  • 内容是种草, 不是销售 (核心 PASS): 小红书的内容逻辑是「让用户自己想买」, 不是「告诉用户来买」. 硬广直发必死.
  • 数据反馈驱动迭代 (核心 PASS): 小红书运营是**测试驱动的**, 不是经验驱动的 — 每篇笔记都是 A/B 测试.

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**种草联盟接入** (Week 1): 跟小红书 BD / 代理对接, 开通小红星 (X 阿里) / 小红盟 (X 京东) / 小红链 (X 唯品会等)"
  "**种草直达配置** (Week 2): 笔记里挂跳转链接 (天猫 / 京东 / 美团等), 用户点击直接跳第三方电商"
  "**跨平台投放节奏** (持续):"
  "**AIPS 人群资产沉淀** (持续): 每月看 A / I / TI / P / S 五个层级人群, 重点扩 TI → P (深度兴趣 → 购买)"
  "**ROI 归因闭环** (季度): 跟代理 / 平台跑后链路数据 — 哪些种草内容真正贡献了站外 GMV"
)
declare -a FAILURE_MODES=(
  "种草联盟接通了但没配 ROI 归因 → 数据看不到, 老板不批预算"
  "小红书内容做得好但站外承接不力 → 用户跳过去转化不下来"
  "跨平台节奏脱节 → 小红书种草 ≠ 直播间需求, 浪费种草人群"
  "AIPS 人群资产看了不动 → 5 层人群每月不扩, 沉淀价值随时间衰减"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-3-walkthrough"
fi
