#!/usr/bin/env bash
# workflow-2.sh — 矩阵号 + 数据迭代 (中大品牌长期路径) SOP walkthrough for 小红书运营.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="小红书运营"
WORKFLOW="矩阵号 + 数据迭代 (中大品牌长期路径)"

usage() {
  cat <<EOF
workflow-2.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-2.sh             # interactive
  ./workflow-2.sh --dry-run
  ./workflow-2.sh --json
  ./workflow-2.sh --explain
  ./workflow-2.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "矩阵号 + 数据迭代 (中大品牌长期路径)" 工作流。

一句话: 5-30 个矩阵号同步运营, 数据驱动持续迭代, 抗算法波动 + 抗单点风险.

入门 SOP 共 5 步, 失败模式自检 4 项。

相关心智模型:
  • 内容是种草, 不是销售 (核心 PASS): 小红书的内容逻辑是「让用户自己想买」, 不是「告诉用户来买」. 硬广直发必死.
  • 数据反馈驱动迭代 (核心 PASS): 小红书运营是**测试驱动的**, 不是经验驱动的 — 每篇笔记都是 A/B 测试.

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**矩阵号规划** (Week 1): 按人群 (年龄 / 性别 / 价位 / 风格) 分层. 每个矩阵号锁定 1-2 个细分人群."
  "**账号矩阵搭建** (Week 1-3): 5-10 个账号同步搭, 不同手机号 / 不同设备 / 不同 IP. 每个号有不同昵称 / 头像 / 简介定位."
  "**内容生产分工** (Week 3+): 头部矩阵号做精品 (周 3-5 篇) + 中腰部铺量 (周 5-10 篇) + KOC 长尾 (周 1-3 篇)."
  "**数据迭代闭环** (持续): 周复盘 — 哪些选题爆了 / 哪些死了. 月复盘 — 矩阵号方向是否要调整."
  "**合规边界守住** (持续): 不报备的私单一概不接 / 不刷量 / 不用同设备同 IP / 不发同一条内容."
)
declare -a FAILURE_MODES=(
  "矩阵号同设备 / 同 IP 管理 → 平台识别 → 整组限流"
  "矩阵号内容同质化 → 平台判定为「营销号」 → 推荐量降权"
  "不做数据迭代 → 矩阵号沦为僵尸号 → 浪费维护成本"
  "矩阵规模过快 → 平台合规边界一动就团灭"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-2-walkthrough"
fi
