#!/usr/bin/env bash
# contract-review.sh — 合同审核 (Contract Review) SOP walkthrough for 中国法律执业.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="中国法律执业"
WORKFLOW="合同审核 (Contract Review)"

usage() {
  cat <<EOF
contract-review.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./contract-review.sh             # interactive
  ./contract-review.sh --dry-run
  ./contract-review.sh --json
  ./contract-review.sh --explain
  ./contract-review.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "合同审核 (Contract Review)" 工作流。

一句话: 从客户提交合同到出审核意见的标准流程 (条款风险 + 法律风险 + 商业风险 三维度)

入门 SOP 共 5 步, 失败模式自检 12 项。

相关心智模型:
  • 程序先于实体 — 时效 / 管辖 / 主体 错一个就输: 实体法 (民法典 / 刑法 / 公司法) 决定「谁对谁错」, 程序法 (民诉 / 刑诉 / 行诉) 决定「能不能进法院」. 程序错了, 实体上多对都没用.
  • 法律不是结论, 是程序 + 论证 — 「依法」≠「我说的就对」: 法律给的不是「答案」, 是「论证路径 + 证据规则 + 程序」. 同一事实下不同律师 / 不同法官可能得出不同结果, 这不是错, 是法律的本质.

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**了解背景** — 当事人 / 业务背景 / 客户角色 (买 / 卖 / 借 / 投 / 雇) + 客户重点关注 (价格 / 履约 / 责任 / 退出)"
  "**结构性审查** —"
  "**法律风险审查** —"
  "**商业风险审查** —"
  "**审核意见输出** —"
)
declare -a FAILURE_MODES=(
  "**不了解业务背景直接审条款** → 形式审查, 错失关键风险"
  "**没签字 / 没审核范围** → 范围争议 + 律师责任风险"
  "**强制性规定遗漏** → 条款无效, 客户损失"
  "**仲裁 / 管辖条款被忽略** → 争议时无法主张"
  "**数据合规漏项** → 涉外 / 个保案件后果严重"
  "**元数据没清除** → 内部讨论 / 修订记录暴露 给对方"
  "**「合理」「适当」「双方协商」 模糊条款不指出** → 履约时分歧无依据"
  "**客户告知不充分** → 风险责任律师承担"
  "**关键决策点**:"
  "Red 必须改 vs Yellow 建议改: 强制性规定 / 致命漏洞 vs 商业不利 / 模糊"
  "仲裁 vs 法院: 标的额 + 涉外 + 保密 + 执行地 + 程序速度"
  "适用法律: 涉外多选目的地 / 中立第三方法律, 国内一般中国法"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "contract-review-walkthrough"
fi
