#!/usr/bin/env bash
# workflow-3.sh — 涉外商事争议 (国际仲裁 / 跨境执行) SOP walkthrough for 中国法律执业.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="中国法律执业"
WORKFLOW="涉外商事争议 (国际仲裁 / 跨境执行)"

usage() {
  cat <<EOF
workflow-3.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-3.sh             # interactive
  ./workflow-3.sh --dry-run
  ./workflow-3.sh --json
  ./workflow-3.sh --explain
  ./workflow-3.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "涉外商事争议 (国际仲裁 / 跨境执行)" 工作流。

一句话: 涉外商事合同纠纷 — 国际仲裁 / 跨境诉讼 / 跨境执行 标准流程

入门 SOP 共 6 步, 失败模式自检 12 项。

相关心智模型:
  • 程序先于实体 — 时效 / 管辖 / 主体 错一个就输: 实体法 (民法典 / 刑法 / 公司法) 决定「谁对谁错」, 程序法 (民诉 / 刑诉 / 行诉) 决定「能不能进法院」. 程序错了, 实体上多对都没用.
  • 法律不是结论, 是程序 + 论证 — 「依法」≠「我说的就对」: 法律给的不是「答案」, 是「论证路径 + 证据规则 + 程序」. 同一事实下不同律师 / 不同法官可能得出不同结果, 这不是错, 是法律的本质.

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**争议条款审查** — 仲裁 vs 诉讼? 仲裁机构 (CIETAC / SHIAC / SCIA / 国际机构 ICC / SIAC / HKIAC) + 仲裁地 (重要 — 决定程序法 + 撤销 / 不予执行管辖) + 适用法律 + 语言"
  "**管辖权评估** —"
  "**法律适用** —"
  "**证据收集** —"
  "**仲裁 / 诉讼程序** —"
  "**跨境执行** —"
)
declare -a FAILURE_MODES=(
  "**仲裁条款失效** → 仲裁不成 + 法院管辖也不成 → 灾难"
  "**跨境执行困难** → 赢了仲裁 / 判决拿不到钱"
  "**法律适用错** → 用中国法解释外国法主张, 判决不利"
  "**跨境取证违法** → 部分国家禁止外国律师调查, 操作不当违法"
  "**公证 / 认证缺失** → 涉外文书在境外不被采信 (Apostille 简化前更严重)"
  "**程序时间表失控** → 国际仲裁 / 跨境诉讼时间长 (1-3 年常见), 客户不耐"
  "**多法系沟通失误** → 普通法系 vs 大陆法系 vs 中国法 概念不互通"
  "**关键决策点**:"
  "仲裁 vs 诉讼: 涉外多倾向仲裁 (机密 + 中立 + 跨境执行 + 程序灵活)"
  "仲裁机构选择: 案件性质 + 当事人偏好 + 仲裁员资源 + 程序成本"
  "仲裁地: 中立 + 程序法成熟 + 法院支持仲裁 (新加坡 / 香港 / 瑞士 / 伦敦 / 纽约)"
  "适用法律: 当事人协议优先 + 国际惯例 + 强制性规定"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-3-walkthrough"
fi
