#!/usr/bin/env bash
# workflow-2.sh — 商事合同审核流程 SOP walkthrough for 法律执业 (中国法).
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="法律执业 (中国法)"
WORKFLOW="商事合同审核流程"

usage() {
  cat <<EOF
workflow-2.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-2.sh             # interactive
  ./workflow-2.sh --dry-run
  ./workflow-2.sh --json
  ./workflow-2.sh --explain
  ./workflow-2.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "商事合同审核流程" 工作流。

一句话: 客户拿合同要求律师审核到出意见的标准动作

入门 SOP 共 6 步, 失败模式自检 3 项。

相关心智模型:
  • 程序正义先于实体: 程序错了, 实体再对也白搭。诉讼时效 / 管辖 / 当事人主体 / 证据规则的程序问题, 一个错了案子就死了。
  • 证据决定胜负, 不是法条: 法条人人会查, 但证据是子弹。证据不到「高度盖然性」标准, 法条再硬也撑不起来。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "看合同主体 + 类型 (买卖 / 服务 / 借贷 / 保密 / 涉外)"
  "重点审违约救济条款 — 违约金 / 解约权 / 管辖 / 法律适用"
  "审权利义务对等性 — 客户的权利是否充分 / 对方义务是否具体"
  "审风险分配 — 不可抗力 / 第三方责任 / 知识产权"
  "审涉外因素 (如适用) — 法律适用 + 争议解决地 + 语言版本优先"
  "出意见 — 必改 vs 建议改 vs 接受 三档分级"
)
declare -a FAILURE_MODES=(
  "只看权利义务不看违约救济 → 履行出问题没救济路径"
  "涉外合同没审法律适用条款 → 争议时管辖混乱"
  "不分级给客户全部修改建议 → 客户不知道哪个必改"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-2-walkthrough"
fi
