#!/usr/bin/env bash
# hallux-valgus.sh — 拇外翻 (Hallux Valgus) 评估 + 决策 SOP walkthrough for 足踝外科.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="足踝外科"
WORKFLOW="拇外翻 (Hallux Valgus) 评估 + 决策"

usage() {
  cat <<EOF
hallux-valgus.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./hallux-valgus.sh             # interactive
  ./hallux-valgus.sh --dry-run
  ./hallux-valgus.sh --json
  ./hallux-valgus.sh --explain
  ./hallux-valgus.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "拇外翻 (Hallux Valgus) 评估 + 决策" 工作流。

一句话: 从拇外翻初诊 (角度 + 症状 + 期望评估) 到术式选择 (保守 vs 第三代微创 vs 传统切开) 的标准流程

入门 SOP 共 7 步, 失败模式自检 10 项。

相关心智模型:
  • 保守治疗优先于手术 (3-6 月黄金期): 90% 的足踝慢性病变不需要手术, 但很多医生 / 患者直接跳到手术决策, 跳过保守治疗黄金期.
  • 影像学发现 ≠ 临床症状原因 (跟着症状走): MRI 看到的「异常」很多跟患者主诉无关. 影像跟症状对不上时, 跟着症状走, 不是跟着影像走.

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**病史采集** — 主诉 (疼痛位置 / 严重度 / 进展速度 + 鞋具问题 + 美观期望) + 既往保守治疗 + 家族史 (拇外翻强遗传倾向) + 患者职业 / 活动需求"
  "**负重 X 线** (必须负重位):"
  "**严重度分级**:"
  "**体格检查**: 第一 MTP 关节炎 (僵硬 / 疼痛弧度) + 第二 MTP 转移性痛 + 平足 / 平足合并 (常见) + 跟腱挛缩 (Silverskiöld)"
  "**保守治疗 (3-6 月)**:"
  "**手术评估** (保守失败 / 重度 / 患者强烈期望):"
  "**术后管理**:"
)
declare -a FAILURE_MODES=(
  "**保守治疗够都不试就手术** → 轻度患者不必要手术"
  "**单纯按 HVA 选术式** → 忽略 IMA / DMAA / 关节炎 / 合并畸形"
  "**不矫平足 / 不矫挛缩** → 复发率高"
  "**患者期望管理失败** (期望「漂亮的脚」) → 投诉 + 满意度低"
  "**第三代微创学习曲线没过就上** → 复杂畸形效果差"
  "**关节置换乱用** → 失败率高 (vs 融合)"
  "**关键决策点**:"
  "保守 vs 手术: 6 月规范保守失败 + 影响日常 / 鞋具 / 工作"
  "微创 vs 开放: 轻 + 中度 → 微创首选; 重度 / 关节炎 / 复杂 → 开放"
  "融合 vs 截骨: 关节炎晚期 / 严重畸形 / 翻修 → 融合; 否则截骨"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "hallux-valgus-walkthrough"
fi
