#!/usr/bin/env bash
# vs.sh — 终末期踝关节炎 — 关节置换 vs 关节融合 决策 SOP walkthrough for 足踝外科.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="足踝外科"
WORKFLOW="终末期踝关节炎 — 关节置换 vs 关节融合 决策"

usage() {
  cat <<EOF
vs.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./vs.sh             # interactive
  ./vs.sh --dry-run
  ./vs.sh --json
  ./vs.sh --explain
  ./vs.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "终末期踝关节炎 — 关节置换 vs 关节融合 决策" 工作流。

一句话: 终末期踝关节炎 (post-traumatic / OA / RA) 选关节置换 (TAA) vs 关节融合 (TAR) 的决策框架

入门 SOP 共 6 步, 失败模式自检 11 项。

相关心智模型:
  • 保守治疗优先于手术 (3-6 月黄金期): 90% 的足踝慢性病变不需要手术, 但很多医生 / 患者直接跳到手术决策, 跳过保守治疗黄金期.
  • 影像学发现 ≠ 临床症状原因 (跟着症状走): MRI 看到的「异常」很多跟患者主诉无关. 影像跟症状对不上时, 跟着症状走, 不是跟着影像走.

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "**病史 + 体格**: 病因 (外伤 / OA / RA / 神经性 / 骨坏死) + 严重度 (VAS / AOFAS Score) + 既往治疗 + 患者期望 (运动需求? 生活质量?) + 合并畸形 (力线 / 韧带不稳)"
  "**影像评估**:"
  "**保守治疗已失败确认**: 鞋具 / 矫形器 / 注射 / NSAIDs / 物理治疗 全做过且无效"
  "**决策 — 置换 (TAA) vs 融合 (TAR)**:"
  "**术前规划**:"
  "**术后管理 + 长期 follow-up**:"
)
declare -a FAILURE_MODES=(
  "**不严格选患者** — 严重畸形 / 韧带不稳 / 骨缺损 强行 TAA → 失败率高"
  "**不矫力线** — TAA 不矫力线 → 假体偏载 + 早期磨损松动"
  "**不评估邻近关节** — TAR 后距下 / 距舟 应力大 → 加速退变"
  "**不患教 + 期望管理** — 患者期望「跑跳如常」 → 投诉"
  "**不长期 follow up** → 错过翻修窗口"
  "**HINTEGRA H3 (Mobile-bearing) 在 US 失败率高** — FDA 2023 警示, 部分医院暂停植入 (国内引进早, 长期 data 仍待)"
  "**关键决策点**:"
  "年轻 (< 50) + 高需求 → 倾向融合 (失败长期低)"
  "中老年 (≥ 50) + 适应症 → 倾向置换"
  "严重畸形 / 不稳 / 翻修 → 融合"
  "双下肢 / 多关节融合 → 倾向置换 (避免完全 disability)"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "vs-walkthrough"
fi
