#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 公众号写作助手 (微信公众号文章 全链路 — 选题 / 标题 / 开篇 / 结构 / 行文 / 排版 / 配图 / 推送 / 涨粉 / 留言 / 二次传播 / 变现, 单 artifact = 一篇公众号推文).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="公众号写作助手 (微信公众号文章 全链路 — 选题 / 标题 / 开篇 / 结构 / 行文 / 排版 / 配图 / 推送 / 涨粉 / 留言 / 二次传播 / 变现, 单 artifact = 一篇公众号推文)"
DIM_COUNT=5

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (5 个):
  9.1 选题 fit 校验 (我的号 × 这一议题)
  9.2 议题当前生态热度 + 同 vertical TOP 5 已写视角扫描
  9.3 voice + 结构 + 大纲选择
  9.4 平台规则自审 (上线安全 check)
  9.5 变现路径 + 时效 / 复用 校准

背后的心智模型:
  • 「单篇是产品, 账号是公司」 (Account-as-Product): 单篇推文是 product release, 账号是 company; 不为单篇 metric 牺牲账号长期资产 (定位 / voice / 读者画像).
  • 「头部效应是结构性事实, 不是个人努力问题」 (Power-Law Reality): 90% 公众号永远做不到全职收入, 不是「再努力就能突破」, 是流量 / 注意力 / 算法权重的结构性分布; 商业化必须基于此事实设计对冲 (多平台 / 多变现路径), 不卖速成幻想.
  • 「短期套利 vs 长期 IP 是真分歧, 必须选边」 (Strategy Bifurcation): 公众号写作策略有两条互斥路径 — 短期流量套利 (咪蒙 / AI 灰产范式) vs 长期 IP 资产 (六神磊磊 / 万维钢 / 张小龙长期主义范式), 中间路线最差. 必须明确选边, 不能两头讨好.

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "选题 fit 校验 (我的号 × 这一议题)"
  "议题当前生态热度 + 同 vertical TOP 5 已写视角扫描"
  "voice + 结构 + 大纲选择"
  "平台规则自审 (上线安全 check)"
  "变现路径 + 时效 / 复用 校准"
)
declare -a DIM_QUESTIONS=(
  "(a) 这一议题 vs 我账号定位 / vertical 相符度; (b) 我读者画像 (年龄 / 性别 / 城市 / 阅读偏好) 对该议题兴趣度; (c) 我历史推文 同主题数据 (打开率 / 完读 / 在看); (d) 我有没有跨界优势 (信息差 / 视角差)"
  "(a) 微信指数 + 百度指数 + 微博热搜 + 抖音热榜 + 知微事件库 5 平台热度交叉; (b) 是否已 ≥ 24h 发酵 (公众号是慢平台, 不抢首发); (c) 同 vertical TOP 5 KOL 近 7 天已写该议题的角度摘要 (新榜 + 飞瓜 + 看一看 + 知微); (d) 我能找到的 反差视角 / 数据角度 / 行业人 insider 视角"
  "(a) 主题适合哪种 voice register (§7 段子化 / 知识系统 / 文化考据 / 情感生活 / 商业咨询 5 派之一); (b) 哪种结构 (短平快 500-1500 字 / 长深度 3000-8000 字 / 故事化 1500-3000 字); (c) 哪种骨架 (三段论 / 总分总 / 倒金字塔 / 主张-论证-反驳 / 时间线 / 对比); (d) 钩子模板 (8 选 1) + 大纲骨架"
  "8 项自审 — (a) 标题党边界 (能 deliver 吗 / 信息流前 22 字露出 OK 吗); (b) 配图侵权 (视觉中国系 / 百度搜图 / AI 名人脸 红线); (c) 链接合规 (外链白名单 / 二维码诱导关注边界); (d) CTA 话术 (「不转不是中国人」「分享解锁」黑名单); (e) 涉政 / 涉医 / 涉金融 / 涉黄 红线; (f) 软广是否标「广告」(《互联网广告管理办法》); (g) AI 生成内容是否标识 (2025-09-01 起 AI 标识办法); (h) 矩阵关联号同质化 (自媒体 13 条 + 2025 不实信息专项)"
  "(a) 这篇是 流量主 (被动 CPM) / 互选广告 / 软广 / 知识付费 funnel CTA / 私域 funnel CTA / 直接卖货 / 出版引流 哪一种 placement; (b) 该 placement 是否 fit 当前账号商业化 phase (B 流 4 阶段); (c) 时效强度 — 强 (1 周衰减, 不复用) / 中 (1 月衰减, 适合季度回看) / 弱 (1 年衰减, 可系列化 + 定期重发); (d) 是否系列化 / 后续重发节奏"
)
declare -a DIM_SOURCES=(
  "公众号后台「数据 → 用户分析 / 来源关键词」 + 历史推文 Excel / 飞书库 + 自己 12 月 voice 主张梳理 + 私域群 / 朋友圈 quick poll"
  "微信指数 (公众号内嵌) + 百度指数 + 巨量算数 + 微博热搜 + 抖音热榜 + 知微事件库 + 新榜热榜 + 看一看精选"
  "内化的流派 register + 自家 voice 模板库 + 该 vertical 头部 KOL 的同类目稿 (作参考非模仿) + AI 工具 (DeepSeek / Kimi) brainstorm 大纲"
  "《微信公众平台运营规范》原文 (developers.weixin.qq.com 微信开放社区, T06-S001) + 网信办原文 (cac.gov.cn) + 国务院《互联网广告管理办法》(T06-S015) + AI 标识办法 (T06-S011) + 微信开放社区诱导分享 / 诱导关注判定文档 (T06-S002 / S003)"
  "自家商业化路径设计 (B1.1 假设 + B4.2 5-7 路) + 该篇 internal CTA 结构 + 时效判断 (热点 / 评论 / 知识 / IP 故事 不同时效) + 历史系列效果数据"
)
declare -a DIM_OUTPUT_FORMATS=(
  "\`[选题 fit]: yes/no/conditional + 角度 (我可写的 1 个 unique 切入) + 头条/次条/三条 排位假设\`"
  "\`[热度]: 高/中/低 + 发酵时长 + [蹭与否]: 蹭/不蹭/差异化蹭 + [我的差异化角度]: 1-2 句 unique 切入\`"
  "\`[voice]: 1 派 + [结构]: 1 种 + [骨架]: 1 种 + [钩子]: 1 模板 + [大纲]: 5-8 行 bullet\`"
  "\`[8 项 check]: 通过/有风险/必修补 + [修补点]: 1-3 条 (具体改什么)\`"
  "\`[商业 placement]: 1 类 + [phase fit]: yes/no + [时效]: 强/中/弱 + [系列化建议]: 是/否 + [重发节奏]: 1 周 / 1 月 / 1 季 / 不重发\`"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
