#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 足踝外科.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="足踝外科"
DIM_COUNT=3

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (3 个):
  9.1 病史 + 临床体征评估
  9.2 影像学解读
  9.3 治疗路径选择

背后的心智模型:
  • 保守治疗优先于手术: 90% 的足踝问题不需要手术, 但很多医生 / 患者直接跳到手术决策, 跳过保守治疗黄金期。
  • 影像学发现 ≠ 临床症状原因: MRI 看到的「异常」很多跟患者主诉无关。影像跟症状对不上时, 跟着症状走, 不是跟着影像走。
  • 骨与软组织失衡是大多数慢性足踝痛的根源: 足底筋膜炎 / 跟腱病 / 拇外翻 / 平足等慢性病变, 单独干预骨或软组织效果有限, 必须看整体力学失衡。

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "病史 + 临床体征评估"
  "影像学解读"
  "治疗路径选择"
)
declare -a DIM_QUESTIONS=(
  "主诉 / 病程 / 加重缓解因素 / 体格检查 (压痛点 / 活动度 / 力学测试)"
  "X 线 / MRI / CT 的关键征象, 区分症状相关 vs incidental finding"
  "保守 vs 手术 / 时间窗 / 患者期望 / 职业需求"
)
declare -a DIM_SOURCES=(
  "完整病史采集 + 系统体格检查"
  "影像本身 + 影像科报告 + 临床体征对照"
  "患者沟通 + 循证指南 + 既往保守治疗反应"
)
declare -a DIM_OUTPUT_FORMATS=(
  "临床假设 (1-3 个鉴别诊断, 按可能性排序)"
  "哪些是病因 / 哪些是 incidental, 跟临床假设是否一致"
  "推荐方案 + 时间节点 + 失败时的备选"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
