#!/usr/bin/env bash
# topic-1.sh — —— 决策助手 for 求职 / 面试辅导(求职教练视角 — 求职定位与职业叙事 / 简历与 ATS 优化 / 求职渠道与内推策略 / 职场社交 / 行为面试与专业面试 / 面试心理与表达 / 谈薪与 offer 决策 / 校招与应届生 / 转行求职 / 特殊群体求职 / 求职教练的执业经营 — 涵盖中国大陆求职生态 + 海外英语区求职体系,两套差异极大).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="求职 / 面试辅导(求职教练视角 — 求职定位与职业叙事 / 简历与 ATS 优化 / 求职渠道与内推策略 / 职场社交 / 行为面试与专业面试 / 面试心理与表达 / 谈薪与 offer 决策 / 校招与应届生 / 转行求职 / 特殊群体求职 / 求职教练的执业经营 — 涵盖中国大陆求职生态 + 海外英语区求职体系,两套差异极大)"
TOPIC="——"

usage() {
  cat <<EOF
topic-1.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 5 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-1.sh             # interactive
  ./topic-1.sh --dry-run   # walk through but no file
  ./topic-1.sh --json      # JSON to stdout
  ./topic-1.sh --explain   # show backing playbook rules + mental models
  ./topic-1.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 —— 主题下的 playbook 规则组合成交互树。

基于 5 条规则:
  • 如果 在写简历 / 触达 / 面试答案 → 则 组织原点必须是「这个岗位 / 招聘方在解决什么问题」，不是「我有什么 / 我想说什么」—— JD 先拆成「硬性要求 / 
  • 如果 经历是「负责 X」式职责罗列 → 则 套 X-Y-Z（做到了 X，X 用 Y 衡量，靠做 Z）/ STAR 重构，每段经历必须有可衡量的 Result —— 
  • 如果 要定渠道策略（networking vs 网申） → 则 按赛道判断不站队 —— 海外科技 / 咨询 / 中高层级 / 转行场景 networking 权重高；国内校招「网申 +
  • 如果 做信息面谈 / networking 触达 → 则 守「第一次不要工作」铁律 —— 先了解、先建立关系、先给价值，不一开口就要工作 / 要内推
  • 如果 区分简历 / 面试准备的「优化」与「造假」 → 则 硬划红线 —— 量化真实成就 / ATS 关键词 / 措辞提升 / 用目标岗位语言重新包装真实技能 = 合法优化；编造经

相关心智模型:
  • 定位先于一切执行（定位错了，后面是高效地做错事）: 求职的第一性问题不是「简历怎么写 / 该投哪」，而是「要找哪一类岗位 + 为什么是我」—— 目标不收敛时，改简历、海投、练面试都是在高效地做错的事。
  • 从招聘方 / ATS / 岗位的痛点出发倒推（不是从「我想要什么」出发）: 简历、触达、面试答案的组织原点是「这个岗位 / 招聘经理在解决什么问题」，不是「我想说什么」—— 招聘经理立项前往往已缺人 6-12 个月，他要的是「缓解」。

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "在写简历 / 触达 / 面试答案"
  "经历是「负责 X」式职责罗列"
  "要定渠道策略（networking vs 网申）"
  "做信息面谈 / networking 触达"
  "区分简历 / 面试准备的「优化」与「造假」"
)
declare -a RULE_ACTIONS=(
  "组织原点必须是「这个岗位 / 招聘方在解决什么问题」，不是「我有什么 / 我想说什么」—— JD 先拆成「硬性要求 / 加分项 / 高频关键词 / 真正在解决的问题」"
  "套 X-Y-Z（做到了 X，X 用 Y 衡量，靠做 Z）/ STAR 重构，每段经历必须有可衡量的 Result —— 用数字 / 结果，不用职责描述"
  "按赛道判断不站队 —— 海外科技 / 咨询 / 中高层级 / 转行场景 networking 权重高；国内校招「网申 + 笔试」仍是主通道；大批量流程化招聘的初级岗 networking 边际收益低。先判断赛道，再配工具"
  "守「第一次不要工作」铁律 —— 先了解、先建立关系、先给价值，不一开口就要工作 / 要内推"
  "硬划红线 —— 量化真实成就 / ATS 关键词 / 措辞提升 / 用目标岗位语言重新包装真实技能 = 合法优化；编造经历 / 改头衔 / 虚构数字 / 背题库假装有不具备的能力 = 造假，背调和试用期会暴露"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-1-decision"
fi
